-- comm_explosion

return {
  ["comm_explosion"] = {
    groundflash = {
      air                = true,
      circlealpha        = 0.6,
      circlegrowth       = 50,
      flashalpha         = 2.4,
      flashsize          = 1472,
      ground             = true,
      ttl                = 35,
      water              = true,
      color = {
        [1]  = 1,
        [2]  = 0.80000001192093,
        [3]  = 0.80000001192093,
      },
    },
    pop1 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        heat               = 10,
        heatfalloff        = 0.5,
        maxheat            = 15,
        pos                = [[-55 r55, 10 r-10, r-55 r55]],
        size               = [[100 r-50]],
        sizegrowth         = 2,
        speed              = [[r-1 r1, 1 0, r-1 r1]],
        texture            = [[flowexplo]],
      },
    },
    pop2 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        heat               = 10,
        heatfalloff        = 0.4,
        maxheat            = 15,
        pos                = [[-55 r55, 10 r-10, r-55 r55]],
        size               = [[60 r-30]],
        sizegrowth         = 2,
        speed              = [[r-1 r1, 1 0, r-1 r1]],
        texture            = [[cloudexplo]],
      },
    },
    pop3 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        heat               = 10,
        heatfalloff        = 0.3,
        maxheat            = 15,
        pos                = [[-55 r55, 10 r-10, r-55 r55]],
        size               = [[40 r-20]],
        sizegrowth         = 2,
        speed              = [[r-1 r1, 1 0, r-1 r1]],
        texture            = [[mildexplo]],
      },
    },
    pop4 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        heat               = 20,
        heatfalloff        = 0.075,
        maxheat            = 40,
        pos                = [[r-2 r2, 5, r-2 r2]],
        size               = 300,
        sizegrowth         = 1.1,
        speed              = [[0, 1 0, 0]],
        texture            = [[mildexplo]],
      },
    },
    smoke1 = {
      air                = true,
      class              = [[smoke]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        agespeed           = 0.050,
        color              = [[0.5 r0.1]],
        pos                = [[r10 r-20, -50 r-10, r10 r-20]],
        size               = 15,
        sizeexpansion      = [[2 r3]],
        sizegrowth         = 1,
        speed              = [[2 r-4, 1 r-1, 2 r-4]],
        startsize          = 5,
      },
    },
  },

}

