-- vulcanflare

return {
  ["vulcanflare"] = {
    glow = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        alwaysvisible      = false,
        colormap           = [[1 1 0.7 0.01   1 1 0.8 0.9 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[-0, 1, 0]],
        gravity            = [[0, 0.00, 0]],
        numparticles       = 1,
        particlelife       = 5,
        particlelifespread = 0,
        particlesize       = 100,
        particlesizespread = 10,
        particlespeed      = 1,
        particlespeedspread = 0,
        pos                = [[0, 4, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[diamondstar]],
      },
    },
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.5 0.2 0.01 0.2 0.2 0.2 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = 40,
        sidetexture        = [[muzzleside]],
        size               = 25,
        sizegrowth         = -0.575,
        ttl                = 20,
      },
    },
    smoke_back = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1 1 0.5 0.01 1.0 0.8 0.6 0.1 0.5 0.4 0.3 0.2 0.1 0.1 0.1 0.2 0 0 0 0.001]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 30,
        particlelife       = 19,
        particlelifespread = 1,
        particlesize       = 8,
        particlesizespread = 0.4,
        particlespeed      = 1,
        particlespeedspread = 20,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    smoke_backfront = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1 1 0.5 0.01 1.0 0.8 0.6 0.1 0.5 0.4 0.3 0.2 0.1 0.1 0.1 0.2 0 0 0 0.001]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 15,
        particlelife       = 17,
        particlelifespread = 1,
        particlesize       = 12,
        particlesizespread = 0.6,
        particlespeed      = 20,
        particlespeedspread = 23,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1 1 0.5 0.01 1.0 0.8 0.6 0.1 0.5 0.4 0.3 0.2 0.1 0.1 0.1 0.2 0 0 0 0.001]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 30,
        particlelife       = 15,
        particlelifespread = 0,
        particlesize       = 4,
        particlesizespread = 2,
        particlespeed      = -5,
        particlespeedspread = -2,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 24,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.15,
        color              = [[1.0, 0.7, 0.2]],
        dir                = [[-25 r50,-25 r50,-25 r50]],
        length             = 1,
        width              = 40,
      },
    },
    windsphere = {
      air                = true,
      class              = [[CSpherePartSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.08,
        color              = [[1.0, 1.0, 1.0]],
        expansionspeed     = [[6 r6]],
        ttl                = 12,
      },
    },
  },

}

