--------------------------------------------------------------------------------
--
-- resources definitions
--
--------------------------------------------------------------------------------

local resources = {

	graphics = {
		smoke = {
			'smoke/smoke00.tga',
			'smoke/smoke01.tga',
			'smoke/smoke02.tga',
			'smoke/smoke03.tga',
			'smoke/smoke04.tga',
			'smoke/smoke05.tga',
			'smoke/smoke06.tga',
			'smoke/smoke07.tga',
			'smoke/smoke08.tga',
			'smoke/smoke09.tga',
			'smoke/smoke10.tga',
			'smoke/smoke11.tga',
		},
		scars = {
			'scars/scar1.bmp',
			'scars/scar2.bmp',
			'scars/scar3.bmp',
			'scars/scar4.bmp',
		},
		trees = {
			bark='Bark.bmp',
			leaf='bleaf.bmp',
			gran1='gran.bmp',
			gran2='gran2.bmp',
			birch1='birch1.bmp',
			birch2='birch2.bmp',
			birch3='birch3.bmp',
		},
		maps = {
			detailtex='detailtex2.bmp',
			watertex='ocean.jpg',
		},
		groundfx = {
			groundflash='groundflash.tga',
			groundring='groundring.tga',
			seismic='circles.tga',
			
		},
		projectiletextures = {
			TELEGREENBLUE1='TELEGREENBLUE1.tga',
			LightningStrike='LightningStrike.tga',
			LightningStrike_Alpha='LightningStrike_Alpha.tga',
			ExplodeHeat1='ExplodeHeat1.tga',
			flame1='flame1.tga',
			fireball1='qFireball1.tga',
			diamondstar1='DiamondStar1.tga',
			smokesmall1='qsmokesmall1.tga',
			burn1='burn1.tga',
			laserendred='laserendred.tga',
			NarrowBoltNoisy='NarrowBoltNoisy.tga',
			EMG='EMG.tga',
			Type6Beam='Type6Beam.tga',
			PlasmaHeatB='PlasmaHeatB.tga',
			PlasmaHeatG='PlasmaHeatG.tga',
			ConeFragments1='ConeFragments1.tga',
			Fire1='Fire1.tga',
			GenericSmokeCloud1='GenericSmokeCloud1.tga',
			Type4Beam='Type4Beam.tga',
			circularthingy='circularthingy.tga',
			laserend='laserend.tga',
			laserfalloff='laserfalloff.tga',
			randdots='randdots.tga',
			smoketrail='smoketrail.tga',
			wake='wake.tga',
			explo='explo.tga',
			explofade='explofade.tga',
			heatcloud='explo.tga',
			flame='flame.tga',
			graysmoke='graysmoke.tga',
			smokeorange='gpl/smoke_orange.png',
			fireball='fireball.tga',
        		laserendpink='laserendpink.tga',
			flare='flare.tga',
			shard1='shard1.tga',
			shard2='shard2.tga',
			shard3='shard3.tga',
			"2explo='2explo.tga'",
			redexplo='redexplo.tga',
			purpleexplo='purpleexplo.tga',
			blueexplo='blueexplo.tga',
			pinkexplo='pinkexplo.tga',
			brightblueexplo='brightblueexplo.tga',
			bluenovaexplo='bluenovaexplo.tga',
			muzzleside='muzzleside.png',
			muzzlefront='muzzlefront.png',
			bigexplo='bigexplo.tga',
			bigexplosmoke='bigexplosmoke.tga',
			sakexplo='sakexplo.tga',
			sparkexplo='sparkexplo.tga',
			cloudexplo='cloudexplo.tga',
			flowexplo='flowexplo.tga',
			flowexplo2='flowexplo2.tga',
			mildexplo='mildexplo.tga',
			spikeexplo='spikeexplo.tga',
			starexplo='starexplo.tga',
			greenexplo='greenexplo.tga',
			PlasmaPure='PlasmaPure.tga',
			gunshot='CC/gunshot.tga',
			flash1='flash1.tga',
			flash2='flash2.tga',
			flash3='flash3.tga',
			armsmoketrail='armsmoketrail.tga',
			coresmoketrail='coresmoketrail.tga',
			shotgunflare='shotgunflare.tga',
			lightb='PD/lightningball.tga',
			lightning='PD/lightning.tga',
			plasma='GPL/plasma.tga',
			flashside1='flashside1.tga',
			shotgunside='shotgunside.tga',
			megaparticle='megaparticle.tga',
			shot='shot.tga',	
			beamrifle='beamrifle.tga',
			beamrifletip='beamrifletip.tga',
			smallflare='GPL/smallflare.tga',			
			dirt='CC/dirt.png',
			smoke='smoke/smoke00.tga',
			diamondstar='diamondstar.tga',
			whitelight='lightw.bmp',
			yellowlight='lighty.bmp',
			redlight='lightr.png',
			sporetrail='GPL/sporetrail.tga',
			null='PD/null.tga',
			bluenovaexplo='bluenovaexplo.tga',
			randdots='randdots.tga',
			blueexploredexplo='blueexploredexplo.tga',
			bombsmoke='bombsmoke.tga',
		},
	},
}

--------------------------------------------------------------------------------

return resources

--------------------------------------------------------------------------------
