return {
	armgripn_bomb = {
		areaofeffect = 240,
		collidefriendly = 0,
		commandfire = 1,
		craterboost = 0,
		cratermult = 0,
		edgeeffectiveness = 0.75,
		explosiongenerator = "custom:EMPFLASH240",
		firestarter = 90,
		impulseboost = 0,
		impulsefactor = 0,
		name = "EMPbomb",
		noselfdamage = 1,
		paralyzer = 1,
		paralyzetime = 12,
		range = 1280,
		reloadtime = 0.3,
		soundhit = "EMGPULS1",
		soundstart = "bombrel",
		tolerance = 7000,
		damage = {
			commanders = 1000,
			default = 4000,
		},
	},
}
