-- bluelaserbighit

return {
  ["bluelaserbighit"] = {
    usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 0.5,
      circlegrowth       = 2,
      flashalpha         = 0.66,
      flashsize          = 100,
      ttl                = 10,
      color = {
        [1]  = 0.30000001192093,
        [2]  = 0.5,
        [3]  = 0.89999997615814,
      },
    },
    spark_sprey_short = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.9,
        colormap           = [[1.0 1.0 1.0 0.1		0.6 0.6 1.0 0.05  0 0 0 0.01]],
        directional        = true,
        emitrot            = -2,
        emitrotspread      = -2,
        emitvector         = [[dir]],
        gravity            = [[0, -0.00, 0]],
        numparticles       = 1,
        particlelife       = 50,
        particlelifespread = 20,
        particlesize       = 35,
        particlesizespread = 15,
        particlespeed      = 4,
        particlespeedspread = 0.1,
        pos                = [[0, 2, 0]],
        sizegrowth         = -0.02,
        sizemod            = 1.0,
        texture            = [[splash]],
        useairlos          = true,
      },
    },
    spark_sprey_wide = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.9,
        colormap           = [[0.5 0.6 0.9 0.4		0.3 0.3 0.8 0.3  0.1 0.1 0.5 0.05  0 0 0 0.01]],
        directional        = true,
        emitrot            = 10,
        emitrotspread      = 1,
        emitvector         = [[dir]],
        gravity            = [[0, -0.0, 0]],
        numparticles       = 20,
        particlelife       = 80,
        particlelifespread = 120,
        particlesize       = 15,
        particlesizespread = 0.5,
        particlespeed      = 3,
        particlespeedspread = 6,
        pos                = [[0, 2, 0]],
        sizegrowth         = -0.02,
        sizemod            = 1.0,
        texture            = [[smoke]],
        useairlos          = true,
      },
    },
    spikesofhell1 = {
      air                = true,
      class              = [[explspike]],
      count              = 10,
      ground             = true,
      water              = false,
      properties = {
        alpha              = 1,
        alphadecay         = 0.06,
        color              = [[0.5, 0.5, 1.0]],
        dir                = [[-5 r10,-5 r10,-5 r10]],
        length             = 1,
        width              = 40,
      },
    },
  },

}

