-- debree3
-- debree4
-- nanodebree1
-- debree5
-- large_debree5
-- debree1
-- debree0
-- debree2
-- large_debree2
-- nanodebree0

return {
  ["debree3"] = {
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.2 0.7 1.0 0.01 0.1 0.2 0.3 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -6,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 1,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.3,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 5,
      },
    },
  },

  ["debree4"] = {
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.3 0.8 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -6,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 1,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.75,
        color              = [[1.0, 0.3, 0.0]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 5,
      },
    },
  },

  ["nanodebree1"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.4,
        colormap           = [[0.0 0.0 0.0 0.00 0.0 0.0 0.0 0.0 0.01 0.01 0.01 0.05 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 20,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 1,
        particlelifespread = 30,
        particlesize       = 3,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 2,
        pos                = [[0, 1, 0]],
        sizegrowth         = 1.3,
        sizemod            = 1.0,
        texture            = [[antilagsmoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[0.2 1.0 0.2 0.01 0.1 0.1 0.1 0.2 0.01 0.01 0.01 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 20,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 1,
        particlelifespread = 20,
        particlesize       = 8,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 5,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[diamondstar]],
      },
    },
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.2 0.7 0.2 0.01 0.1 0.3 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -6,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 2,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.4,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 5,
      },
    },
  },

  ["debree5"] = {
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.5 0 0.01 0.6 0.2 0 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -4,
        sidetexture        = [[muzzleside]],
        size               = -4,
        sizegrowth         = 0.65,
        ttl                = 1,
      },
    },
    smoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1 0.5 0 1  0.6 0.2 0 0.8	0.1 0.1 0.1 0.6 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0, 0.2, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 4,
        particlelife       = 4,
        particlelifespread = 16,
        particlesize       = 0.5,
        particlesizespread = 3,
        particlespeed      = 2,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[0.0 r.65]],
        sizemod            = 1.0,
        texture            = [[GenericSmokeCloud1]],
        useairlos          = true,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.75,
        color              = [[1.0, 0.3, 0.0]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 2,
        width              = 2,
      },
    },
  },

  ["large_debree5"] = {
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.5 0 0.01 0.6 0.2 0 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -6,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 1,
      },
    },
    smoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1 0.5 0 1  0.6 0.2 0 0.8	0.1 0.1 0.1 0.6 0 0 0 0.01]],
        directional        = true,
        emitdir            = [[dir]],
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0, 0.2, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 5,
        particlelife       = 6,
        particlelifespread = 16,
        particlesize       = 1,
        particlesizespread = 3,
        particlespeed      = 2,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[0.0 r.65]],
        sizemod            = 1.0,
        texture            = [[GenericSmokeCloud1]],
        useairlos          = true,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.75,
        color              = [[1.0, 0.3, 0.0]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 3,
        width              = 3,
      },
    },
  },

  ["debree1"] = {
    usedefaultexplosions = false,
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[1.0 0.6 0.2 0.01 0.02 0.02 0.02 0.1 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 20,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 1,
        particlelifespread = 20,
        particlesize       = 7,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 2,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -6,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 1,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.6,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 5,
      },
    },
  },

  ["debree0"] = {
    usedefaultexplosions = false,
  },

  ["debree2"] = {
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.3 0.8 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -6,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 1,
      },
    },
    smoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.5,
        colormap           = [[1 0.45 0.0 0.8  0.7 0.5 0.0 0.5	0.1 0.1 0.1 0.5 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0, 0.2, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 5,
        particlelife       = 6,
        particlelifespread = 16,
        particlesize       = 0.6,
        particlesizespread = 3,
        particlespeed      = 2,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[0.0 r.65]],
        sizemod            = 1.0,
        texture            = [[GenericSmokeCloud1]],
        useairlos          = true,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.75,
        color              = [[1.0, 0.3, 0.0]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 5,
      },
    },
  },

  ["large_debree2"] = {
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.3 0.8 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -6,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 1,
      },
    },
    smoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1 0.45 0.0 0.8  0.7 0.5 0.0 0.5	0.1 0.1 0.1 0.5 0 0 0 0.01]],
        directional        = true,
        emitdir            = [[dir]],
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0, 0.2, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 5,
        particlelife       = 6,
        particlelifespread = 16,
        particlesize       = 1,
        particlesizespread = 3,
        particlespeed      = 2,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[0.0 r.65]],
        sizemod            = 1.0,
        texture            = [[GenericSmokeCloud1]],
        useairlos          = true,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.75,
        color              = [[1.0, 0.3, 0.0]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 5,
      },
    },
  },

  ["nanodebree0"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.4,
        colormap           = [[0.0 0.0 0.0 0.00 0.0 0.0 0.0 0.0 0.01 0.01 0.01 0.05 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 20,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 1,
        particlelifespread = 30,
        particlesize       = 3,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 2,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.6,
        sizemod            = 1.0,
        texture            = [[antilagsmoke]],
      },
    },
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.2 0.7 1.0 0.01 0.1 0.2 0.3 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -6,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 2,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.4,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 5,
      },
    },
  },
   ["small_debree"] = {
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.3 0.8 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -6,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 1,
      },
    },
    smoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1 0.45 0.0 0.8  0.7 0.5 0.0 0.5	0.1 0.1 0.1 0.5 0 0 0 0.01]],
        directional        = true,
        emitdir            = [[dir]],
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0, 0.2, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 5,
        particlelife       = 6,
        particlelifespread = 16,
        particlesize       = 1,
        particlesizespread = 3,
        particlespeed      = 2,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[0.0 r.65]],
        sizemod            = 1.0,
        texture            = [[clouds2]],
        useairlos          = true,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.75,
        color              = [[1.0, 0.3, 0.0]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 5,
      },
    },
  },

}

