-- kbotrockethit

return {
  ["kbotrockethit"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.77,
        colormap           = [[0.7 0.5 0.4 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 12,
        particlelife       = 90,
        particlelifespread = 30,
        particlesize       = 3,
        particlesizespread = 2,
        particlespeed      = -5,
        particlespeedspread = 10,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    groundflash = {
      air                = true,
      circlealpha        = 0,
      circlegrowth       = 0,
      flashalpha         = 0.3,
      flashsize          = 80,
      ground             = true,
      ttl                = 30,
      water              = true,
      color = {
        [1]  = 0.33000001311302,
        [2]  = 0.20000000298023,
        [3]  = 0.20000000298023,
      },
    },
    sparkystuff = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.95,
        alwaysvisible      = true,
        colormap           = [[1 1 1 0.01   1 0.7 0.2 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 28,
        emitrotspread      = 65,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.45, 0]],
        numparticles       = 8,
        particlelife       = 32,
        particlelifespread = 0,
        particlesize       = 2.5,
        particlesizespread = 2.4,
        particlespeed      = 5.4,
        particlespeedspread = 1.8,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[flamespark]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 12,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.07,
        color              = [[1.0, 0.5, 0.4]],
        dir                = [[-6 r12,-6 r12,-6 r12]],
        length             = 1,
        width              = 20,
      },
    },
  },

}

