-- trail_dmc_cannon

return {
  ["trail_dmc_core"] = {
    usedefaultexplosions = false,
     Spawner_dmc_sparkels = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 32, --32
      ground             = false,
      water              = false,
      unit               = false,
      properties = {
        explosiongenerator = [[custom:dmc_sparkels_core]],
        pos                = [[0 r-10 r10, 0 r-10 r10, 0 r-10 r10]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.5,
        alphadecay         = 0.18,
        color              = [[1, 0.2, 0.2]],
        dir                = [[-4 r6,-4 r6,-4 r6]],
        length             = 13,
        width              = 23,
      },
    },
  },
   ["dmc_sparkels_core"] = {
    sparkels = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = false,
      water              = false,
      properties = {
        airdrag            = .75,
        colormap           = [[1 0.8 0.8 .005		1 0.2 0.2 .005      	0 0 0 0.001]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0.2, 0.2, 0.2]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 4,
        particlelifespread = 16,
        particlesize       = 0.02,
        particlesizespread = 2,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.2,
        sizemod            = 1.0,
        texture            = [[EMG]],
        useairlos          = true,
      },
    },
  },
  ["trail_dmc_arm"] = {
    usedefaultexplosions = false,
     Spawner_dmc_sparkels = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 32, --32
      ground             = false,
      water              = false,
      unit               = false,
      properties = {
        explosiongenerator = [[custom:dmc_sparkels_arm]],
        pos                = [[0 r-10 r10, 0 r-10 r10, 0 r-10 r10]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.5,
        alphadecay         = 0.18,
        color              = [[0.2, 0.2, 1]],
        dir                = [[-4 r6,-4 r6,-4 r6]],
        length             = 13,
        width              = 23,
      },
    },
  },
    ["dmc_sparkels_arm"] = {
     sparkels = {
       air                = true,
       class              = [[CSimpleParticleSystem]],
       count              = 1,
       ground             = false,
       water              = false,
       properties = {
         airdrag            = .75,
         colormap           = [[0.8 0.8 1.0 .005		0.2 0.2 1 .005      	0 0 0 0.001]],
         directional        = true,
         emitrot            = 0,
         emitrotspread      = 0,
         emitvector         = [[0.2, 0.2, 0.2]],
         gravity            = [[0, 0, 0]],
         numparticles       = 1,
         particlelife       = 4,
         particlelifespread = 16,
         particlesize       = 0.02,
         particlesizespread = 2,
         particlespeed      = 1,
         particlespeedspread = 1,
         pos                = [[0, 0, 0]],
         sizegrowth         = 0.2,
         sizemod            = 1.0,
         texture            = [[EMG]],
         useairlos          = true,
       },
     },
   },
   ["trail_dmc_tll"] = {
     usedefaultexplosions = false,
      Spawner_dmc_sparkels = {
       air                = true,
       class              = [[CExpGenSpawner]],
       count              = 32, --32
       ground             = false,
       water              = false,
       unit               = false,
       properties = {
         explosiongenerator = [[custom:dmc_sparkels_tll]],
         pos                = [[0 r-10 r10, 0 r-10 r10, 0 r-10 r10]],
       },
     },
     spikes = {
       air                = true,
       class              = [[explspike]],
       count              = 3,
       ground             = true,
       water              = true,
       properties = {
         alpha              = 0.5,
         alphadecay         = 0.18,
         color              = [[1.0 0.7 0.4]],
         dir                = [[-4 r6,-4 r6,-4 r6]],
         length             = 13,
         width              = 23,
       },
     },
   },
   ["dmc_sparkels_tll"] = {
    sparkels = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = false,
      water              = false,
      properties = {
        airdrag            = .75,
        colormap           = [[1 0.8 0.7 .005		1.0 0.7 0.4 .005      	0 0 0 0.001]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0.2, 0.2, 0.2]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 4,
        particlelifespread = 16,
        particlesize       = 0.02,
        particlesizespread = 2,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.2,
        sizemod            = 1.0,
        texture            = [[EMG]],
        useairlos          = true,
      },
    },
  },
  ["trail_dmc_talon"] = {
    usedefaultexplosions = false,
     Spawner_dmc_sparkels = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 32, --32
      ground             = false,
      water              = false,
      unit               = false,
      properties = {
        explosiongenerator = [[custom:dmc_sparkels_talon]],
        pos                = [[0 r-10 r10, 0 r-10 r10, 0 r-10 r10]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.5,
        alphadecay         = 0.18,
        color              = [[0.1 0.9 1.0]],
        dir                = [[-4 r6,-4 r6,-4 r6]],
        length             = 13,
        width              = 23,
      },
    },
  },
  ["dmc_sparkels_talon"] = {
   sparkels = {
     air                = true,
     class              = [[CSimpleParticleSystem]],
     count              = 1,
     ground             = false,
     water              = false,
     properties = {
       airdrag            = .75,
       colormap           = [[0.8 0.8 1 .005	0.1 0.9 1.0 .005      	0 0 0 0.001]],
       directional        = true,
       emitrot            = 0,
       emitrotspread      = 0,
       emitvector         = [[0.2, 0.2, 0.2]],
       gravity            = [[0, 0, 0]],
       numparticles       = 1,
       particlelife       = 4,
       particlelifespread = 16,
       particlesize       = 0.02,
       particlesizespread = 2,
       particlespeed      = 1,
       particlespeedspread = 1,
       pos                = [[0, 0, 0]],
       sizegrowth         = 0.2,
       sizemod            = 1.0,
       texture            = [[EMG]],
       useairlos          = true,
     },
   },
  },
  ["trail_dmc_gok"] = {
    usedefaultexplosions = false,
     Spawner_dmc_sparkels = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 32, --32
      ground             = false,
      water              = false,
      unit               = false,
      properties = {
        explosiongenerator = [[custom:dmc_sparkels_gok]],
        pos                = [[0 r-10 r10, 0 r-10 r10, 0 r-10 r10]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.5,
        alphadecay         = 0.18,
        color              = [[0.78 0.08 0.55]],
        dir                = [[-4 r6,-4 r6,-4 r6]],
        length             = 12,
        width              = 12,
      },
    },
  },
  ["dmc_sparkels_gok"] = {
   sparkels = {
     air                = true,
     class              = [[CSimpleParticleSystem]],
     count              = 1,
     ground             = false,
     water              = false,
     properties = {
       airdrag            = .75,
       colormap           = [[0.78 0.08 0.55 0.1		0.78 0.08 0.55 .005      	0 0 0 0.001]],
       directional        = true,
       emitrot            = 0,
       emitrotspread      = 0,
       emitvector         = [[0.2, 0.2, 0.2]],
       gravity            = [[0, 0, 0]],
       numparticles       = 1,
       particlelife       = 4,
       particlelifespread = 16,
       particlesize       = 0.02,
       particlesizespread = 2,
       particlespeed      = 1,
       particlespeedspread = 1,
       pos                = [[0, 0, 0]],
       sizegrowth         = 0.2,
       sizemod            = 1.0,
       texture            = [[EMG]],
       useairlos          = true,
     },
   },
  },
  ["trail_dmc_rumad"] = {
    usedefaultexplosions = false,
     Spawner_dmc_sparkels = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 32, --32
      ground             = false,
      water              = false,
      unit               = false,
      properties = {
        explosiongenerator = [[custom:dmc_sparkels_rumad]],
        pos                = [[0 r-10 r10, 0 r-10 r10, 0 r-10 r10]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.5,
        alphadecay         = 0.18,
        color              = [[0.9, 0.9, 0.9]],
        dir                = [[-4 r6,-4 r6,-4 r6]],
        length             = 13,
        width              = 23,
      },
    },
  },
    ["dmc_sparkels_rumad"] = {
     sparkels = {
       air                = true,
       class              = [[CSimpleParticleSystem]],
       count              = 1,
       ground             = false,
       water              = false,
       properties = {
         airdrag            = .75,
         colormap           = [[0.8 0.8 0.8 .005		1 1 1 .005      	0 0 0 0.001]],
         directional        = true,
         emitrot            = 0,
         emitrotspread      = 0,
         emitvector         = [[0.2, 0.2, 0.2]],
         gravity            = [[0, 0, 0]],
         numparticles       = 1,
         particlelife       = 4,
         particlelifespread = 16,
         particlesize       = 0.02,
         particlesizespread = 2,
         particlespeed      = 1,
         particlespeedspread = 1,
         pos                = [[0, 0, 0]],
         sizegrowth         = 0.2,
         sizemod            = 1.0,
         texture            = [[EMG]],
         useairlos          = true,
       },
     },
   },
}
