return {
	ametalmakerlvl2 = {
		activatewhenbuilt = true,
		buildcostenergy = 750000,
		buildcostmetal = 19650,
		builder = false,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 6,
		buildinggrounddecalsizey = 6,
		buildinggrounddecaltype = "ametalmakerlvl2_aoplane.dds",
		buildtime = 200000,
		category = "ALL NOTDEFENSE NOTHOVERNOTVTOL NOTMOBILE NOTSUB NOTSUBNOTSHIP NOTVTOL NOTWEAPON",
		corpse = "dead",
		damagemodifier = 0.25,
		description = "Converts upto 16000 Energy to Metal",
		designation = "AEM-MEM",
		energystorage = 0,
		explodeas = "nuclear_missile1",
		floater = false,
		footprintx = 4,
		footprintz = 4,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 53.75679,
		mass = 23119,
		maxdamage = 5000,
		maxslope = 20,
		maxwaterdepth = 0,
		metalstorage = 0,
		name = "T3 Metal Maker",
		nochasecategory = "ALL",
		objectname = "AMetalMakerLvl2",
		radardistance = 0,
		radaremitheight = 53.75679,
		script = "armmmkr.cob",
		selfdestructas = "nuclear_missile1",
		side = "ARM",
		sightdistance = 210,
		unitname = "ametalmakerlvl2",
		usebuildinggrounddecal = true,
		workertime = 0,
		yardmap = "oooo oooo oooo oooo",
		featuredefs = {
			dead = {
				blocking = true,
				category = "core_corpses",
				damage = 3000,
				description = "T3 Metalmaker Wreckage",
				featuredead = "heap",
				featurereclamate = "smudge01",
				footprintx = 4,
				footprintz = 4,
				height = 20,
				hitdensity = 100,
				metal = 18495.20117,
				object = "AMetalMakerLvl2_dead",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 1800.00012,
				description = "T3 Metalmaker Heap",
				featurereclamate = "smudge01",
				footprintx = 4,
				footprintz = 4,
				height = 4,
				hitdensity = 100,
				metal = 14796.16016,
				object = "AMetalMakerLvl2_heap",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
		},
		sounds = {
			activate = "metlon1",
			canceldestruct = "cancel2",
			deactivate = "metloff1",
			underattack = "warning1",
			working = "metlrun1",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "metlon1",
			},
		},
	},
}
