return {
	arm_bagheera = {
		acceleration = 0.09,
		autoheal = 100,
		brakerate = 0.63,
		buildcostenergy = 410000,
		buildcostmetal = 22850,
		builder = false,
		buildpic = "arm_bagheera.dds",
		buildtime = 300000,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL HUGE MOBILE SURFACE UNDERWATER",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "135 100 135",
		collisionvolumetype = "Ell",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "All-Terrain Experimental Kbot (Auto-Repair 100)",
		explodeas = "BANTHA_BLAST",
		firestandorders = 1,
		footprintx = 5,
		footprintz = 5,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 131,
		maneuverleashlength = 640,
		mass = 22850,
		maxdamage = 64050,
		maxslope = 20,
		maxvelocity = 1.3,
		maxwaterdepth = 25,
		mobilestandorders = 1,
		movementclass = "HTKBOT6",
		name = "Bagheera",
		noautofire = false,
		objectname = "arm/arm_bagheera.s3o",
		radaremitheight = 100,
		selfdestructas = "KROG_BLAST",
		selfdestructcountdown = 10,
		sightdistance = 700,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 2,
		turninplaceanglelimit = 120,
		turninplacespeedlimit = 1.12,
		turnrate = 225,
		unitname = "arm_bagheera",
		--upright = true,
		customparams = {
			buildpic = "arm_bagheera.dds",
			faction = "ARM",
			normaltex = "unittextures/arm_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 89400,
				description = "Raptor Wreckage",
				featuredead = "heap",
				footprintx = 6,
				footprintz = 6,
				object = "arm/arm_bagheera_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				damage = 145500,
				description = "Raptor Debris",
				footprintx = 6,
				footprintz = 6,
				object = "6x6d.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"mavbok1",
			},
			select = {
				"mavbsel1",
			},
		},
		weapondefs = {
			bagheera_multilaser = {
				areaofeffect = 24,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				energypershot = 300,
				firestarter = 90,
				impulseboost = 0,
				impulsefactor = 0,
				name = "Vengence Laser",
				range = 900,
				reloadtime = 0.2,
				rgbcolor = "0.18 0.10 0.65",
				soundhitdry = "xplosml3",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "Lasrhvy2",
				thickness = 2,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 1200,
				damage = {
					default = 300,
					subs = 5,
				},
			},
			arm_rocket = {
				areaofeffect = 96,
				avoidfeature = false,
				cegtag = "armstartbursttrail",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:incendiary_explosion_medium",
				firestarter = 70,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				metalpershot = 0,
				model = "weapon_starburstm.s3o",
				name = "Heavy Rockets",
				noselfdamage = true,
				proximitypriority = -1,
				range = 1050,
				reloadtime = 1,
				rgbcolor = "1.000 0.000 0.000",
				smoketrail = false,
				soundhitdry = "xplosml2",
				soundhitwet = "splsmed",
				soundhitwetvolume = 0.6,
				soundstart = "rocklit1",
				startvelocity = 200,
				targetable = 16,
				texture1 = "null",
				texture2 = "null",
				texture3 = "null",
				texture4 = "null",
				tolerance = 9000,
				tracks = false,
				turnrate = 50000,
				weaponacceleration = 230,
				weapontimer = 2,
				weapontype = "StarburstLauncher",
				weaponvelocity = 4000,
				customparams = {
					light_color = "1 0.6 0.15",
					light_mult = 3.3,
					light_radius_mult = 1.9,
				},
				damage = {
					default = 500,
					subs = 5,
				},
			},
		},
		weapons = {
			{
				badtargetcategory = "LARGE MINOR SMALL MEDIUM MINOR",
				def = "bagheera_multilaser",
				onlytargetcategory = "SURFACE",
			},
			{
				badtargetcategory = "MINOR",
				def = "arm_rocket",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
