return {
	arm_ulab = {
		buildcostenergy = 1479050,
		buildcostmetal = 85630,
		builder = true,
		buildinggrounddecaldecayspeed = 0.01,
		buildinggrounddecalsizex = 20,
		buildinggrounddecalsizey = 20,
		buildinggrounddecaltype = "arm_ulab_aoplane.dds",
		buildpic = "arm_ulab.dds",
		buildtime = 1000000,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "LEVEL3 ALL SURFACE",
		corpse = "dead",
		collisionvolumeoffsets = "0 -5 -20",
		collisionvolumescales = "250 200 235",
		collisionvolumetype = "Box",
		description = "Produces T4 Units",
		explodeas = "LARGE_BUILDINGEX",
		firestandorders = 1,
		footprintx = 18,
		footprintz = 12,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 174,
		mass = 85630,
		maxdamage = 59680,
		maxslope = 18,
		maxwaterdepth = 0,
		mobilestandorders = 1,
		name = "Prototype Lab",
		noautofire = false,
		objectname = "arm/arm_ulab.s3o",
		radaremitheight = 174,
		seismicsignature = 0,
		selfdestructas = "LARGE_BUILDING",
		shownanospray = false,
		sightdistance = 273,
		standingfireorder = 2,
		standingmoveorder = 1,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0,
		turnrate = 0,
		unitname = "arm_ulab",
		workertime = 1600,
		yardmap = "oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo yooooooooooooooooy yyccccccccccccccyy yyccccccccccccccyy yyccccccccccccccyy yoccccccccccccccoy ooccccccccccccccoo ooccccccccccccccoo ooccccccccccccccoo ooccccccccccccccoo",
		buildoptions = {
			[1] = "armspid",
			[2] = "armraptor",
			[3] = "armbeetle",
			[4] = "armpraet",
			[5] = "armmcv1",
			[6] = "armolympus",
			[7] = "armmygalo",
			[8] = "armstratus",
			[9] = "armlift",
		},
		customparams = {
			buildpic = "arm_ulab.dds",
			faction = "ARM",
			normaltex = "unittextures/arm_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 39519,
				description = "Prototype Pod Wreckage",
				energy = 0,
				featuredead = "heap",
				footprintx = 16,
				footprintz = 16,
				metal = 67200,
				object = "arm/arm_ulab_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				damage = 49399,
				description = "Prototype Mech Lab Debris",
				energy = 0,
				footprintx = 18,
				footprintz = 18,
				metal = 35840,
				object = "7x7c.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		nanocolor = {
			[1] = 0.34,
			[2] = 0.69,
			[3] = 0.69,
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:YellowLight",
				[2] = "custom:GantWhiteLight",
			},
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			activate = "gantok2",
			build = "gantok2",
			canceldestruct = "cancel2",
			deactivate = "gantok2",
			repair = "lathelrg",
			underattack = "warning1",
			unitcomplete = "gantok1",
			working = "build",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "gantsel1",
			},
		},
	},
}
