-- UNITDEF -- ARM_FURIE --
--------------------------------------------------------------------------------

local unitName = "arm_furie"

--------------------------------------------------------------------------------

local unitDef = {
	acceleration = 0.09,
	bmcode = 1,
	brakeRate = 0.2,
	buildCostEnergy = 486664,
	buildCostMetal = 35089,
	builder = false,
	buildTime = 502193,
	canAttack = true,
	canGuard = true,
	canMove = true,
	canPatrol = true,
	canstop = 1,
	cantBeTransported = true,
	category = [[ALL HUGE MOBILE NOTDEFENSE NOTHOVERNOTVTOL NOTSUB NOTSUBNOTSHIP NOTVTOL WEAPON]],
	collisionvolumeoffsets = [[0 -5 -3]],
	collisionvolumescales = [[47 58 28]],
	collisionvolumetype = [[Box]],
	corpse = [[dead]],
	defaultmissiontype = [[Standby]],
	description = [[The Legendary Kbot]],
	designation = [[ARM-KL]],
	energyMake = 1.1,
	energyStorage = 0,
	energyUse = 1.1,
	explodeAs = [[NUCLEAR_MISSILE2]],
	firestandorders = 1,
	footprintX = 5,
	footprintZ = 5,
	iconType = [[building]],
	idleAutoHeal = 7,
	idleTime = 1800,
	immunetoparalyzer = 1,
	maneuverleashlength = 640,
	mass = 200000,
	maxDamage = 188788,
	maxSlope = 17,
	maxVelocity = 1.1,
	maxWaterDepth = 12,
	metalStorage = 0,
	mobilestandorders = 1,
	movementClass = [[VKBOT5]],
	name = [[Arm Furie]],
	noAutoFire = false,
	noChaseCategory = [[SUB VTOL]],
	objectName = [[ARM_FURIE]],
	radarDistance = 0,
	selfDestructAs = [[NUCLEAR_MISSILE1]],
	selfDestructCountdown = 20,
	shootme = 1,
	side = [[ARM]],
	sightDistance = 485,
	standingfireorder = 2,
	standingmoveorder = 1,
	steeringmode = 2,
	turnRate = 560,
	unitname = [[arm_furie]],
	unitnumber = 7218,
	workerTime = 0,
	customparams = {
		RequireTech = [[Advanced T3 Unit Research Centre]],
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = [[custom:furie_muzzle]],
			[2] = [[custom:arm_furie_muzzle]],
		},
        },
	featureDefs = nil,
	sounds = {
		canceldestruct = [[cancel2]],
		underattack = [[warning1]],
		cant = {
			[1] = [[cantdo4]],
		},
		count = {
			[1] = [[count6]],
			[2] = [[count5]],
			[3] = [[count4]],
			[4] = [[count3]],
			[5] = [[count2]],
			[6] = [[count1]],
		},
		ok = {
			[1] = [[krogok1]],
		},
		select = {
			[1] = [[krogsel1]],
		},
	},
	weaponDefs = nil,
	weapons = {
		[1] = {
			def = [[ARM_FURIE_HEAD]],
			onlyTargetCategory = [[NOTVTOL]],
		},
		[2] = {
			def = [[ARM_FURIE_FIRE]],
			onlyTargetCategory = [[NOTVTOL]],
		},
		[3] = {
			def = [[ARM_FURIE_ROCKET]],
			onlyTargetCategory = [[NOTVTOL]],
		},
	},
}

--------------------------------------------------------------------------------

local weaponDefs = {
	ARM_FURIE_FIRE = {
		accuracy = 10,
		areaOfEffect = 8,
		beamWeapon = true,
		burnblow = false,
		--cegTag = [[trail_furie]],
		coreThickness = 0.5,
		craterBoost = 0,
		craterMult = 0,
		energypershot = 0,
		explosionGenerator = [[custom:armfurie_fire_explosion]],
		guidance = true,
		impulseBoost = 0,
		intensity = 1,
		lineOfSight = true,
		name = [[Gauss Cannon2]],
		range = 800,
		reloadtime = 0.1,
		renderType = 0,
		rgbColor = [[1 0.95 0.4]],
		selfprop = true,
		soundHitDry = [[xplomed2]],
		soundStart = [[gatling]],
		soundStartVolume = 15,
		soundTrigger = true,
		startsmoke = 1,
		texture1 = [[beamrifle]],
		texture2 = [[NULL]],
		texture3 = [[NULL]],
		thickness = 1.5,
		tolerance = 2000,
		turret = true,
		unitsonly = 1,
		weaponTimer = 1,
		weaponType = [[LaserCannon]],
		weaponVelocity = 250,
		damage = {
			default = 150,
			subs = 5,
		},
	},
	ARM_FURIE_HEAD = {
		areaOfEffect = 8,
		beamlaser = 1,
		beamTime = 0.7,
		coreThickness = 0.3,
		craterBoost = 0,
		craterMult = 0,
		energypershot = 2100,
		explosionGenerator = [[custom:FLASH3blue]],
		impactonly = 1,
		impulseBoost = 0,
		impulseFactor = 0,
		laserFlareSize = 22,
		lineOfSight = true,
		name = [[MINI ATAD]],
		noSelfDamage = true,
		range = 1000,
		reloadtime = 9,
		renderType = 0,
		rgbColor = [[0 0 1]],
		soundHitDry = [[xplosml3]],
		soundStart = [[annigun1]],
		targetMoveError = 0.3,
		thickness = 3.5,
		tolerance = 10000,
		turret = true,
		weaponType = [[BeamLaser]],
		weaponVelocity = 1500,
		damage = {
			commanders = 2100,
			default = 5000,
			subs = 5,
		},
	},
	ARM_FURIE_ROCKET = {
		areaOfEffect = 80,
		cegTag = [[ARMRAVENTRAIL]],
		craterBoost = 0,
		craterMult = 0,
		fireStarter = 70,
		flightTime = 4,
		guidance = true,
		explosionGenerator = [[custom:incendiary_explosion_small]],
		impulseBoost = 0,
		impulseFactor = 0,
		lineOfSight = true,
		metalpershot = 0,
		model = [[fmdmisl]],
		name = [[Heavy Rockets2]],
		range = 1100,
		reloadtime = 1.1,
		renderType = 1,
		rgbColor = [[1.000 0.000 0.000]],
		selfprop = true,
		smokedelay = 0.1,
		smokeTrail = false,
		soundHitDry = [[xplosml2]],
		soundStart = [[rocklit1]],
		startsmoke = 1,
		startVelocity = 250,
		Texture1 = [[null]],
		Texture2 = [[null]],
		Texture3 = [[null]],
		Texture4 = [[null]],
		tolerance = 9000,
		tracks = true,
		turnRate = 63000,
		vlaunch = true,
		weaponAcceleration = 200,
		weaponTimer = 2.5,
		weaponType = [[StarburstLauncher]],
		weaponVelocity = 450,
		damage = {
			default = 700,
			subs = 5,
		},
	},
}
unitDef.weaponDefs = weaponDefs


--------------------------------------------------------------------------------

local featureDefs = {
	dead = {
		blocking = true,
		category = [[arm_corpses]],
		damage = 0.6000 * unitDef.maxDamage,
		description = [[Legendary Wreckage]],
		featureDead = [[furie_heap]],
		featurereclamate = [[smudge01]],
		footprintX = 3,
		footprintZ = 3,
		height = 20,
		hitdensity = 100,
		metal = 0.8000 * unitDef.buildCostMetal,
		object = [[arm_furie_dead]],
		reclaimable = true,
		seqnamereclamate = [[tree1reclamate]],
		world = [[All Worlds]],
	},
	furie_heap = {
		blocking = false,
		category = [[heaps]],
		damage = 0.3600 * unitDef.maxDamage,
		description = [[Legendary Heap]],
		featurereclamate = [[smudge01]],
		footprintX = 3,
		footprintZ = 3,
		height = 4,
		hitdensity = 100,
		metal = 0.6400 * unitDef.buildCostMetal,
		object = [[3x3a]],
		reclaimable = true,
		seqnamereclamate = [[tree1reclamate]],
		world = [[All Worlds]],
	},
}
unitDef.featureDefs = featureDefs

--------------------------------------------------------------------------------

return lowerkeys({[unitName] = unitDef})

--------------------------------------------------------------------------------