local Def = {
	armarty = {
		acceleration = 0.016,
		badTargetCategory = [[VTOL]],
		bmcode = 1,
		brakeRate = 0.01,
		buildCostEnergy = 2546,
		buildCostMetal = 395,
		buildTime = 5104,
		builder = false,
		canAttack = true,
		canGuard = true,
		canMove = true,
		canPatrol = true,
		canstop = 1,
		category = [[ALL TANK MOBILE WEAPON NOTSUB NOTSHIP NOTAIR]],
		copyright = [[Copyright 1997 Humongous Entertainment. All rights reserved.]],
		corpse = [[dead]],
		defaultmissiontype = [[Standby]],
		description = [[Level 1 Artillery]],
		designation = [[ARM-ART5]],
		downloadable = 1,
		energyMake = 0.6,
		energyStorage = 0,
		energyUse = 0.6,
		explodeAs = [[BIG_UNITEX]],
		featureDefs = {
			dead = {
				blocking = true,
				category = [[arm_corpses]],
				damage = nil,
				description = nil,
				featureDead = [[heap]],
				featurereclamate = [[smudge01]],
				footprintX = 2,
				footprintZ = 2,
				height = 20,
				hitdensity = 100,
				metal = nil,
				object = [[ARMARTY_dead]],
				reclaimable = true,
				seqnamereclamate = [[tree1reclamate]],
				world = [[All Worlds]],
			},
			heap = {
				blocking = false,
				category = [[heaps]],
				damage = nil,
				description = nil,
				featurereclamate = [[smudge01]],
				footprintX = 2,
				footprintZ = 2,
				height = 4,
				hitdensity = 100,
				metal = nil,
				object = [[2x2d]],
				reclaimable = true,
				seqnamereclamate = [[tree1reclamate]],
				world = [[All Worlds]],
			},
		},
		firestandorders = 1,
		footprintX = 2,
		footprintZ = 2,
		frenchdescription = [[Artillerie de niv.1]],
		germandescription = [[L1 Artillerie]],
		maneuverleashlength = 640,
		maxDamage = 458,
		maxSlope = 10,
		maxVelocity = 1.4,
		maxWaterDepth = 12,
		metalStorage = 0,
		mobilestandorders = 1,
		movementClass = [[TANK2]],
		name = [[Gladius]],
		noAutoFire = false,
		noChaseCategory = [[VTOL]],
		objectName = [[ARMARTY]],
		radarDistance = 0,
		selfDestructAs = [[BIG_UNIT]],
		shootme = 1,
		side = [[ARM]],
		sightDistance = 780,
		sounds = {
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[cantdo4]],
			},
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			ok = {
				[1] = [[tarmmove]],
			},
			select = {
				[1] = [[tarmsel]],
			},
			underattack = [[warning1]],
		},
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		threed = 1,
		turnRate = 450,
		unitname = [[armarty]],
		unitnumber = 3524,
		upright = true,
		version = 1,
		weaponDefs = {
			LVL1_GUN = {
				accuracy = 300,
				areaOfEffect = 72,
				ballistic = true,
				craterBoost = 0,
				craterMult = 0,
				damage = {
					default = 112,
				},
				explosionart = [[explode3]],
				explosiongaf = [[fx]],
				gravityaffected = [[true]],
				id = 119,
				impulseBoost = 0,
				impulseFactor = 0,
				lavaexplosionart = [[lavasplash]],
				lavaexplosiongaf = [[fx]],
				minbarrelangle = -10,
				name = [[Light Artillery Cannon]],
				noSelfDamage = true,
				range = 1090,
				reloadtime = 3,
				renderType = 4,
				soundHit = [[xplomed4]],
				soundStart = [[cannhvy2]],
				startsmoke = 1,
				turret = true,
				waterexplosionart = [[h2o]],
				waterexplosiongaf = [[fx]],
				weaponType = [[Cannon]],
				weaponVelocity = 410,
			},
		},
		weapons = {
			[1] = {
				badTargetCategory = [[VTOL]],
				def = [[LVL1_GUN]],
				onlyTargetCategory = [[NOTAIR]],
			},
		},
		workerTime = 0,
		zbuffer = 1,
	},
}
Def.armarty.featureDefs.dead.damage = 0.6000 * Def.armarty.maxDamage
Def.armarty.featureDefs.dead.description = Def.armarty.name .. [[ Wreckage]]
Def.armarty.featureDefs.dead.metal = 0.8000 * Def.armarty.buildCostMetal
Def.armarty.featureDefs.heap.damage = 0.3600 * Def.armarty.maxDamage
Def.armarty.featureDefs.heap.description = Def.armarty.name .. [[ Heap]]
Def.armarty.featureDefs.heap.metal = 0.6400 * Def.armarty.buildCostMetal
return lowerkeys(Def)
