return {
	armawac = {
		acceleration = 0.04095,
		altfromsealevel = 1,
		bankscale = 1,
		brakerate = 0.05,
		buildcostenergy = 8599,
		buildcostmetal = 176,
		builder = false,
		buildpic = "ARMAWAC.png",
		buildtime = 12819,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MEDIUMVTOL MOBILE NOTDEFENSE NOTSUB NOTSUBNOTSHIP NOTWEAPON VTOL",
		collide = false,
		cruisealt = 160,
		defaultmissiontype = "VTOL_standby",
		description = "Radar/Sonar Plane",
		energymake = 23,
		energystorage = 0,
		energyuse = 23,
		explodeas = "BIG_UNITEX",
		footprintx = 3,
		footprintz = 3,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		maneuverleashlength = 1280,
		mass = 176,
		maxdamage = 800,
		maxslope = 10,
		maxvelocity = 10.58,
		maxwaterdepth = 0,
		metalstorage = 0,
		mobilestandorders = 1,
		name = "Eagle",
		noautofire = false,
		nochasecategory = "SUB VTOL",
		objectname = "ARMAWAC",
		radardistance = 2500,
		scale = 1,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT_VTOL",
		side = "ARM",
		sightdistance = 1275,
		sonardistance = 1200,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 6.9828,
		turnrate = 392,
		unitname = "armawac",
		workertime = 0,
		customparams = {
			buildpic = "ARMAWAC.png",
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "aaradsel",
			},
		},
	},
}
