local Def = {
	armflak = {
		acceleration = 0,
		badTargetCategory = [[NOWEAPON]],
		bmcode = 0,
		brakeRate = 0,
		buildAngle = 8192,
		buildCostEnergy = 37425,
		buildCostMetal = 969,
		buildPic = [[ARMFLAK.png]],
		buildTime = 19005,
		builder = false,
		canAttack = true,
		canstop = 1,
		category = [[ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR]],
		corpse = [[DEAD]],
		defaultmissiontype = [[GUARD_NOMOVE]],
		description = [[Anti-Air Flak Gun]],
		energyStorage = 0,
		energyUse = 0,
		explodeAs = [[MEDIUM_BUILDINGEX]],
		featureDefs = {
			DEAD = {
				blocking = true,
				category = [[corpses]],
				damage = nil,
				description = nil,
				energy = 0,
				featureDead = [[HEAP]],
				featurereclamate = [[SMUDGE01]],
				footprintX = 2,
				footprintZ = 2,
				height = 20,
				hitdensity = 100,
				metal = nil,
				object = [[ARMFLAK_DEAD]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
			HEAP = {
				blocking = false,
				category = [[heaps]],
				damage = nil,
				description = nil,
				energy = 0,
				featurereclamate = [[SMUDGE01]],
				footprintX = 2,
				footprintZ = 2,
				height = 4,
				hitdensity = 100,
				metal = nil,
				object = [[2X2C]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
		},
		firestandorders = 1,
		footprintX = 2,
		footprintZ = 2,
		iconType = [[building]],
		idleAutoHeal = 5,
		idleTime = 1800,
		maxDamage = 5575,
		maxSlope = 10,
		maxVelocity = 0,
		maxWaterDepth = 0,
		metalStorage = 0,
		name = [[Flakker]],
		noAutoFire = false,
		noChaseCategory = [[ALL]],
		objectName = [[ARMFLAK]],
		seismicSignature = 0,
		selfDestructAs = [[MEDIUM_BUILDING]],
		side = [[ARM]],
		sightDistance = 525,
		smoothAnim = true,
		sounds = {
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[cantdo4]],
			},
			cloak = [[kloak1]],
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			ok = {
				[1] = [[twrturn3]],
			},
			select = {
				[1] = [[twrturn3]],
			},
			uncloak = [[kloak1un]],
			underattack = [[warning1]],
		},
		standingfireorder = 2,
		turnRate = 0,
		unitname = [[armflak]],
		weaponDefs = {
			ARMFLAK_GUN = {
				accuracy = 1000,
				areaOfEffect = 192,
				ballistic = true,
				burnblow = true,
				canattackground = false,
				color = 1,
				craterBoost = 0,
				craterMult = 0,
				damage = {
					default = 0,
					gunships = 500,
					hgunships = 500,
					l1bombers = 550,
					l1fighters = 170,
					l2bombers = 1100,
					l2fighters = 950,
					vradar = 600,
					vtol = 200,
					vtrans = 200,
				},
				edgeEffectiveness = 0.85,
				explosionGenerator = [[custom:FLASH3]],
				gravityaffected = [[true]],
				impulseBoost = 0,
				impulseFactor = 0,
				minbarrelangle = -24,
				name = [[FlakCannon]],
				noSelfDamage = true,
				range = 975,
				reloadtime = 0.4,
				renderType = 4,
				size = 5,
				soundHit = [[flakhit]],
				soundStart = [[flakfire]],
				startsmoke = 1,
				toAirWeapon = true,
				turret = true,
				unitsonly = 1,
				weaponTimer = 1,
				weaponType = [[Cannon]],
				weaponVelocity = 1550,
			},
		},
		weapons = {
			[1] = {
				badTargetCategory = [[NOWEAPON]],
				def = [[ARMFLAK_GUN]],
			},
		},
		workerTime = 0,
		yardMap = [[oooo]],
	},
}
Def.armflak.featureDefs.DEAD.damage = 0.6000 * Def.armflak.maxDamage
Def.armflak.featureDefs.DEAD.description = Def.armflak.name .. [[ Wreckage]]
Def.armflak.featureDefs.DEAD.metal = 0.8000 * Def.armflak.buildCostMetal
Def.armflak.featureDefs.HEAP.damage = 0.3600 * Def.armflak.maxDamage
Def.armflak.featureDefs.HEAP.description = Def.armflak.name .. [[ Heap]]
Def.armflak.featureDefs.HEAP.metal = 0.6400 * Def.armflak.buildCostMetal
return lowerkeys(Def)
