local Def = {
	armhlt1 = {
		acceleration = 0,
		badTargetCategory = [[ANTILASER]],
		bmcode = 0,
		brakeRate = 0,
		buildAngle = 8192,
		buildCostEnergy = 8900,
		buildCostMetal = 745,
		buildPic = [[ARMHLT.png]],
		buildTime = 17000,
		builder = false,
		canAttack = true,
		canstop = 1,
		category = [[ALL NOTMOBILE NOTVTOL NOTSUB NOTSUBNOTSHIP NOTHOVERNOTVTOL]],
		corpse = [[ARMHLT_DEAD]],
		defaultmissiontype = [[GUARD_NOMOVE]],
		description = [[Heavy Laser Tower]],
		energyStorage = 1000,
		energyUse = 0,
		explodeAs = [[MEDIUM_BUILDINGEX]],
		featureDefs = {
			ARMHLT_DEAD = {
				blocking = true,
				category = [[corpses]],
				damage = nil,
				description = [[Sentinel Wreckage]],
				energy = 0,
				featureDead = [[ARMHLT_HEAP]],
				featurereclamate = [[SMUDGE01]],
				footprintX = 2,
				footprintZ = 2,
				height = 20,
				hitdensity = 100,
				metal = nil,
				object = [[ARMHLT_DEAD]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
			ARMHLT_HEAP = {
				blocking = false,
				category = [[heaps]],
				damage = nil,
				description = [[Sentinel Heap]],
				energy = 0,
				featurereclamate = [[SMUDGE01]],
				footprintX = 2,
				footprintZ = 2,
				height = 4,
				hitdensity = 100,
				metal = nil,
				object = [[2X2A]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
		},
		firestandorders = 1,
		footprintX = 2,
		footprintZ = 2,
		iconType = [[building]],
		idleAutoHeal = 5,
		idleTime = 1800,
		maxDamage = 3500,
		maxSlope = 10,
		maxVelocity = 0,
		maxWaterDepth = 0,
		metalStorage = 0,
		name = [[High-Energy Sentinel]],
		noAutoFire = false,
		noChaseCategory = [[ALL]],
		objectName = [[ARMHLT]],
		seismicSignature = 0,
		selfDestructAs = [[MEDIUM_BUILDING]],
		side = [[ARM]],
		sightDistance = 494,
		smoothAnim = true,
		sounds = {
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[cantdo4]],
			},
			cloak = [[kloak1]],
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			ok = {
				[1] = [[twractv3]],
			},
			select = {
				[1] = [[twractv3]],
			},
			uncloak = [[kloak1un]],
			underattack = [[warning1]],
		},
		standingfireorder = 2,
		turnRate = 0,
		unitname = [[armhlt1]],
		weaponDefs = {
			ARM_LASERH2 = {
				areaOfEffect = 20,
				beamTime = 0.7,
				beamlaser = 1,
				coreThickness = 0.45,
				craterBoost = 0,
				craterMult = 0,
				damage = {
					commanders = 1200,
					default = 920,
					gunships = 35,
					hgunships = 35,
					l1bombers = 35,
					l1fighters = 35,
					l1subs = 5,
					l2bombers = 35,
					l2fighters = 35,
					l2subs = 5,
					l3subs = 5,
					vradar = 35,
					vtol = 35,
					vtrans = 35,
				},
				energypershot = 150,
				explosionGenerator = [[custom:GreenLaser]],
				fireStarter = 90,
				impulseBoost = 0.123,
				impulseFactor = 0.123,
				laserFlareSize = 20,
				lineOfSight = true,
				name = [[HighEnergyLaser]],
				noSelfDamage = true,
				range = 700,
				reloadtime = 1.5,
				renderType = 0,
				rgbColor = [[0 1 0]],
				soundHit = [[lasrhit1]],
				soundStart = [[Lasrmas2]],
				targetMoveError = 0.2,
				thickness = 3,
				tolerance = 10000,
				turret = true,
				weaponType = [[BeamLaser]],
				weaponVelocity = 2850,
			},
		},
		weapons = {
			[1] = {
				badTargetCategory = [[ANTILASER]],
				def = [[ARM_LASERH2]],
			},
		},
		workerTime = 0,
		yardMap = [[oooo]],
	},
}
Def.armhlt1.featureDefs.ARMHLT_DEAD.damage = 0.6000 * Def.armhlt1.maxDamage
Def.armhlt1.featureDefs.ARMHLT_DEAD.metal = 0.8000 * Def.armhlt1.buildCostMetal
Def.armhlt1.featureDefs.ARMHLT_HEAP.damage = 0.3600 * Def.armhlt1.maxDamage
Def.armhlt1.featureDefs.ARMHLT_HEAP.metal = 0.6400 * Def.armhlt1.buildCostMetal
return lowerkeys(Def)
