return {
	armjanus = {
		acceleration = 0.0198,
		brakerate = 0.165,
		buildcostenergy = 2537,
		buildcostmetal = 242,
		builder = false,
		buildpic = "armjanus.dds",
		buildtime = 3200,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MEDIUM MOBILE SURFACE UNDERWATER",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "35 20 49",
		collisionvolumetype = "Box",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Twin Medium Rocket Launcher",
		explodeas = "BIG_UNITEX",
		firestandorders = 1,
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		losemitheight = 22,
		maneuverleashlength = 640,
		mass = 272,
		maxdamage = 925,
		maxslope = 10,
		maxvelocity = 1.95,
		maxwaterdepth = 12,
		mobilestandorders = 1,
		movementclass = "TANK2",
		name = "Janus",
		noautofire = false,
		objectname = "arm/armjanus.s3o",
		radaremitheight = 25,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 325,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		trackoffset = 3,
		trackstrength = 6,
		trackstretch = 1,
		tracktype = "StdTank",
		trackwidth = 24,
		turninplace = 0,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1.2,
		turnrate = 320,
		unitname = "armjanus",
		customparams = {
			buildpic = "armjanus.dds",
			faction = "ARM",
			normaltex = "unittextures/arm_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumeoffsets = "-1.45095062256 -4.56400614014 0.266441345215",
				collisionvolumescales = "28.8743438721 18.1917877197 33.2305145264",
				collisionvolumetype = "Box",
				damage = 1086,
				description = "Janus Wreckage",
				energy = 0,
				featuredead = "heap",
				footprintx = 2,
				footprintz = 2,
				metal = 216,
				object = "arm/armjanus_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				damage = 1358,
				description = "Janus Debris",
				energy = 0,
				footprintx = 2,
				footprintz = 2,
				metal = 115,
				object = "2x2c.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"tarmmove",
			},
			select = {
				"tarmsel",
			},
		},
		weapondefs = {
			janus_rocket = {
				areaofeffect = 150,
				avoidfeature = false,
				cegtag = "Arm_Janus_Rocket",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:VEHROCKET_EXPLOSION",
				firestarter = 70,
				impulsefactor = 1,
				model = "weapon_janusrocket.s3o",
				name = "HeavyRocket",
				noselfdamage = true,
				range = 420,
				reloadtime = 8,
				smoketrail = true,
				soundhitdry = "xplosml2",
				soundhitvolume = 8,
				soundhitwet = "splslrg",
				soundhitwetvolume = 0.6,
				soundstart = "rocklit1",
				soundstartvolume = 7,
				startvelocity = 190,
				texture1 = "null",
				texture2 = "null",
				texture3 = "null",
				texture4 = "null",
				tracks = false,
				trajectoryheight = 0.4,
				turret = true,
				weaponacceleration = 100,
				weapontimer = 3,
				weapontype = "MissileLauncher",
				weaponvelocity = 190,
				damage = {
					default = 360,
					subs = 5,
				},
			},
		},
		weapons = {
			{
				def = "JANUS_ROCKET",
				onlytargetcategory = "SURFACE",
			},
			{
				def = "JANUS_ROCKET",
				onlytargetcategory = "SURFACE",
				slaveto = 1,
			},
		},
	},
}