-- UNITDEF -- ARMMLS --
--------------------------------------------------------------------------------

local unitName = "armmls"

--------------------------------------------------------------------------------

local unitDef = {
	acceleration = 0.05,
	bmcode = 1,
	brakeRate = 0.07,
	buildCostEnergy = 3725,
	buildCostMetal = 213,
	buildDistance = 200,
	builder = true,
	buildPic = [[ARMMLS.png]],
	buildTime = 5247,
	canGuard = true,
	canMove = true,
	canPatrol = true,
	canstop = 1,
	category = [[ALL CONSTR MEDIUM MOBILE NOTDEFENSE NOTHOVERNOTVTOL NOTSUB NOTVTOL NOTWEAPON]],
	corpse = [[DEAD]],
	defaultmissiontype = [[Standby]],
	description = [[Naval Engineer]],
	energyMake = 0.5,
	energyStorage = 0,
	energyUse = 0.5,
	explodeAs = [[SMALL_UNITEX]],
	floater = true,
	footprintX = 4,
	footprintZ = 4,
	iconType = [[sea]],
	idleAutoHeal = 5,
	idleTime = 1800,
	maneuverleashlength = 640,
	maxDamage = 1314,
	maxVelocity = 2.4,
	metalStorage = 0,
	minWaterDepth = 15,
	mobilestandorders = 1,
	movementClass = [[BOAT4]],
	name = [[Valiant]],
	noAutoFire = false,
	noChaseCategory = [[VTOL]],
	objectName = [[ARMMLS]],
	seismicSignature = 0,
	selfDestructAs = [[SMALL_UNIT]],
	side = [[arm]],
	sightDistance = 260,
	smoothAnim = true,
	standingmoveorder = 1,
	steeringmode = 1,
	terraformSpeed = 1200,
	turnRate = 388,
	unitname = [[armmls]],
	workerTime = 400,
	buildoptions = {
		[1] = [[armtide]],
		[2] = [[armuwmex]],
		[3] = [[armasy]],
		[4] = [[asubpen]],
		[5] = [[armhevsenan]],
		[6] = [[armfhp]],
		[7] = [[armeyes]],
		[8] = [[armfrad]],
		[9] = [[armsonar]],
		[10] = [[armfmine3]],
		[11] = [[armfhlt]],
		[12] = [[armtl]],
		[13] = [[armfrt]],
		[14] = [[armcs]],
		[15] = [[armpt]],
		[16] = [[decade]],
		[17] = [[armroy]],
		[18] = [[armsub]],
		[19] = [[armbeaver]],
		[20] = [[armbats]],
	},
	featureDefs = nil,
	sounds = {
		build = [[nanlath1]],
		canceldestruct = [[cancel2]],
		repair = [[repair1]],
		underattack = [[warning1]],
		working = [[reclaim1]],
		cant = {
			[1] = [[cantdo4]],
		},
		count = {
			[1] = [[count6]],
			[2] = [[count5]],
			[3] = [[count4]],
			[4] = [[count3]],
			[5] = [[count2]],
			[6] = [[count1]],
		},
		ok = {
			[1] = [[sharmmov]],
		},
		select = {
			[1] = [[sharmsel]],
		},
	},
}

--------------------------------------------------------------------------------

local featureDefs = {
	DEAD = {
		blocking = true,
		category = [[corpses]],
		damage = 0.6000 * unitDef.maxDamage,
		description = unitDef.name .. [[ Wreckage]],
		energy = 0,
		featureDead = [[HEAP]],
		featurereclamate = [[SMUDGE01]],
		footprintX = 4,
		footprintZ = 4,
		height = 20,
		hitdensity = 100,
		metal = 0.8000 * unitDef.buildCostMetal,
		object = [[ARMMLS_DEAD]],
		reclaimable = true,
		seqnamereclamate = [[TREE1RECLAMATE]],
		world = [[All Worlds]],
	},
	HEAP = {
		blocking = false,
		category = [[heaps]],
		damage = 0.3600 * unitDef.maxDamage,
		description = unitDef.name .. [[ Heap]],
		energy = 0,
		footprintX = 2,
		footprintZ = 2,
		height = 4,
		hitdensity = 100,
		metal = 0.6400 * unitDef.buildCostMetal,
		object = [[4X4A]],
		reclaimable = true,
		seqnamereclamate = [[TREE1RECLAMATE]],
		world = [[All Worlds]],
	},
}
unitDef.featureDefs = featureDefs

--------------------------------------------------------------------------------

return lowerkeys({[unitName] = unitDef})

--------------------------------------------------------------------------------
