local Def = {
	armmav = {
		acceleration = 0.12,
		autoHeal = 50,
		badTargetCategory = [[VTOL]],
		bmcode = 1,
		brakeRate = 0.125,
		buildCostEnergy = 12180,
		buildCostMetal = 655,
		buildPic = [[ARMMAV.png]],
		buildTime = 18384,
		builder = false,
		canAttack = true,
		canGuard = true,
		canMove = true,
		canPatrol = true,
		canstop = 1,
		category = [[ALL MOBILE NOTVTOL NOTSUB NOTDEFENSE MEDIUM NOTSUBNOTSHIP NOTHOVERNOTVTOL]],
		corpse = [[DEAD]],
		defaultmissiontype = [[Standby]],
		description = [[Skirmish Kbot (Combat Auto-Repair)]],
		energyMake = 0.4,
		energyStorage = 0,
		energyUse = 0.4,
		explodeAs = [[BIG_UNITEX]],
		featureDefs = {
			DEAD = {
				blocking = true,
				category = [[arm_corpses]],
				damage = nil,
				description = nil,
				featureDead = [[heap]],
				featurereclamate = [[smudge01]],
				footprintX = 2,
				footprintZ = 2,
				height = 20,
				hitdensity = 100,
				metal = nil,
				object = [[armmav_dead]],
				reclaimable = true,
				seqnamereclamate = [[tree1reclamate]],
				world = [[All Worlds]],
			},
			heap = {
				blocking = false,
				category = [[heaps]],
				damage = nil,
				description = nil,
				featurereclamate = [[smudge01]],
				footprintX = 2,
				footprintZ = 2,
				height = 4,
				hitdensity = 100,
				metal = nil,
				object = [[2x2e]],
				reclaimable = true,
				seqnamereclamate = [[tree1reclamate]],
				world = [[All Worlds]],
			},
		},
		firestandorders = 1,
		footprintX = 2,
		footprintZ = 2,
		idleAutoHeal = 5,
		idleTime = 1800,
		maneuverleashlength = 640,
		maxDamage = 1120,
		maxSlope = 14,
		maxVelocity = 1.65,
		maxWaterDepth = 0,
		metalStorage = 0,
		mobilestandorders = 1,
		movementClass = [[KBOT2]],
		name = [[Maverick]],
		noAutoFire = false,
		noChaseCategory = [[VTOL SUB]],
		objectName = [[ARMMAV]],
		seismicSignature = 0,
		selfDestructAs = [[BIG_UNIT]],
		side = [[ARM]],
		sightDistance = 550,
		smoothAnim = true,
		sounds = {
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[cantdo4]],
			},
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			ok = {
				[1] = [[mavbok1]],
			},
			select = {
				[1] = [[mavbsel1]],
			},
			underattack = [[warning1]],
		},
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 2,
		turnRate = 1118,
		unitname = [[armmav]],
		upright = true,
		weaponDefs = {
			ARMMAV_WEAPON = {
				areaOfEffect = 8,
				damage = {
					default = 280,
					gunships = 70,
					hgunships = 70,
					l1bombers = 70,
					l1fighters = 70,
					l1subs = 5,
					l2bombers = 70,
					l2fighters = 70,
					l2subs = 5,
					l3subs = 5,
					vradar = 70,
					vtol = 70,
					vtrans = 70,
				},
				explosionGenerator = [[custom:FLASH1]],
				impactonly = 1,
				lineOfSight = true,
				minbarrelangle = -15,
				name = [[GaussCannon]],
				noSelfDamage = true,
				range = 365,
				reloadtime = 0.945,
				renderType = 4,
				soundHit = [[xplomed2]],
				soundStart = [[Mavgun2]],
				startsmoke = 1,
				tolerance = 4000,
				turret = true,
				weaponType = [[Cannon]],
				weaponVelocity = 500,
			},
		},
		weapons = {
			[1] = {
				badTargetCategory = [[VTOL]],
				def = [[ARMMAV_WEAPON]],
			},
		},
		workerTime = 0,
	},
}
Def.armmav.featureDefs.DEAD.damage = 0.6000 * Def.armmav.maxDamage
Def.armmav.featureDefs.DEAD.description = Def.armmav.name .. [[ Heap]]
Def.armmav.featureDefs.DEAD.metal = 0.8000 * Def.armmav.buildCostMetal
Def.armmav.featureDefs.heap.damage = 0.3600 * Def.armmav.maxDamage
Def.armmav.featureDefs.heap.description = Def.armmav.name .. [[ Heap]]
Def.armmav.featureDefs.heap.metal = 0.6400 * Def.armmav.buildCostMetal
return lowerkeys(Def)
