return {
	armor = {
		acceleration = 0.2,
		antiweapons = 1,
		bankscale = 1,
		bmcode = 1,
		brakerate = 6.25,
		buildcostenergy = 40000,
		buildcostmetal = 2500,
		builder = false,
		buildpic = "armor.png",
		buildtime = 25000,
		canattack = true,
		canfly = true,
		canguard = true,
		canload = 1,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MOBILE NOTDEFENSE NOTSUB NOTSUBNOTSHIP NOTWEAPON VTOL",
		cruisealt = 250,
		defaultmissiontype = "VTOL_standby",
		description = "Very Heavy Air Transport, Min load 2000 - Max Load 14000",
		energymake = 0.6,
		energystorage = 0,
		energyuse = 0.6,
		explodeas = "BIG_UNITEX",
		firestandorders = 1,
		footprintx = 4,
		footprintz = 4,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 3000,
		losemitheight = 28.8,
		maneuverleashlength = 1280,
		mass = 2500,
		maxdamage = 13500,
		maxslope = 15,
		maxvelocity = 2.55,
		maxwaterdepth = 0,
		metalstorage = 0,
		mintransportmass = 2000,
		mobilestandorders = 1,
		name = "Ornith",
		nochasecategory = "SUB VTOL",
		objectname = "ARMOR",
		radardistance = 0,
		radaremitheight = 28.8,
		scale = 0.8,
		selfdestructas = "BIG_UNIT_VTOL",
		shootme = 1,
		side = "ARM",
		sightdistance = 660,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		tedclass = "VTOL",
		transportcapacity = 1,
		transportmass = 15000,
		transportsize = 25,
		turnrate = 420,
		unitname = "armor",
		workertime = 0,
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
	},
}
