local Def = {
	armsnipe = {
		acceleration = 0.12,
		bmcode = 1,
		brakeRate = 0.188,
		buildCostEnergy = 14727,
		buildCostMetal = 535,
		buildPic = [[ARMSNIPE.png]],
		buildTime = 19137,
		builder = false,
		canAttack = true,
		canGuard = true,
		canMove = true,
		canPatrol = true,
		canstop = 1,
		category = [[KBOT MOBILE WEAPON ALL NOTSHIP NOTAIR]],
		cloakCost = 75,
		cloakCostMoving = 200,
		corpse = [[DEAD]],
		defaultmissiontype = [[Standby]],
		description = [[Sniper Kbot]],
		energyMake = 0.9,
		energyStorage = 0,
		energyUse = 0.9,
		explodeAs = [[BIG_UNITEX]],
		featureDefs = {
			DEAD = {
				blocking = true,
				category = [[corpses]],
				damage = nil,
				description = nil,
				energy = 0,
				featureDead = [[HEAP]],
				featurereclamate = [[SMUDGE01]],
				footprintX = 2,
				footprintZ = 2,
				height = 20,
				hitdensity = 100,
				metal = nil,
				object = [[ARMSNIPE_DEAD]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
			HEAP = {
				blocking = false,
				category = [[heaps]],
				damage = nil,
				description = nil,
				energy = 0,
				featurereclamate = [[SMUDGE01]],
				footprintX = 2,
				footprintZ = 2,
				height = 4,
				hitdensity = 100,
				metal = nil,
				object = [[2X2D]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
		},
		firestandorders = 1,
		footprintX = 2,
		footprintZ = 2,
		idleAutoHeal = 5,
		idleTime = 1800,
		maneuverleashlength = 640,
		maxDamage = 520,
		maxSlope = 14,
		maxVelocity = 1.26,
		maxWaterDepth = 22,
		metalStorage = 0,
		minCloakDistance = 80,
		mobilestandorders = 1,
		movementClass = [[KBOT2]],
		name = [[Sharpshooter]],
		objectName = [[ARMSNIPE]],
		onlyTargetCategory = [[NOTAIR]],
		radarDistanceJam = 10,
		selfDestructAs = [[BIG_UNIT]],
		side = [[ARM]],
		sightDistance = 455,
		smoothAnim = true,
		sounds = {
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[cantdo4]],
			},
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			ok = {
				[1] = [[kbarmmov]],
			},
			select = {
				[1] = [[kbarmsel]],
			},
			underattack = [[warning1]],
		},
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 2,
		turnRate = 1338,
		unitname = [[armsnipe]],
		upright = true,
		weaponDefs = {
			ARMSNIPE_WEAPON = {
				areaOfEffect = 16,
				beamWeapon = true,
				collideFriendly = false,
				craterBoost = 0,
				craterMult = 0,
				damage = {
					commanders = 1025,
					default = 2500,
					l1subs = 5,
					l2subs = 5,
					l3subs = 5,
					t3mechs = 5400,
				},
				duration = 0.0025,
				energypershot = 500,
				explosionGenerator = [[custom:FLASH1nd]],
				impactonly = 1,
				impulseBoost = 0.234,
				impulseFactor = 0.234,
				intensity = 0.75,
				lineOfSight = true,
				name = [[SniperWeapon]],
				noSelfDamage = true,
				noradar = 1,
				range = 900,
				reloadtime = 10,
				renderType = 0,
				rgbColor = [[1 1 0]],
				soundHit = [[xplolrg2]],
				soundHitVolume = 4,
				soundStart = [[sniper2]],
				soundStartVolume = 4,
				thickness = 0.5,
				turret = true,
				weaponType = [[LaserCannon]],
				weaponVelocity = 3000,
			},
		},
		weapons = {
			[1] = {
				def = [[ARMSNIPE_WEAPON]],
				onlyTargetCategory = [[NOTAIR]],
			},
		},
		workerTime = 0,
	},
}
Def.armsnipe.featureDefs.DEAD.damage = 0.6000 * Def.armsnipe.maxDamage
Def.armsnipe.featureDefs.DEAD.description = Def.armsnipe.name .. [[ Wreckage]]
Def.armsnipe.featureDefs.DEAD.metal = 0.8000 * Def.armsnipe.buildCostMetal
Def.armsnipe.featureDefs.HEAP.damage = 0.3600 * Def.armsnipe.maxDamage
Def.armsnipe.featureDefs.HEAP.description = Def.armsnipe.name .. [[ Heap]]
Def.armsnipe.featureDefs.HEAP.metal = 0.6400 * Def.armsnipe.buildCostMetal
return lowerkeys(Def)
