local Def = {
	armsam1 = {
		acceleration = 0.0396,
		badTargetCategory = [[ALL]],
		bmcode = 1,
		brakeRate = 0.0165,
		buildCostEnergy = 3227,
		buildCostMetal = 290,
		buildPic = [[ARMSAM.png]],
		buildTime = 3745,
		builder = false,
		canAttack = true,
		canGuard = true,
		canMove = true,
		canPatrol = true,
		canstop = 1,
		category = [[ARM TANK MOBILE WEAPON NOTAIR NOTSUB NOTSHIP ALL]],
		corpse = [[ARMSAM_DEAD]],
		defaultmissiontype = [[Standby]],
		description = [[Missile Truck]],
		energyMake = 0.5,
		energyStorage = 0,
		energyUse = 0.5,
		explodeAs = [[BIG_UNITEX]],
		featureDefs = {
			ARMSAM_DEAD = {
				blocking = true,
				category = [[corpses]],
				damage = nil,
				description = nil,
				energy = 0,
				featureDead = [[ARMSAM_HEAP]],
				featurereclamate = [[SMUDGE01]],
				footprintX = 3,
				footprintZ = 3,
				height = 20,
				hitdensity = 100,
				metal = nil,
				object = [[ARMSAM_DEAD]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
			ARMSAM_HEAP = {
				blocking = false,
				category = [[heaps]],
				damage = nil,
				description = nil,
				energy = 0,
				featurereclamate = [[SMUDGE01]],
				footprintX = 3,
				footprintZ = 3,
				height = 4,
				hitdensity = 100,
				metal = nil,
				object = [[3X3D]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
		},
		firestandorders = 1,
		footprintX = 3,
		footprintZ = 3,
		idleAutoHeal = 5,
		idleTime = 1800,
		leaveTracks = true,
		maneuverleashlength = 640,
		maxDamage = 1365,
		maxSlope = 16,
		maxVelocity = 1.605,
		maxWaterDepth = 12,
		metalStorage = 0,
		mobilestandorders = 1,
		movementClass = [[TANK3]],
		name = [[Godlike Samson]],
		noAutoFire = false,
		noChaseCategory = [[VTOL]],
		objectName = [[ARMSAM1]],
		seismicSignature = 0,
		selfDestructAs = [[BIG_UNIT]],
		sfxtypes = {
			explosiongenerators = {
				[1] = [[custom:rocketflare]],
			},
		},
		side = [[ARM]],
		sightDistance = 670,
		smoothAnim = true,
		sounds = {
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[cantdo4]],
			},
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			ok = {
				[1] = [[varmmove]],
			},
			select = {
				[1] = [[varmsel]],
			},
			underattack = [[warning1]],
		},
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		trackOffset = -6,
		trackStrength = 5,
		trackStretch = 1,
		trackType = [[StdTank]],
		trackWidth = 32,
		turnRate = 497,
		unitname = [[armsam1]],
		weaponDefs = {
			ARMTRUCK_MISSILE1 = {
				areaOfEffect = 24,
				burst = 2,
				burstrate = 0.25,
				craterBoost = 0,
				craterMult = 0,
				damage = {
					commanders = 30,
					default = 45,
				},
				explosionGenerator = [[custom:FLASH2]],
				fireStarter = 70,
				guidance = true,
				impulseBoost = 0.123,
				impulseFactor = 0.123,
				lineOfSight = true,
				metalpershot = 0,
				model = [[missile]],
				name = [[Missiles]],
				noSelfDamage = true,
				range = 640,
				reloadtime = 4.5,
				renderType = 1,
				selfprop = true,
				smokeTrail = true,
				smokedelay = 0.1,
				soundHit = [[xplomed2]],
				soundStart = [[rockhvy2]],
				soundTrigger = true,
				startVelocity = 450,
				startsmoke = 1,
				texture2 = [[armsmoketrail]],
				tolerance = 8000,
				tracks = true,
				trajectoryHeight = 0.9,
				turnRate = 63000,
				turret = true,
				weaponAcceleration = 108,
				weaponTimer = 5,
				weaponType = [[MissileLauncher]],
				weaponVelocity = 540,
			},
		},
		weapons = {
			[1] = {
				badTargetCategory = [[NOTAIR]],
				def = [[ARMTRUCK_MISSILE1]],
				onlyTargetCategory = [[NOTAIR]],
			},
		},
		workerTime = 0,
	},
}
Def.armsam1.featureDefs.ARMSAM_DEAD.damage = 0.6000 * Def.armsam1.maxDamage
Def.armsam1.featureDefs.ARMSAM_DEAD.description = Def.armsam1.name .. [[ Wreckage]]
Def.armsam1.featureDefs.ARMSAM_DEAD.metal = 0.8000 * Def.armsam1.buildCostMetal
Def.armsam1.featureDefs.ARMSAM_HEAP.damage = 0.3600 * Def.armsam1.maxDamage
Def.armsam1.featureDefs.ARMSAM_HEAP.description = Def.armsam1.name .. [[ Heap]]
Def.armsam1.featureDefs.ARMSAM_HEAP.metal = 0.6400 * Def.armsam1.buildCostMetal
return lowerkeys(Def)
