return {
	armtys = {
		acceleration = 0.43756,
		bankscale = 0.6,
		blocking = false,
		brakerate = 0.1547,
		buildcostenergy = 7209,
		buildcostmetal = 318,
		builder = false,
		buildpic = "armtys.dds",
		buildtime = 10500,
		canattack = true,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MEDIUMVTOL MOBILE NOTDEFENSE NOTSUB NOTSUBNOTSHIP VTOL WEAPON",
		collide = false,
		cruisealt = 80,
		defaultmissiontype = "VTOL_standby",
		description = "Land Attack Helicopter",
		downloadable = 1,
		energymake = 6,
		energyuse = 12,
		explodeas = "BIG_UNITEX",
		firestandorders = 1,
		footprintx = 3,
		footprintz = 3,
		hoverattack = true,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 8.5,
		maneuverleashlength = 200,
		mass = 318,
		maxdamage = 1230,
		maxslope = 100,
		maxvelocity = 5,
		mobilestandorders = 1,
		name = "Tyson",
		noautofire = false,
		nochasecategory = "SUB VTOL",
		objectname = "armTYS",
		radardistance = 0,
		selfdestructas = "BIG_UNIT_VTOL",
		sightdistance = 325,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 360,
		turninplacespeedlimit = 3.3,
		turnrate = 850,
		unitname = "armtys",
		upright = true,
		customparams = {
			buildpic = "armtys.dds",
			faction = "CORE",
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
		weapondefs = {
			gmissiles = {
				areaofeffect = 48,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "Core_Trail_rocket",
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:Explosion_Medium_VLight",
				firestarter = 70,
				flighttime = 2.5,
				metalpershot = 0,
				model = "missile",
				name = "Guided Missiles",
				range = 310,
				reloadtime = 1,
				smoketrail = true,
				soundhitdry = "xplosml2",
				soundhitwet = "splshbig",
				soundhitwetvolume = 0.6,
				soundstart = "Rocklit3",
				startvelocity = 120,
				texture1 = "null",
				texture2 = "null",
				texture3 = "null",
				texture4 = "null",
				tolerance = 8000,
				tracks = true,
				turnrate = 163840,
				weaponacceleration = 60,
				weapontimer = 3,
				weapontype = "MissileLauncher",
				weaponvelocity = 250,
				damage = {
					commanders = 60,
					default = 120,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "GMISSILES",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
