return {
	armthovr = {
		acceleration = 0.043,
		brakerate = 0.186,
		buildangle = 16384,
		buildcostenergy = 8467,
		buildcostmetal = 709,
		builder = false,
		buildpic = "armthovr.dds",
		buildtime = 20341,
		canattack = true,
		canguard = true,
		canhover = true,
		canload = 1,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		cantbetransported = true,
		category = "ALL HOVER MEDIUM MOBILE NOTDEFENSE NOTSUB NOTSUBNOTSHIP NOTVTOL WEAPON SURFACE",
		collisionvolumeoffsets = "-1 -1 0",
		collisionvolumescales = "56 56 96",
		collisionvolumetype = "CylZ",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Transport Hovercraft",
		explodeas = "BIG_UNITEX",
		firestandorders = 1,
		footprintx = 4,
		footprintz = 4,
		icontype = "armthovr",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 51,
		maneuverleashlength = 640,
		mass = 860,
		maxdamage = 5160,
		maxvelocity = 2.07,
		minwaterdepth = 12,
		mobilestandorders = 1,
		movementclass = "HOVER4",
		name = "Bear",
		noautofire = false,
		nochasecategory = "ALL",
		objectname = "ARMTHOVR",
		radaremitheight = 50,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 325,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		transportcapacity = 20,
		transportmaxunits = 8,
		transportsize = 3,
		turninplace = 0,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1.3662,
		turnrate = 395,
		unitname = "armthovr",
		waterline = 14,
		customparams = {
			buildpic = "armthovr.dds",
			faction = "ARM",
		},
		featuredefs = {
			dead = {
				blocking = false,
				collisionvolumeoffsets = "3.81589508057 -2.34375000119e-06 -4.35322570801",
				collisionvolumescales = "64.6317596436 60.2001953125 88.311706543",
				collisionvolumetype = "Box",
				damage = 4095,
				description = "Bear Wreckage",
				energy = 0,
				footprintx = 4,
				footprintz = 4,
				metal = 531,
				object = "ARMTHOVR_DEAD",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "hovlgok1",
			},
			select = {
				[1] = "hovlgsl1",
			},
		},
	},
}
