return {
	cfusionplant = {
		activatewhenbuilt = true,
		buildangle = 90096,
		buildcostenergy = 424704,
		buildcostmetal = 43930,
		builder = false,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 12,
		buildinggrounddecalsizey = 12,
		buildinggrounddecaltype = "cfusionplant_aoplane.dds",
		buildpic = "cfusionplant.dds",
		buildtime = 725000,
		category = "ALL SURFACE",
		collisionvolumeoffsets = "0 -3 0",
		collisionvolumescales = "165 101 165",
		collisionvolumetype = "CylY",
		corpse = "dead",
		description = "Produces Energy",
		energymake = 12800,
		energystorage = 12800,
		energyuse = 0,
		explodeas = "FUSION_BLAST_BIG",
		floater = false,
		footprintx = 9,
		footprintz = 9,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 94,
		mass = 33632,
		maxdamage = 21250,
		maxslope = 10,
		maxwaterdepth = 0,
		name = "Experimental Fusion Reactor",
		noautofire = false,
		objectname = "core/cfusionplant.s3o",
		radardistance = 0,
		radaremitheight = 75,
		seismicsignature = 0,
		selfdestructas = "FUSION_BLAST_BIG",
		sightdistance = 300,
		turnrate = 0,
		unitname = "cfusionplant",
		usebuildinggrounddecal = true,
		yardmap = "ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
		customparams = {
			buildpic = "cfusionplant.dds",
			faction = "CORE",
			normaltex = "unittextures/core_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 15334,
				description = "Mega Fusion Reactor Wreckage",
				featuredead = "heap",
				footprintx = 5,
				footprintz = 5,
				metal = 50400,
				object = "core/cfusionplant_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				damage = 19168,
				description = "Mega Fusion Reactor Debris",
				footprintx = 5,
				footprintz = 5,
				metal = 26880,
				object = "core/cfusionplant_heap.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail5",
				[2] = "piecetrail5",
				[3] = "piecetrail4",
				[4] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "fusion2",
			},
		},
	},
}
