return {
	corach = {
		acceleration = 0.48,
		brakerate = 0.288,
		buildcostenergy = 12410,
		buildcostmetal = 598,
		builddistance = 200,
		builder = true,
		buildpic = "corach.dds",
		buildtime = 25000,
		canguard = true,
		canhover = true,
		canmove = true,
		canpatrol = true,
		canreclamate = 1,
		canstop = 1,
		category = "ALL LARGE MOBILE SURFACE",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Tech Level 2",
		downloadable = 1,
		energymake = 20,
		energystorage = 100,
		explodeas = "BIG_UNITEX",
		footprintx = 4,
		footprintz = 4,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 22,
		maneuverleashlength = 640,
		mass = 598,
		maxdamage = 1380,
		maxslope = 16,
		maxvelocity = 2,
		maxwaterdepth = 0,
		metalmake = 0.2,
		metalstorage = 50,
		mobilestandorders = 1,
		movementclass = "TANKHOVER4",
		name = "Construction Hover",
		noautofire = false,

		objectname = "corach",
		radaremitheight = 25,
		selfdestructas = "BIG_UNIT",
		shownanospray = false,
		sightdistance = 270,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplace = 1,
		turninplaceanglelimit = 60,
		turninplacespeedlimit = 1.056,
		turnrate = 215,
		unitname = "corach",
		workertime = 180,
		buildoptions = {
			[1] = "corfus",
			[2] = "cafus",
			[3] = "cmgeo",
			[4] = "coruwadves",
			[5] = "coruwadvms",
			[6] = "cormoho",
			[7] = "cormmkr",
			[8] = "corhp",
			[9] = "cahp",
			[10] = "corevp",
			[11] = "cornanotc1",
			[12] = "corsd",
			[13] = "corgate",
			[14] = "cortron",
			[15] = "corfmd",
			[16] = "corsilo",
			[17] = "corint",
			[18] = "corbuzz",
			[19] = "coruwfus",
			--[20] = "",
			[21] = "coruwmmm",
			[22] = "corsy",
			[23] = "corplat",
			[24] = "corasy",
			[25] = "csubpen",
			[26] = "cahpns",
			[27] = "coresy",
			[28] = "corfnanotc1",
			[29] = "corfatf",
			[30] = "corason",
			[31] = "corflshd",
		},
		customparams = {
			buildpic = "corach.dds",
			faction = "CORE",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 2335,
				description = "Advanced Construction Hover Wreckage",
				footprintx = 3,
				footprintz = 4,
				metal = 1356,
				object = "corach_dead",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		nanocolor = {
			[1] = 0.324,
			[2] = 0.674,
			[3] = 0.674,
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "hovmdok2",
			},
			select = {
				[1] = "hovmdsl2",
			},
		},
	},
}
