return {
	corca = {
		acceleration = 0.06,
		bankscale = 1.5,
		brakerate = 0.4125,
		buildcostenergy = 4885,
		buildcostmetal = 117,
		builddistance = 40,
		builder = true,
		buildpic = "corca.dds",
		buildtime = 9286,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canreclaim = true,
		canstop = 1,
		category = "ALL CONSTR MOBILE NOTDEFENSE NOTSUB NOTSUBNOTSHIP NOTWEAPON SMALLVTOL VTOL",
		collide = false,
		cruisealt = 75,
		defaultmissiontype = "VTOL_Standby",
		description = "Tech Level 1",
		energystorage = 25,
		explodeas = "CA_EX",
		footprintx = 3,
		footprintz = 3,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		maneuverleashlength = 1280,
		mass = 117,
		maxdamage = 145,
		maxslope = 10,
		maxvelocity = 7.7,
		maxwaterdepth = 0,
		metalmake = 0.05,
		metalstorage = 25,
		mobilestandorders = 1,
		name = "Construction Aircraft",
		noautofire = false,
		nochasecategory = "SUB VTOL",
		objectname = "CORCA",
		radardistance = 50,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT_VTOL",
		sightdistance = 351,
		standingmoveorder = 1,
		steeringmode = 1,
		terraformspeed = 135,
		turninplaceanglelimit = 360,
		turninplacespeedlimit = 5.082,
		turnrate = 94,
		unitname = "corca",
		workertime = 55,
		buildoptions = {
			[1] = "corsolar",
			[2] = "coradvsol",
			[3] = "corwin",
			[4] = "corgeo",
			[5] = "cormstor",
			[6] = "corestor",
			[7] = "corehpad",
			[8] = "cormex",
			[9] = "corexp",
			[10] = "cormakr",
			[11] = "coraap",
			[12] = "corlab",
			[13] = "corvp",
			[14] = "corap",
			[15] = "corhp",
			[16] = "cornanotc",
			[17] = "coreyes",
			[18] = "corrad",
			[19] = "cordrag",
			[20] = "cormaw",
			[21] = "corllt",
			[22] = "hllt",
			[23] = "corhlt",
			[24] = "corpun",
			[25] = "corrl",
			[26] = "madsam",
			[27] = "corerad",
			[28] = "cordl",
			[29] = "corjamt",
			[30] = "cjuno",
			[31] = "cmortor",
			[32] = "corech3",
			[33] = "corsy",
		},
		customparams = {
			buildpic = "CORCA.png",
			faction = "core",
		},
		nanocolor = {
			[1] = 0.044,
			[2] = 0.394,
			[3] = 0.394,
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
	},
}
