return {
	corcsa = {
		acceleration = 0.072,
		amphibious = 1,
		bankscale = 1.5,
		blocking = false,
		brakerate = 0.4275,
		buildcostenergy = 16741,
		buildcostmetal = 596,
		builddistance = 60,
		builder = true,
		buildpic = "corcsa.dds",
		buildtime = 25000,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canreclamate = 1,
		canstop = 1,
		cansubmerge = false,
		category = "ALL CONSTR MEDIUMVTOL MOBILE NOTDEFENSE NOTSUB NOTSUBNOTSHIP NOTWEAPON VTOL",
		collide = false,
		cruisealt = 75,
		defaultmissiontype = "VTOL_Standby",
		description = "Tech Level 2",
		energymake = 20,
		energystorage = 50,
		energyuse = 0,
		explodeas = "CA_EX",
		floater = true,
		footprintx = 2,
		footprintz = 2,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 9,
		maneuverleashlength = 1280,
		mass = 596,
		maxdamage = 990,
		maxslope = 10,
		maxvelocity = 8,
		maxwaterdepth = 255,
		metalmake = 0.2,
		metalstorage = 50,
		mobilestandorders = 1,
		name = "Construction Seaplane",
		noautofire = false,
		nochasecategory = "SUB VTOL",
		objectname = "CORCSA",
		radardistance = 50,
		radaremitheight = 9,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT_VTOL",
		shownanospray = false,
		sightdistance = 351,
		standingmoveorder = 1,
		steeringmode = 1,
		terraformspeed = 180,
		turninplaceanglelimit = 360,
		turninplacespeedlimit = 5.28,
		turnrate = 132,
		unitname = "corcsa",
		workertime = 100,
		buildoptions = {
			[1] = "corfus",
			[2] = "cmgeo",
			[3] = "coruwadves",
			[4] = "coruwadvms",
			[5] = "cormoho",
			[6] = "cormmkr",
			[7] = "cahp",
			[8] = "corsd",
			[9] = "corasp",
			[10] = "corgate",
			[11] = "cortron",
			[12] = "corfmd",
			[13] = "corsilo",
			[14] = "corint",
			[15] = "corbuzz",
			[16] = "coruwfus",
			[17] = "coruwmme",
			[18] = "coruwmmm",
			[19] = "corplat",
			[20] = "corasy",
			[21] = "csubpen",
			[22] = "cahpns",
			[23] = "corfatf",
			[24] = "corflshd",
		},
		customparams = {
			buildpic = "corcsa.dds",
			faction = "CORE",
		},
		nanocolor = {
			[1] = 0.128,
			[2] = 0.478,
			[3] = 0.478,
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "seapsel2",
			},
		},
	},
}
