return {
	cordust = {
		acceleration = 0.01,
		activatewhenbuilt = true,
		airhoverfactor = 0,
		airstrafe = false,
		bankingallowed = false,
		blocking = false,
		brakerate = 0.04,
		buildcostenergy = 1520054,
		buildcostmetal = 207141,
		builder = false,
		buildpic = "cordust.dds",
		buildtime = 2400000,
		canattack = true,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MOBILE MAJOR SURFACE VTOL",
		collide = false,
		collisionvolumeoffsets = "0 -21 -40",
		collisionvolumescales = "150 150 300",
		collisionvolumetype = "Ell",
		corpse = "dead",
		cruisealt = 50,
		defaultmissiontype = "VTOL_standby",
		description = "AeroShip",
		dontland = 0,
		energystorage = 10000,
		explodeas = "MKL_BLAST",
		firestandorders = 1,
		footprintx = 16,
		footprintz = 16,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 34.5,
		maneuverleashlength = 500,
		mass = 207141,
		maxdamage = 595000,
		maxslope = 10,
		maxvelocity = 1.1,
		maxwaterdepth = 0,
		metalstorage = 1000,
		mobilestandorders = 1,
		name = "Dust",
		noautofire = false,
		objectname = "core/cordust.s3o",
		radardistance = 0,
		radaremitheight = 25,
		seismicsignature = 0,
		selfdestructas = "MEGA_BLAST",
		selfdestructcountdown = 10,
		sightdistance = 1000,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 360,
		turninplacespeedlimit = 0.66,
		turnrate = 70,
		unitname = "cordust",
		upright = true,
		customparams = {
			buildpic = "cordust.dds",
			faction = "CORE",
			normaltex = "unittextures/core_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 220660,
				description = "Dust Wreckage",
				footprintx = 14,
				footprintz = 8,
				metal = 227250,
				object = "core/cordust_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			arrived = {
				"bigstop",
			},
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"biggo",
			},
			select = {
				"bigsel",
			},
		},
		weapondefs = {
			corflak_gun = {
				accuracy = 1000,
				areaofeffect = 192,
				avoidfeature = false,
				burnblow = true,
				canattackground = false,
				cegtag = "corflak-fx",
				craterareaofeffect = 288,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:FLASH3",
				gravityaffected = true,
				impulseboost = 0,
				impulsefactor = 0,
				name = "FlakCannon",
				noselfdamage = true,
				range = 1000,
				reloadtime = 0.65,
				rgbcolor = "1.0 0.5 0.0",
				size = 5,
				soundhitdry = "flakhit",
				soundhitwet = "splslrg",
				soundhitwetvolume = 0.6,
				soundstart = "flakfire",
				turret = true,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 1550,
				damage = {
					areoship = 162.5,
					default = 5,
					air = 650,
				},
				tracks = false,
			},
			devastatorrockets = {
				areaofeffect = 350,
				avoidfeature = false,
				burnblow = true,
				collidefriendly = false,
				craterareaofeffect = 525,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				energypershot = 0,
				explosiongenerator = "custom:MININUKES",
				firestarter = 0,
				flighttime = 7,
				impulseboost = 0,
				model = "weapon_rocket_devastator.s3o",
				name = "Heavy Rockets",
				noselfdamage = true,
				range = 1800,
				reloadtime = 2,
				smoketrail = true,
				soundhitdry = "DevastatorRocket_hit",
				soundhitwet = "splslrg",
				soundhitwetvolume = 0.6,
				soundstart = "DevastatorRocket",
				soundtrigger = true,
				startvelocity = 350,
				targetable = 16,
				tolerance = 3000,
				tracks = false,
				turnrate = 30000,
				turret = true,
				weaponacceleration = 280,
				weapontimer = 2,
				weapontype = "StarburstLauncher",
				weaponvelocity = 550,
				damage = {
					commanders = 1500,
					default = 3000,
					subs = 5,
				},
			},
			antimatteraccelerator = {
				areaofeffect = 80,
				beamtime = 1,
				burnblow = true,
				collidefriendly = false,
				corethickness = 0.4,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				energypershot = 7500,
				explosiongenerator = "custom:RAVAGER",
				firestarter = 20,
				impulseboost = 0,
				impulsefactor = 0,
				largebeamlaser = true,
				laserflaresize = 10,
				name = "Mounted antimatter accelerator",
				noexplode = true,
				noselfdamage = true,
				range = 1400,
				reloadtime = 3,
				rgbcolor = "1 0 0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "arrfire",
				soundtrigger = 1,
				sweepfire = false,
				targetmoveerror = 0.4,
				texture1 = "Type4Beam",
				texture2 = "NULL",
				texture3 = "NULL",
				texture4 = "EMG",
				thickness = 13,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 1500,
				customparams = {
					light_mult = 1.8,
					light_radius_mult = 1.2,
				},
				damage = {
					commanders = 3000,
					default = 12000,
					subs = 5,
				},
				tracks = false,
			},
			tehlazerofdewm = {
				areaofeffect = 14,
				beamtime = 1.05,
				corethickness = 0.5,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				energypershot = 1000,
				explosiongenerator = "custom:BURN_WHITE",
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				laserflaresize = 12,
				name = "DEEWWMM",
				noselfdamage = true,
				range = 950,
				reloadtime = 5,
				rgbcolor = "0.2 0.2 1",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "annigun1",
				soundtrigger = 1,
				sweepfire = false,
				targetmoveerror = 0.2,
				thickness = 4,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 1500,
				customparams = {
					light_mult = 1.8,
					light_radius_mult = 1.2,
				},
				damage = {
					commanders = 1250,
					default = 2500,
					subs = 5,
				},
				tracks = false,
			},
		},
		weapons = {
			{
				badtargetcategory = "HUGE LARGE MEDIUM SMALL MINOR",
				def = "AntimatterAccelerator",
				maindir = "1 0 0",
				maxangledif = 270,
				onlytargetcategory = "SURFACE",
			},
			{
				badtargetcategory = "HUGE LARGE MEDIUM SMALL MINOR",
				def = "AntimatterAccelerator",
				maindir = "-1 0 0",
				maxangledif = 270,
				onlytargetcategory = "SURFACE",
			},
			{
				badtargetcategory = "MEDIUM SMALL MINOR",
				def = "tehlazerofdewm",
				maindir = "-1 0 0",
				maxangledif = 180,
				onlytargetcategory = "SURFACE",
			},
			{
				badtargetcategory = "MEDIUM SMALL MINOR",
				def = "tehlazerofdewm",
				maindir = "1 0 0",
				maxangledif = 180,
				onlytargetcategory = "SURFACE",
			},
			{
				badtargetcategory = "MEDIUM SMALL MINOR",
				def = "tehlazerofdewm",
				maindir = "-1 0 0",
				maxangledif = 300,
				onlytargetcategory = "SURFACE",
			},
			{
				badtargetcategory = "MEDIUM SMALL MINOR",
				def = "tehlazerofdewm",
				maindir = "1 0 0",
				maxangledif = 300,
				onlytargetcategory = "SURFACE",
			},
			{
				badtargetcategory = "MINOR MAJOR",
				def = "CORFLAK_GUN",
				maindir = "1 0 0",
				maxangledif = 200,
				onlytargetcategory = "VTOL",
			},
			{
				badtargetcategory = "MINOR MAJOR",
				def = "CORFLAK_GUN",
				maindir = "-1 0 0",
				maxangledif = 200,
				onlytargetcategory = "VTOL",
			},
			{
				def = "DevastatorRockets",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}