local Def = {
	core_immolator = {
		bmcode = 0,
		buildAngle = 8192,
		buildCostEnergy = 115165,
		buildCostMetal = 1650,
		buildPic = [[core_immolator.png]],
		buildTime = 43900,
		builder = false,
		canAttack = true,
		canGuard = true,
		canstop = 1,
		category = [[CORE WEAPON NOTAIR NOTSUB]],
		corpse = [[dead]],
		customparams = {
			canareaattack = 1,
		},
		defaultmissiontype = [[GUARD_NOMOVE]],
		description = [[- Plasma Tower]],
		designation = [[COR-PLAS]],
		downloadable = 1,
		energyStorage = 1200,
		energyUse = 0,
		explodeAs = [[ATOMIC_BLAST]],
		featureDefs = {
			dead = {
				blocking = true,
				category = [[core_corpses]],
				damage = nil,
				description = nil,
				featureDead = [[heap]],
				featurereclamate = [[smudge01]],
				footprintX = 3,
				footprintZ = 3,
				height = 20,
				hitdensity = 100,
				metal = nil,
				object = [[core_immolator_dead]],
				reclaimable = true,
				seqnamereclamate = [[tree1reclamate]],
				world = [[All Worlds]],
			},
			heap = {
				blocking = false,
				category = [[heaps]],
				damage = nil,
				description = nil,
				featurereclamate = [[smudge01]],
				footprintX = 3,
				footprintZ = 3,
				height = 4,
				hitdensity = 100,
				metal = nil,
				object = [[3x3d]],
				reclaimable = true,
				seqnamereclamate = [[tree1reclamate]],
				world = [[All Worlds]],
			},
		},
		firestandorders = 1,
		footprintX = 4,
		footprintZ = 4,
		healtime = 11,
		iconType = [[building]],
		maxDamage = 2800,
		maxSlope = 10,
		maxWaterDepth = 0,
		metalStorage = 0,
		name = [[Immolator]],
		noAutoFire = false,
		objectName = [[core_immolator]],
		radarDistance = 0,
		selfDestructAs = [[ATOMIC_BLAST]],
		sfxtypes = {
			explosiongenerators = {
				[1] = [[custom:berthaflare]],
			},
		},
		shootme = 1,
		side = [[Core]],
		sightDistance = 665,
		sounds = {
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[cantdo4]],
			},
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			ok = {
				[1] = [[kbcormov]],
			},
			select = {
				[1] = [[kbcorsel]],
			},
			underattack = [[warning1]],
		},
		standingfireorder = 2,
		threed = 1,
		unitname = [[core_immolator]],
		unitnumber = 124,
		version = 3,
		weaponDefs = {
			CORE_INTIMIDATOR3 = {
				accuracy = 535,
				aimrate = 2200,
				areaOfEffect = 250,
				ballistic = true,
				craterBoost = 0.15,
				craterMult = 0.15,
				damage = {
					blackhydra = 3000,
					default = 650,
					flakboats = 3000,
					jammerboats = 3000,
					l1subs = 5,
					l2subs = 5,
					l3subs = 5,
					otherboats = 3000,
					seadragon = 3000,
				},
				energypershot = 4000,
				explosionGenerator = [[custom:FLASHBIGBUILDING]],
				gravityaffected = [[true]],
				holdtime = 1,
				impulseBoost = 0,
				impulseFactor = 0,
				metalpershot = 1,
				name = [[IntimidatorCannon]],
				noSelfDamage = true,
				range = 5100,
				reloadtime = 9,
				renderType = 4,
				soundHit = [[xplonuk1]],
				soundStart = [[xplonuk3]],
				startsmoke = 1,
				turret = true,
				weaponType = [[Cannon]],
				weaponVelocity = 850,
			},
		},
		weapons = {
			[1] = {
				badTargetCategory = [[VTOL]],
				def = [[CORE_INTIMIDATOR3]],
				onlyTargetCategory = [[NOTAIR]],
			},
		},
		workerTime = 0,
		yardMap = [[oooo oooo oooo oooo]],
		zbuffer = 1,
	},
}
Def.core_immolator.featureDefs.dead.damage = 0.6000 * Def.core_immolator.maxDamage
Def.core_immolator.featureDefs.dead.description = Def.core_immolator.name .. [[ Wreckage]]
Def.core_immolator.featureDefs.dead.metal = 0.8000 * Def.core_immolator.buildCostMetal
Def.core_immolator.featureDefs.heap.damage = 0.3600 * Def.core_immolator.maxDamage
Def.core_immolator.featureDefs.heap.description = Def.core_immolator.name .. [[ Heap]]
Def.core_immolator.featureDefs.heap.metal = 0.6400 * Def.core_immolator.buildCostMetal
return lowerkeys(Def)
