return {
	core_uncle = {
		acceleration = 0.12,
		autoheal = 100,
		brakerate = 3.0,
		buildcostenergy = 70500,
		buildcostmetal = 8850,
		builder = false,
		buildpic = "core_uncle.dds",
		buildtime = 80000,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL LARGE MOBILE SURFACE UNDERWATER",
		collisionvolumeoffsets = "0 -3 -20",
		collisionvolumescales = "85 30 270",
		collisionvolumetype = "CylZ",
		corpse = "core_uncle_dead",
		defaultmissiontype = "Standby",
		description = "Experimental Transport Hexapod",
		explodeas = "CRAWL_BLAST",
		firestandorders = 1,
		footprintx = 5,
		footprintz = 5,
		idleautoheal = 5,
		idletime = 30,
		losemitheight = 78,
		maneuverleashlength = 1250,
		mass = 8850,
		maxdamage = 20150,
		maxslope = 36,
		maxvelocity = 1.35,
		maxwaterdepth = 100,
		mobilestandorders = 1,
		movementclass = "HTKBOT5",
		name = "Pyro's Uncle",
		noautofire = false,
		objectname = "core/core_uncle.s3o",
		radaremitheight = 100,
		script = "core_uncle.cob",
		seismicsignature = 2,
		selfdestructas = "SPYBOMBX",
		selfdestructcountdown = 5,
		sightdistance = 500,
		standingfireorder = 2,
		standingmoveorder = 1,
		stealth = true,
		steeringmode = 2,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0.8,
		turnrate = 200,
		unitname = "core_uncle",
		upright = true,
		customparams = {
			isairbase = true,
			buildpic = "core_uncle.dds",
			faction = "Core",
			normaltex = "unittextures/core_normals.dds",
		},
		featuredefs = {
			core_uncle_dead = {
				blocking = false,
				damage = 33488,
				description = "Uncle Wreckage",
				energy = 0,
				featuredead = "core_uncle_heap",
				footprintx = 6,
				footprintz = 6,
				metal = 7400,
				object = "core/core_uncle_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			core_uncle_heap = {
				blocking = false,
				damage = 29860,
				description = "Uncle Debris",
				energy = 0,
				footprintx = 6,
				footprintz = 6,
				metal = 3680,
				object = "6x6a.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"kbcormov",
			},
			select = {
				"kbcorsel",
			},
		},
	},
}
