return {
	corfmkr = {
		acceleration = 0,
		activatewhenbuilt = true,
		brakerate = 0,
		buildangle = 8192,
		buildcostenergy = 1421,
		buildcostmetal = 35,
		builder = false,
		buildpic = "corfmkr.dds",
		buildtime = 2200,
		category = "ALL UNDERWATER SURFACE",
		description = "Converts upto 128 Energy to Metal",
		explodeas = "ARMESTOR_BUILDING",
		footprintx = 3,
		footprintz = 3,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 28,
		mass = 21,
		maxdamage = 145,
		maxslope = 10,
		maxvelocity = 0,
		minwaterdepth = 11,
		name = "Floating Metal Maker",
		noautofire = false,
		objectname = "core/corfmkr.s3o",
		radaremitheight = 28,
		seismicsignature = 0,
		selfdestructas = "ARMESTOR_BUILDING",
		sightdistance = 273,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0,
		turnrate = 0,
		unitname = "corfmkr",
		waterline = 21,
		yardmap = "wwwwwwwww",
		customparams = {
			buildpic = "corfmkr.dds",
			faction = "CORE",
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			activate = "metlon2",
			canceldestruct = "cancel2",
			deactivate = "metloff2",
			underattack = "warning1",
			working = "metlrun2",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "metlon2",
			},
		},
	},
}
