return {
	corfmine3 = {
		acceleration = 0,
		blocking = false,
		brakerate = 0,
		buildcostenergy = 1860,
		buildcostmetal = 75,
		builder = false,
		buildpic = "corfmine3.dds",
		buildtime = 150,
		canattack = false,
		canguard = false,
		canmove = false,
		canpatrol = false,
		canstop = 0,
		category = "ALL MINE SURFACE UNDERWATER",
		cloakcost = 3,
		collide = false,
		collisionvolumeoffsets = "0 -1.5 0",
		collisionvolumescales = "22 5 22",
		collisionvolumetype = "CylY",
		decloakspherical = false,
		defaultmissiontype = "Standby_Mine",
		description = "Heavy Mine",
		energyuse = 0,
		explodeas = "MINE_HEAVY",
		firestandorders = 0,
		firestate = 2,
		footprintx = 1,
		footprintz = 1,
		icontype = "building",
		idleautoheal = 5,
		idletime = 300,
		losemitheight = 22,
		mass = 90,
		maxdamage = 10,
		maxslope = 40,
		maxvelocity = 0,
		mincloakdistance = 0,
		minwaterdepth = 0,
		name = "1100 NS",
		noautofire = false,
		objectname = "core/corfmine3.s3o",
		script = "mines_lus.lua",
		radaremitheight = 25,
		seismicsignature = 0,
		selfdestructas = "MINE_HEAVY",
		selfdestructcountdown = 0,
		sightdistance = 71.5,
		sonarstealth = true,
		standingfireorder = 2,
		stealth = true,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0,
		turnrate = 0,
		unitname = "corfmine3",
		waterline = 0,
		customparams = {
			buildpic = "corfmine3.dds",
			detonaterange = "64",
			faction = "CORE",
			initcloaked = true,
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"servsml6",
			},
			select = {
				"minesel2",
			},
		},
		weapondefs = {
			mine_detonator = {
				areaofeffect = 5,
				avoidfeature = false,
				cegtag = "Trail_cannon",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0,
				explosiongenerator = "",
				firesubmersed = true,
				gravityaffected = "TRUE",
				impulseboost = 0,
				impulsefactor = 0,
				name = "Mine Detonator",
				nogap = 1,
				range = 1,
				reloadtime = 0.1,
				separation = 0.45,
				sizedecay = -0.15,
				soundhitwet = "splshbig",
				soundhitwetvolume = 0.6,
				stages = 20,
				weapontype = "Cannon",
				weaponvelocity = 1000,
				damage = {
					default = 0,
					mines = 100,
				},
				tracks = false,
			},
			mine_dummy = {
				areaofeffect = 0,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0,
				explosiongenerator = "",
				firesubmersed = true,
				impulseboost = 0,
				impulsefactor = 0,
				name = "Crawlingbomb Dummy Weapon",
				range = 64,
				reloadtime = 0.1,
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				tolerance = 100000,
				weapontype = "Melee",
				weaponvelocity = 100000,
				damage = {
					default = 0,
				},
				tracks = false,
			},
		},
		weapons = {
			{
				def = "MINE_DUMMY",
				onlytargetcategory = "SURFACE",
			},
			{
				def = "MINE_DETONATOR",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}