local Def = {
	corfhp = {
		acceleration = 0,
		bmcode = 0,
		brakeRate = 0,
		buildCostEnergy = 5082,
		buildCostMetal = 1100,
		buildPic = [[CORFHP.png]],
		buildTime = 17817,
		builder = true,
		buildoptions = {
			[1] = [[corch]],
			[2] = [[corsh]],
			[3] = [[corsnap]],
			[4] = [[corah]],
			[5] = [[cormh]],
			[6] = [[corthovr]],
			[7] = [[nsaclash]],
		},
		canMove = true,
		canPatrol = true,
		canstop = 1,
		category = [[ALL PLANT NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR]],
		corpse = [[DEAD]],
		description = [[Builds Hovercraft]],
		energyStorage = 200,
		energyUse = 0,
		explodeAs = [[LARGE_BUILDINGEX]],
		featureDefs = {
			DEAD = {
				blocking = false,
				category = [[corpses]],
				damage = nil,
				description = nil,
				energy = 0,
				footprintX = 8,
				footprintZ = 7,
				height = 20,
				hitdensity = 100,
				metal = nil,
				object = [[CORFHP_DEAD]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
		},
		firestandorders = 1,
		footprintX = 8,
		footprintZ = 7,
		iconType = [[building]],
		idleAutoHeal = 5,
		idleTime = 1800,
		maxDamage = 3356,
		maxVelocity = 0,
		metalStorage = 200,
		minWaterDepth = 30,
		mobilestandorders = 1,
		name = [[Floating Hovercraft Platform]],
		noAutoFire = false,
		objectName = [[CORFHP]],
		radarDistance = 50,
		seismicSignature = 0,
		selfDestructAs = [[LARGE_BUILDING]],
		side = [[CORE]],
		sightDistance = 312,
		smoothAnim = true,
		sounds = {
			build = [[hoverok2]],
			canceldestruct = [[cancel2]],
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			select = {
				[1] = [[hoversl2]],
			},
			underattack = [[warning1]],
			unitcomplete = [[untdone]],
		},
		standingfireorder = 2,
		standingmoveorder = 1,
		turnRate = 0,
		unitname = [[corfhp]],
		waterline = 5,
		workerTime = 200,
		yardMap = [[wCCCCCCwwCCCCCCwwCCCCCCwwCCCCCCwwCCCCCCwwCCCCCCwwCCCCCCw]],
	},
}
Def.corfhp.featureDefs.DEAD.damage = 0.6000 * Def.corfhp.maxDamage
Def.corfhp.featureDefs.DEAD.description = Def.corfhp.name .. [[ Wreckage]]
Def.corfhp.featureDefs.DEAD.metal = 0.8000 * Def.corfhp.buildCostMetal
return lowerkeys(Def)
