-- UNITDEF -- CORGALA --
--------------------------------------------------------------------------------

local unitName = "corgala"

--------------------------------------------------------------------------------

local unitDef = {
  acceleration       = 0.08,
  ai_limit           = [[limit CORGALA 2]],
  ai_weight          = [[weight CORGALA 0.88]],
  badTargetCategory  = [[VTOL]],
  bmcode             = 1,
  brakeRate          = 0.21,
  buildCostEnergy    = 418588,
  buildCostMetal     = 20692,
  builder            = false,
  buildPic           = [[corgala.DDS]],
  buildTime          = 270000,
  canAttack          = true,
  canGuard           = true,
  canMove            = true,
  canPatrol          = true,
  canstop            = 1,
  cantBeTransported  = true,
  category           = [[CORE LEVEL3 WEAPON NOTAIR NOTSUB]],
  copyright          = [[Copyright 1997 Humongous Entertainment. All rights reserved.]],
  damageModifier     = 1,
  defaultmissiontype = [[Standby]],
  description        = [[Very heavy demolition mech]],
  energyMake         = 0.8,
  energyStorage      = 72,
  energyUse          = 17,
  explodeAs          = [[NUCLEAR_MISSILE]],
  firestandorders    = 1,
  footprintX         = 9,
  footprintZ         = 9,
  immunetoparalyzer  = 1,
  maneuverleashlength = 640,
  mass               = 200000,
  maxDamage          = 163554,
  maxSlope           = 15,
  maxVelocity        = 1.88,
  maxWaterDepth      = 16,
  metalStorage       = 50,
  mobilestandorders  = 1,
  movementClass      = [[VKBOT9]],
  name               = [[Galacticus]],
  noAutoFire         = false,
  objectName         = [[CORGALA]],
  onlytargetcategory3 = [[notair]],
  selfDestructAs     = [[NUCLEAR_MISSILE]],
  shootme            = 1,
  side               = [[CORE]],
  sightDistance      = 900,
  standingfireorder  = 2,
  standingmoveorder  = 0,
  steeringmode       = 2,
  TEDClass           = [[KBOT]],
  threed             = 1,
  turnRate           = 320,
  unitname           = [[corgala]],
  unitnumber         = 100015,
  upright            = true,
  version            = 3.1,
  zbuffer            = 1,
  weapons = {
    [1]  = {
      badTargetCategory  = [[VTOL]],
      def                = [[TAWF_BANISHER2]],
    },
    [2]  = {
      def                = [[RavagerBeam]],
    },
  },
}


--------------------------------------------------------------------------------

local weaponDefs = {
  RavagerBeam = {
    areaOfEffect       = 60,
    beamlaser          = 1,
    beamTime           = 1.5,
    burnblow           = true,
    coreThickness      = 0.4,
    craterBoost        = 0,
    craterMult         = 0,
    endsmoke           = 0,
    energypershot      = 6665.6666667,
    explosionGenerator = [[custom:RAVAGER]],
    fireStarter        = 20,
    id                 = 168,
    impulseBoost       = 0,
    largeBeamLaser     = true,
    laserFlareSize     = 10,
    lineOfSight        = true,
    name               = [[Ravager Beam]],
    noExplode          = true,
    range              = 1500,
    reloadtime         = 15,
    renderType         = 0,
    rgbColor           = [[1 0 1]],
    soundHit           = [[lasbladehit]],
    soundStart         = [[accel]],
    soundTrigger       = true,
    startsmoke         = 0,
    targetmoveerrorr   = 0.4,
    texture1           = [[Type4Beam]],
    texture2           = [[NULL]],
    texture3           = [[NULL]],
    texture4           = [[EMG]],
    thickness          = 25,
    tolerance          = 1500,
    turret             = true,
    weaponType         = [[BeamLaser]],
    weaponVelocity     = 1500,
    damage = {
      commanders         = 2500,
      default            = 20000,
    },
  },
  TAWF_BANISHER2 = {
    areaOfEffect       = 200,
    craterBoost        = 0,
    craterMult         = 0,
    edgeEffectiveness  = 0.4,
    explosionGenerator = [[custom:VEHHVYROCKET_EXPLOSION]],
    fireStarter        = 20,
    guidance           = true,
    impulseBoost       = 0.123,
    impulseFactor      = 0.123,
    lineOfSight        = true,
    model              = [[TAWF114a]],
    name               = [[Banisher]],
    noSelfDamage       = true,
    range              = 1000,
    reloadtime         = 6,
    renderType         = 1,
    selfprop           = true,
    smokedelay         = 0.01,
    smokeTrail         = true,
    soundHit           = [[TAWF114b]],
    soundStart         = [[TAWF114a]],
    startsmoke         = 1,
    startVelocity      = 400,
    tolerance          = 9000,
    tracks             = true,
    trajectoryHeight   = 0.45,
    turnRate           = 22000,
    turret             = true,
    weaponAcceleration = 70,
    weaponTimer        = 5,
    weaponType         = [[MissileLauncher]],
    weaponVelocity     = 400,
    damage = {
      commanders         = 1000,
      default            = 4000,
      l1subs             = 5,
      l2subs             = 5,
      l3subs             = 5,
    },
  },
}
unitDef.weaponDefs = weaponDefs


--------------------------------------------------------------------------------

return lowerkeys({ [unitName] = unitDef })

--------------------------------------------------------------------------------
