return {
	corhunt = {
		acceleration = 0.03808,
		altfromsealevel = 1,
		amphibious = 1,
		bankscale = 1,
		blocking = false,
		brakerate = 0.038,
		buildcostenergy = 6849,
		buildcostmetal = 130,
		builder = false,
		buildpic = "corhunt.dds",
		buildtime = 9512,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		cansubmerge = false,
		category = "ALL MEDIUMVTOL MOBILE NOTDEFENSE NOTSUB NOTSUBNOTSHIP NOTWEAPON VTOL",
		collide = false,
		cruisealt = 190,
		defaultmissiontype = "VTOL_standby",
		description = "Advanced Radar/Sonar Plane",
		explodeas = "BIG_UNITEX",
		firestandorders = 1,
		floater = true,
		footprintx = 3,
		footprintz = 3,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 16,
		maneuverleashlength = 1280,
		mass = 130,
		maxdamage = 660,
		maxslope = 10,
		maxvelocity = 10.81,
		maxwaterdepth = 255,
		mobilestandorders = 1,
		moverate1 = 8,
		name = "Hunter",
		noautofire = false,
		nochasecategory = "SUB VTOL",
		objectname = "CORHUNT",
		radardistance = 2200,
		radaremitheight = 16,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT_VTOL",
		sightdistance = 1130,
		sonardistance = 900,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 7.1346,
		turnrate = 450,
		unitname = "corhunt",
		customparams = {
			buildpic = "corhunt.dds",
			faction = "CORE",
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "seasonr2",
			},
		},
	},
}
