return {
	corhurc = {
		acceleration = 0.02155,
		altfromsealevel = 1,
		attackrunlength = 300,
		blocking = false,
		brakerate = 0.035,
		buildcostenergy = 15325,
		buildcostmetal = 335,
		builder = false,
		buildpic = "corhurc.dds",
		buildtime = 20000,
		canattack = true,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MOBILE VTOL",
		collide = false,
		corpse = "heap",
		cruisealt = 220,
		defaultmissiontype = "VTOL_standby",
		description = "Strategic Bomber",
		explodeas = "BIG_UNITEX",
		firestandorders = 1,
		footprintx = 4,
		footprintz = 4,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 15,
		maneuverleashlength = 1380,
		mass = 335,
		maxdamage = 1275,
		maxslope = 10,
		maxvelocity = 7.9,
		maxwaterdepth = 0,
		mobilestandorders = 1,
		name = "Hurricane",
		noautofire = true,
		objectname = "core/corhurc.s3o",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT_VTOL",
		sightdistance = 221,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 5.94,
		turnrate = 220,
		unitname = "corhurc",
		customparams = {
			buildpic = "corhurc.dds",
			faction = "CORE",
			normaltex = "unittextures/core_normals.dds",
		},
		featuredefs = {
			heap = {
				blocking = false,
				damage = 9641,
				description = "Aircraft Debris",
				footprintx = 4,
				footprintz = 4,
				metal = 142,
				object = "4x4z.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"vtolcrmv",
			},
			select = {
				"vtolcrac",
			},
		},
		weapondefs = {
			coradvbomb = {
				areaofeffect = 196,
				avoidfeature = false,
				burst = 8,
				burstrate = 0.2,
				collidefriendly = false,
				commandfire = false,
				craterareaofeffect = 196,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.7,
				explosiongenerator = "custom:CORE_BIGBOMB_EXPLOSION",
				gravityaffected = "true",
				impulseboost = 0.123,
				impulsefactor = 0.123,
				interceptedbyshieldtype = 16,
				model = "weapon_bomb.s3o",
				name = "AdvancedBombs",
				noselfdamage = true,
				range = 1280,
				reloadtime = 10,
				soundhitdry = "xplomed2",
				soundhitwet = "splslrg",
				soundhitwetvolume = 0.6,
				soundstart = "bombrel",
				weapontype = "AircraftBomb",
				damage = {
					commanders = 140,
					default = 280,
					subs = 5,
				},
				tracks = false,
			},
		},
		weapons = {
			{
				def = "CORADVBOMB",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
