local Def = {
	corint1 = {
		acceleration = 0,
		antiweapons = 1,
		badTargetCategory = [[MOBILE]],
		bmcode = 0,
		brakeRate = 0,
		buildAngle = 32700,
		buildCostEnergy = 152520,
		buildCostMetal = 19328,
		buildPic = [[CORINT.png]],
		buildTime = 193237,
		builder = false,
		canAttack = true,
		canstop = 1,
		category = [[ALL NOTMOBILE NOTVTOL NOTSUB NOTDEFENSE NOTSUBNOTSHIP NOTHOVERNOTVTOL]],
		corpse = [[DEAD]],
		customparams = {
			canareaattack = 1,
		},
		defaultmissiontype = [[GUARD_NOMOVE]],
		description = [[Heavy Long Range Plasma Cannon]],
		energyStorage = 0,
		energyUse = 0,
		explodeAs = [[ATOMIC_BLAST]],
		featureDefs = {
			DEAD = {
				blocking = true,
				category = [[corpses]],
				damage = nil,
				description = nil,
				energy = 0,
				featureDead = [[HEAP]],
				featurereclamate = [[SMUDGE01]],
				footprintX = 10,
				footprintZ = 10,
				height = 20,
				hitdensity = 100,
				metal = nil,
				object = [[corint1_dead]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
			HEAP = {
				blocking = false,
				category = [[heaps]],
				damage = nil,
				description = nil,
				energy = 0,
				featurereclamate = [[SMUDGE01]],
				footprintX = 7,
				footprintZ = 7,
				hitdensity = 100,
				metal = nil,
				object = [[7X7A]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
		},
		firestandorders = 2,
		footprintX = 10,
		footprintZ = 10,
		iconType = [[building]],
		idleAutoHeal = 5,
		idleTime = 1800,
		maxDamage = 16600,
		maxSlope = 13,
		maxVelocity = 0,
		maxWaterDepth = 0,
		metalStorage = 0,
		name = [[Intimidator TECH 3]],
		noChaseCategory = [[ALL]],
		objectName = [[CORINT1]],
		seismicSignature = 0,
		selfDestructAs = [[ATOMIC_BLAST]],
		sfxtypes = {
			explosiongenerators = {
				[1] = [[custom:berthaflare]],
			},
		},
		side = [[CORE]],
		sightDistance = 273,
		smoothAnim = true,
		sounds = {
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[cantdo4]],
			},
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			ok = {
				[1] = [[servlrg4]],
			},
			select = {
				[1] = [[servlrg4]],
			},
			underattack = [[warning1]],
		},
		standingfireorder = 2,
		turnRate = 0,
		unitname = [[corint1]],
		weaponDefs = {
			CORE_INTIMIDATOR1 = {
				accuracy = 535,
				aimrate = 3200,
				areaOfEffect = 324,
				ballistic = true,
				collideFriendly = false,
				craterBoost = 0.15,
				craterMult = 0.15,
				damage = {
					blackhydra = 3000,
					commanders = 1000,
					default = 5400,
					flakboats = 3000,
					jammerboats = 3000,
					l1subs = 5,
					l2subs = 5,
					l3subs = 5,
					otherboats = 3000,
					seadragon = 3000,
				},
				energypershot = 19000,
				explosionGenerator = [[custom:FLASHBIGBUILDING]],
				gravityaffected = [[true]],
				holdtime = 1,
				impulseBoost = 0.5,
				impulseFactor = 0.5,
				metalpershot = 300,
				name = [[IntimidatorCannon]],
				noSelfDamage = true,
				range = 8600,
				reloadtime = 6.5,
				renderType = 4,
				soundHit = [[xplonuk1]],
				soundStart = [[xplonuk3]],
				startsmoke = 1,
				turret = true,
				weaponType = [[Cannon]],
				weaponVelocity = 1150,
			},
		},
		weapons = {
			[1] = {
				badTargetCategory = [[MOBILE]],
				def = [[CORE_INTIMIDATOR1]],
				onlyTargetCategory = [[NOTAIR]],
			},
		},
		workerTime = 0,
		yardMap = [[oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo]],
	},
}
Def.corint1.featureDefs.DEAD.damage = 0.6000 * Def.corint1.maxDamage
Def.corint1.featureDefs.DEAD.description = Def.corint1.name .. [[ Wreckage]]
Def.corint1.featureDefs.DEAD.metal = 0.8000 * Def.corint1.buildCostMetal
Def.corint1.featureDefs.HEAP.damage = 0.3600 * Def.corint1.maxDamage
Def.corint1.featureDefs.HEAP.description = Def.corint1.name .. [[ Heap]]
Def.corint1.featureDefs.HEAP.metal = 0.6400 * Def.corint1.buildCostMetal
return lowerkeys(Def)
