return {
	cormaw = {
		acceleration = 0,
		buildangle = 8192,
		buildcostenergy = 1506,
		buildcostmetal = 281,
		builder = false,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 4,
		buildinggrounddecalsizey = 4,
		buildinggrounddecaltype = "cormaw_aoplane.dds",
		buildpic = "cormaw.dds",
		buildtime = 5000,
		canattack = true,
		canstop = 1,
		category = "ALL ANTIFLAME SURFACE",
		collisionvolumeoffsets = "0 -6 0",
		collisionvolumescales = "31 39 31",
		collisionvolumetype = "CylY",
		corpse = "dead",
		damagemodifier = 0.20,
		defaultmissiontype = "GUARD_NOMOVE",
		description = "Pop-Up Flamethrower Turret",
		digger = 1,
		downloadable = 1,
		explodeas = "MEDIUM_BUILDINGEX",
		firestandorders = 1,
		footprintx = 2,
		footprintz = 2,
		hidedamage = true,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 45,
		mass = 281,
		maxdamage = 2655,
		maxslope = 10,
		maxwaterdepth = 0,
		name = "Dragon's Maw",
		noautofire = false,
		objectname = "core/cormaw.s3o",
		radardistancejam = 8,
		radaremitheight = 45,
		seismicsignature = 0,
		selfdestructas = "MEDIUM_BUILDING",
		sightdistance = 200,
		standingfireorder = 2,
		stealth = true,
		turnrate = 0,
		unitname = "cormaw",
		upright = true,
		usebuildinggrounddecal = true,
		yardmap = "oooo",
		customparams = {
			buildpic = "cormaw.dds",
			faction = "CORE",
			normaltex = "unittextures/core_normals.dds",
		},
		featuredefs = {
			dead = {
				autoreclaimable = 0,
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.0 0.0149960864258 0.116882324219",
				collisionvolumescales = "32.042388916 19.5953521729 32.6287231445",
				collisionvolumetype = "Box",
				damage = 600.01001,
				description = "Dragon's Maw Wreckage",
				energy = 0,
				featuredead = "rockteeth",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 177.0132,
				nodrawundergray = true,
				object = "core/cordrag.s3o",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
				customparams = {
					fromunit = 1,
				},
			},
			rockteeth = {
				animating = 0,
				animtrans = 0,
				blocking = false,
				damage = 500,
				description = "Rubble",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 2,
				object = "2x2a.s3o",
				reclaimable = true,
				shadtrans = 1,
				world = "greenworld",
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			cloak = "kloak1",
			uncloak = "kloak1un",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servmed2",
			},
			select = {
				[1] = "servmed2",
			},
		},
		weapondefs = {
			dmaw = {
				areaofeffect = 64,
				burst = 12,
				burstrate = 0.01,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				firestarter = 100,
				flamegfxtime = 1.2,
				groundbounce = true,
				impulseboost = 0,
				impulsefactor = 0,
				intensity = 0.9,
				name = "FlameThrower",
				noselfdamage = true,
				proximitypriority = 3,
				range = 300,
				reloadtime = 0.5,
				rgbcolor = "1 0.95 0.9",
				rgbcolor2 = "0.9 0.85 0.8",
				sizegrowth = 1.2,
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "Flamhvy1",
				soundtrigger = false,
				sprayangle = 1800,
				targetmoveerror = 0.001,
				turret = true,
				weapontimer = 1,
				weapontype = "Flame",
				weaponvelocity = 300,
				damage = {
					commanders = 18,
					default = 12,
					flamethrowers = 6,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "ANTIFLAME",
				def = "DMAW",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
