-- UNITDEF -- CORMUSKRAT --
--------------------------------------------------------------------------------

local unitName = "cormuskrat"

--------------------------------------------------------------------------------

local unitDef = {
	acceleration = 0.0154,
	bmcode = 1,
	brakeRate = 0.1166,
	buildCostEnergy = 3216,
	buildCostMetal = 161,
	buildDistance = 160,
	builder = true,
	buildPic = [[CORMUSKRAT.png]],
	buildTime = 6864,
	canGuard = true,
	canMove = true,
	canPatrol = true,
	canreclamate = 1,
	canstop = 1,
	category = [[ALL CONSTR MEDIUM MOBILE NOTDEFENSE NOTHOVERNOTVTOL NOTSUB NOTSUBNOTSHIP NOTVTOL NOTWEAPON]],
	corpse = [[DEAD]],
	defaultmissiontype = [[Standby]],
	description = [[Amphibious Construction Vehicle]],
	energyMake = 8,
	energyStorage = 0,
	energyUse = 8,
	explodeAs = [[BIG_UNITEX]],
	footprintX = 3,
	footprintZ = 3,
	idleAutoHeal = 5,
	idleTime = 1800,
	leaveTracks = true,
	maneuverleashlength = 640,
	maxDamage = 995,
	maxSlope = 16,
	maxVelocity = 1.44,
	maxWaterDepth = 255,
	metalMake = 0.08,
	metalStorage = 50,
	mobilestandorders = 1,
	movementClass = [[ATANK3]],
	name = [[Muskrat]],
	noAutoFire = false,
	noChaseCategory = [[SUB VTOL]],
	objectName = [[CORMUSKRAT]],
	seismicSignature = 0,
	selfDestructAs = [[BIG_UNIT]],
	side = [[core]],
	sightDistance = 260,
	smoothAnim = true,
	standingmoveorder = 1,
	steeringmode = 1,
	terraformSpeed = 240,
	trackOffset = 8,
	trackStrength = 5,
	trackStretch = 1,
	trackType = [[StdTank]],
	trackWidth = 24,
	turnRate = 300,
	unitname = [[cormuskrat]],
	workerTime = 120,
	buildoptions = {
		[1] = [[corsolar]],
		[2] = [[coradvsol]],
		[3] = [[corwin]],
		[4] = [[corgeo]],
		[5] = [[cormstor]],
		[6] = [[corestor]],
		[7] = [[cormex]],
		[8] = [[corexp]],
		[9] = [[cormakr]],
		[10] = [[csubpen]],
		[11] = [[corlab]],
		[12] = [[corvp]],
		[13] = [[corap]],
		[14] = [[corsy]],
		[15] = [[corhp]],
		[16] = [[cornanotc]],
		[17] = [[coreyes]],
		[18] = [[corrad]],
		[19] = [[cordrag]],
		[20] = [[cormaw]],
		[21] = [[corllt]],
		[22] = [[hllt]],
		[23] = [[corhlt]],
		[24] = [[corpun]],
		[25] = [[corrl]],
		[26] = [[madsam]],
		[27] = [[corerad]],
		[28] = [[cordl]],
		[29] = [[corjamt]],
		[30] = [[cortide]],
		[31] = [[coruwmex]],
		[32] = [[corfmkr]],
		[33] = [[coruwms]],
		[34] = [[coruwes]],
		[35] = [[csubpen]],
		[36] = [[corsonar]],
		[37] = [[corfdrag]],
		[38] = [[corfrad]],
		[39] = [[corfhlt]],
		[40] = [[corfrt]],
		[41] = [[cortl]],
		[42] = [[cjuno]],
	},
	featureDefs = nil,
	sounds = {
		build = [[nanlath2]],
		canceldestruct = [[cancel2]],
		capture = [[capture1]],
		repair = [[repair2]],
		underattack = [[warning1]],
		working = [[reclaim1]],
		cant = {
			[1] = [[cantdo4]],
		},
		count = {
			[1] = [[count6]],
			[2] = [[count5]],
			[3] = [[count4]],
			[4] = [[count3]],
			[5] = [[count2]],
			[6] = [[count1]],
		},
		ok = {
			[1] = [[vcormove]],
		},
		select = {
			[1] = [[vcorsel]],
		},
	},
}

--------------------------------------------------------------------------------

local featureDefs = {
	DEAD = {
		blocking = true,
		category = [[corpses]],
		damage = 0.6000 * unitDef.maxDamage,
		description = unitDef.name .. [[ Wreckage]],
		energy = 0,
		featureDead = [[HEAP]],
		featurereclamate = [[SMUDGE01]],
		footprintX = 3,
		footprintZ = 3,
		height = 20,
		hitdensity = 100,
		metal = 0.8000 * unitDef.buildCostMetal,
		object = [[CORMUSKRAT_DEAD]],
		reclaimable = true,
		seqnamereclamate = [[TREE1RECLAMATE]],
		world = [[All Worlds]],
	},
	HEAP = {
		blocking = false,
		category = [[heaps]],
		damage = 0.3600 * unitDef.maxDamage,
		description = unitDef.name .. [[ Heap]],
		energy = 0,
		featurereclamate = [[SMUDGE01]],
		footprintX = 3,
		footprintZ = 3,
		height = 4,
		hitdensity = 100,
		metal = 0.6400 * unitDef.buildCostMetal,
		object = [[3X3C]],
		reclaimable = true,
		seqnamereclamate = [[TREE1RECLAMATE]],
		world = [[All Worlds]],
	},
}
unitDef.featureDefs = featureDefs

--------------------------------------------------------------------------------

return lowerkeys({[unitName] = unitDef})

--------------------------------------------------------------------------------
