return {
	cormls = {
		acceleration = 0.046,
		brakerate = 0.18,
		buildcostenergy = 4160,
		buildcostmetal = 305,
		builddistance = 212,
		builder = true,
		buildpic = "CORMLS.png",
		buildtime = 5300,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL CONSTR MEDIUM MOBILE NOTDEFENSE NOTHOVERNOTVTOL NOTSUB NOTVTOL NOTWEAPON",
		collisionvolumeoffsets = "-2 -3 5",
		collisionvolumescales = "24 24 62",
		collisionvolumetype = "CylZ",
		corpse = "DEAD",
		defaultmissiontype = "Standby",
		description = "Naval Engineer",
		energymake = 5,
		energystorage = 0,
		energyuse = 0,
		explodeas = "SMALL_UNITEX",
		floater = true,
		footprintx = 4,
		footprintz = 4,
		icontype = "sea",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 25,
		maneuverleashlength = 640,
		mass = 308,
		maxdamage = 1400,
		maxvelocity = 2.1,
		metalstorage = 0,
		minwaterdepth = 15,
		mobilestandorders = 1,
		movementclass = "BOAT4",
		name = "Pathfinder",
		noautofire = false,
		nochasecategory = "VTOL",
		objectname = "CORMLS",
		radaremitheight = 25,
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT",
		side = "core",
		sightdistance = 360,
		standingmoveorder = 1,
		steeringmode = 1,
		terraformspeed = 750,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1.386,
		turnrate = 377,
		unitname = "cormls",
		workertime = 200,
		buildoptions = {
			[1] = "cortide",
			[2] = "coruwmex",
			[3] = "corasy",
			[4] = "csubpen",
			[5] = "corfhp",
			[6] = "corfnanotc",
			[7] = "coreyes",
			[8] = "corfrad",
			[9] = "corsonar",
			[10] = "corfmine3",
			[11] = "corfhlt",
			[12] = "cortl",
			[13] = "coratl",
			[14] = "corfrt",
			[15] = "corenaa",
			[16] = "corcs",
			[17] = "corpt",
			[18] = "coresupp",
			[19] = "corroy",
			[20] = "corsub",
			[21] = "cormuskrat",
			[22] = "corbats",
		},
		customparams = {
			buildpic = "CORMLS.png",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = -0.1136,
				collisionvolumescales = "33.75 14.0462341309 88.0440979004",
				collisionvolumetype = "Box",
				damage = 862.80005,
				description = "Pathfinder Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 4,
				footprintz = 4,
				height = 20,
				hitdensity = 100,
				metal = 231.2,
				object = "CORMLS_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 517.67999,
				description = "Pathfinder Heap",
				energy = 0,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 184.95999,
				object = "4X4A",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		nanocolor = {
			[1] = 0.2,
			[2] = 0.55,
			[3] = 0.55,
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "shcormov",
			},
			select = {
				[1] = "shcorsel",
			},
		},
	},
}
