return {
	corslander = {
		acceleration = 0.005,
		activatewhenbuilt = false,
		airStrafe  = true,
		airHoverFactor = 1,
		--bankscale = 1,
		bankingAllowed = false,
		blocking = false,
		brakerate = 0.01,
		buildcostenergy = 1601145,
		buildcostmetal = 275640,
		builder = false,
		buildpic = "corslander.dds",
		buildtime = 1250000,
		canattack = false,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MOBILE SATELLITE",
		collide = false,
		corpse = "heap",
		cruisealt = 1750,
		description = "Pyro Launcher",
		explodeas = "KROG_BLAST",
		footprintx = 20,
		footprintz = 20,
		hoverAttack = true,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 6,
		maneuverleashlength = 1280,
		mass = 275640,
		maxdamage = 121550,
		maxslope = 10,
		maxvelocity = 0.75,
		maxwaterdepth = 0,
		mobilestandorders = 1,
		name = "Inferno",
		noautofire = false,
		objectname = "corslander",
		radaremitheight = 50,
		selfdestructas = "KROG_BLAST",
		selfdestructcountdown = 10,
		sightdistance = 1500,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 50,
		turninplacespeedlimit = 2,
		turnrate = 120,
		unitname = "corslander",
		usepiececollisionvolumes = true,
		usepieceselectionvolumes = true,
		customparams = {
			buildpic = "corslander.dds",
			faction = "CORE",
		},
		featuredefs = {
			heap = {
				blocking = false,
				damage = 100641,
				description = "Aircraft Debris",
				footprintx = 10,
				footprintz = 10,
				object = "10X10Z",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "satelliteselect",
			},
			select = {
				[1] = "satelliteselect",
			},
		},
		weapondefs = {
			pyro_cannon = {
				accuracy = 500,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0.01,
				cratermult = 0,
				energypershot = 3447,
				explosiongenerator = "custom:DIRT3",
				gravityaffected = "TRUE",
				impulseboost = 0.1,
				impulsefactor = 0.1,
				metalpershot = 245,
				model = "weapon_unitshell",
				name = "Pyro Launcher",
				noselfdamage = true,
				range = 2000,
				reloadtime = 0.25,
				soundhitdry = "",
				soundhitwet = "",
				soundhitwetvolume = 0.6,
				soundstart = "blackpollen",
				sprayangle = 600,
				stockpile = true,
				stockpiletime = 2,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 1000,
				wobble = 1800,
				damage = {
					default = 100,
				},
			},
		},
		weapons = {
			[1] = {
				def = "PYRO_CANNON",
				onlytargetcategory = "SURFACE",
				maindir = "0 -1 0",
				maxangledif = 15,
			},
		},
	},
}
