local Def = {
	corsjam = {
		acceleration = 0.096,
		activateWhenBuilt = true,
		badTargetCategory = [[MOBILE]],
		bmcode = 1,
		brakeRate = 0.022,
		buildCostEnergy = 2254,
		buildCostMetal = 135,
		buildPic = [[CORSJAM.png]],
		buildTime = 7025,
		builder = false,
		canAttack = true,
		canGuard = true,
		canMove = true,
		canPatrol = true,
		canstop = 1,
		category = [[ALL NOTLAND MOBILE NOTSUB SHIP NOWEAPON NOTAIR]],
		corpse = [[DEAD]],
		defaultmissiontype = [[Standby]],
		description = [[Radar Jammer Ship]],
		energyMake = 20,
		energyStorage = 0,
		energyUse = 20,
		explodeAs = [[SMALL_UNITEX]],
		featureDefs = {
			DEAD = {
				blocking = false,
				category = [[corpses]],
				damage = nil,
				description = nil,
				energy = 0,
				featureDead = [[HEAP]],
				footprintX = 4,
				footprintZ = 4,
				height = 20,
				hitdensity = 100,
				metal = nil,
				object = [[CORSJAM_DEAD]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
			HEAP = {
				blocking = false,
				category = [[heaps]],
				damage = nil,
				description = nil,
				energy = 0,
				footprintX = 2,
				footprintZ = 2,
				height = 4,
				hitdensity = 100,
				metal = nil,
				object = [[4X4A]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
		},
		floater = true,
		footprintX = 4,
		footprintZ = 4,
		iconType = [[sea]],
		idleAutoHeal = 5,
		idleTime = 1800,
		maneuverleashlength = 640,
		maxDamage = 570,
		maxVelocity = 2.88,
		metalStorage = 0,
		minWaterDepth = 6,
		mobilestandorders = 1,
		movementClass = [[BOAT4]],
		name = [[Phantom]],
		noAutoFire = false,
		noChaseCategory = [[MOBILE]],
		objectName = [[CORSJAM]],
		onoffable = true,
		radarDistanceJam = 900,
		seismicSignature = 0,
		selfDestructAs = [[SMALL_UNIT]],
		side = [[CORE]],
		sightDistance = 403,
		smoothAnim = true,
		sounds = {
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[cantdo4]],
			},
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			ok = {
				[1] = [[shcormov]],
			},
			select = {
				[1] = [[radjam2]],
			},
			underattack = [[warning1]],
		},
		standingmoveorder = 1,
		steeringmode = 1,
		turnRate = 512,
		unitname = [[corsjam]],
		weaponDefs = {
			BOGUS_GROUND_MISSILE = {
				areaOfEffect = 48,
				craterBoost = 0,
				craterMult = 0,
				damage = {
					default = 0,
				},
				impulseBoost = 0,
				impulseFactor = 0,
				lineOfSight = true,
				metalpershot = 0,
				name = [[Missiles]],
				range = 800,
				reloadtime = 0.5,
				renderType = 1,
				startVelocity = 450,
				tolerance = 9000,
				turnRate = 33000,
				turret = true,
				weaponAcceleration = 101,
				weaponTimer = 0.1,
				weaponType = [[Cannon]],
				weaponVelocity = 650,
			},
		},
		weapons = {
			[1] = {
				badTargetCategory = [[MOBILE]],
				def = [[BOGUS_GROUND_MISSILE]],
			},
		},
		workerTime = 0,
	},
}
Def.corsjam.featureDefs.DEAD.damage = 0.6000 * Def.corsjam.maxDamage
Def.corsjam.featureDefs.DEAD.description = Def.corsjam.name .. [[ Wreckage]]
Def.corsjam.featureDefs.DEAD.metal = 0.8000 * Def.corsjam.buildCostMetal
Def.corsjam.featureDefs.HEAP.damage = 0.3600 * Def.corsjam.maxDamage
Def.corsjam.featureDefs.HEAP.description = Def.corsjam.name .. [[ Heap]]
Def.corsjam.featureDefs.HEAP.metal = 0.6400 * Def.corsjam.buildCostMetal
return lowerkeys(Def)
