local Def = {
	corsub = {
		acceleration = 0.03,
		activateWhenBuilt = true,
		badTargetCategory = [[HOVER NOTSHIP]],
		bmcode = 1,
		brakeRate = 0.25,
		buildCostEnergy = 3902,
		buildCostMetal = 679,
		buildPic = [[CORSUB.png]],
		buildTime = nil,
		builder = false,
		canAttack = true,
		canGuard = true,
		canMove = true,
		canPatrol = true,
		canstop = 1,
		category = [[ALL UNDERWATER MOBILE WEAPON NOTLAND NOTAIR]],
		collisionvolumeoffsets = [[0 0 0]],
		collisionvolumescales = [[30 10 60]],
		collisionvolumetest = 0,
		collisionvolumetype = [[Ell]],
		corpse = [[DEAD]],
		defaultmissiontype = [[Standby]],
		description = [[Submarine]],
		energyMake = 0.4,
		energyStorage = 0,
		energyUse = 0.4,
		explodeAs = [[SMALL_UNITEX]],
		featureDefs = {
			DEAD = {
				blocking = false,
				category = [[corpses]],
				damage = 501,
				description = [[Snake Wreckage]],
				energy = 0,
				featureDead = [[HEAP]],
				footprintX = 4,
				footprintZ = 4,
				height = 4,
				hitdensity = 100,
				metal = 543.2,
				object = [[CORSUB_DEAD]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
			HEAP = {
				blocking = false,
				category = [[heaps]],
				damage = 300.6,
				description = [[Snake Heap]],
				energy = 0,
				footprintX = 2,
				footprintZ = 2,
				height = 4,
				hitdensity = 100,
				metal = 434.56,
				object = [[4X4B]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
		},
		firestandorders = 1,
		footprintX = 4,
		footprintZ = 4,
		iconType = [[sea]],
		idleAutoHeal = 5,
		idleTime = 1800,
		maneuverleashlength = 640,
		maxDamage = 835,
		maxVelocity = 2.7,
		metalStorage = 0,
		minWaterDepth = 20,
		mobilestandorders = 1,
		movementClass = [[UBOAT4]],
		name = [[Snake]],
		noAutoFire = false,
		noChaseCategory = [[VTOL]],
		objectName = [[CORSUB]],
		seismicSignature = 0,
		selfDestructAs = [[SMALL_UNIT]],
		side = [[CORE]],
		sightDistance = 364,
		smoothAnim = true,
		sonarDistance = 450,
		sounds = {
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[cantdo4]],
			},
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			ok = {
				[1] = [[sucormov]],
			},
			select = {
				[1] = [[sucorsel]],
			},
			underattack = [[warning1]],
		},
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turnRate = 246,
		unitname = [[corsub]],
		upright = true,
		waterline = 30,
		weaponDefs = {
			ARM_TORPEDO = {
				areaOfEffect = 16,
				avoidFriendly = false,
				burnblow = true,
				collideFriendly = false,
				craterBoost = 0,
				craterMult = 0,
				damage = {
					default = 600,
					krogoth = 1200,
					l1subs = 150,
					l2subs = 150,
					l3subs = 150,
				},
				explosionGenerator = [[custom:FLASH2]],
				flightTime = 2.3,
				guidance = true,
				impactonly = 1,
				impulseBoost = 0.123,
				impulseFactor = 0.123,
				lineOfSight = true,
				model = [[torpedo]],
				name = [[Torpedo]],
				noSelfDamage = true,
				propeller = 1,
				range = 500,
				reloadtime = 2.5,
				renderType = 1,
				selfprop = true,
				soundHit = [[xplodep1]],
				soundStart = [[torpedo1]],
				startVelocity = 100,
				tolerance = 32767,
				turnRate = 8000,
				turret = false,
				waterWeapon = true,
				weaponAcceleration = 15,
				weaponTimer = 3,
				weaponType = [[TorpedoLauncher]],
				weaponVelocity = 160,
			},
		},
		weapons = {
			[1] = {
				badTargetCategory = [[HOVER NOTSHIP]],
				def = [[ARM_TORPEDO]],
				mainDir = [[0 0 1]],
				maxAngleDif = 90,
			},
		},
		workerTime = 0,
	},
}
Def.aach.buildTime = 2.0955 * Def.aach.buildCostEnergy
Def.aach.featureDefs.dead.damage = 0.6000 * Def.aach.maxDamage
Def.aach.featureDefs.dead.metal = 0.8000 * Def.aach.buildCostMetal
Def.aafus.buildTime = 1.8182 * Def.aafus.buildCostEnergy
Def.aahp.buildTime = 2.6001 * Def.aahp.buildCostEnergy
Def.aahp.featureDefs.dead.damage = 0.6000 * Def.aahp.maxDamage
Def.aahp.featureDefs.dead.metal = 0.8000 * Def.aahp.buildCostMetal
Def.aahp.featureDefs.heap.damage = 0.3600 * Def.aahp.maxDamage
Def.aahp.featureDefs.heap.metal = 0.6400 * Def.aahp.buildCostMetal
Def.aahpns.buildTime = 1.2217 * Def.aahpns.buildCostEnergy
Def.aahpns.featureDefs.dead.damage = 0.6000 * Def.aahpns.maxDamage
Def.aahpns.featureDefs.dead.metal = 0.8000 * Def.aahpns.buildCostMetal
Def.aahpns.featureDefs.heap.damage = 0.3600 * Def.aahpns.maxDamage
Def.aahpns.featureDefs.heap.metal = 0.6400 * Def.aahpns.buildCostMetal
Def.abroadside.buildTime = 1.4286 * Def.abroadside.buildCostEnergy
Def.abroadside.featureDefs.dead.damage = 0.6000 * Def.abroadside.maxDamage
Def.abroadside.featureDefs.dead.metal = 0.8000 * Def.abroadside.buildCostMetal
Def.abuilderlvl1.buildTime = 3.9372 * Def.abuilderlvl1.buildCostEnergy
Def.abuilderlvl2.buildTime = 1.1032 * Def.abuilderlvl2.buildCostEnergy
Def.abuilderlvl2.featureDefs.dead.damage = 0.6000 * Def.abuilderlvl2.maxDamage
Def.abuilderlvl2.featureDefs.dead.metal = 0.8000 * Def.abuilderlvl2.buildCostMetal
Def.abuilderlvl3.buildTime = 0.6800 * Def.abuilderlvl3.buildCostEnergy
Def.abuilderlvl3.featureDefs.dead.damage = 0.6000 * Def.abuilderlvl3.maxDamage
Def.abuilderlvl3.featureDefs.dead.metal = 0.8000 * Def.abuilderlvl3.buildCostMetal
Def.acovertopscentre.buildTime = 0.0466 * Def.acovertopscentre.buildCostEnergy
Def.acovertopscentre.featureDefs.dead.damage = 0.6000 * Def.acovertopscentre.maxDamage
Def.acovertopscentre.featureDefs.dead.metal = 0.8000 * Def.acovertopscentre.buildCostMetal
Def.aexxec.buildTime = 1.6005 * Def.aexxec.buildCostEnergy
Def.aexxec.featureDefs.dead.damage = 0.6000 * Def.aexxec.maxDamage
Def.aexxec.featureDefs.dead.description = Def.aexxec.name .. [[ Wreckage]]
Def.aexxec.featureDefs.dead.metal = 0.8000 * Def.aexxec.buildCostMetal
Def.aexxec.featureDefs.heap.damage = 0.3600 * Def.aexxec.maxDamage
Def.aexxec.featureDefs.heap.description = Def.aexxec.name .. [[ Heap]]
Def.aexxec.featureDefs.heap.metal = 0.6400 * Def.aexxec.buildCostMetal
Def.afusionplant.buildTime = 1.5652 * Def.afusionplant.buildCostEnergy
Def.afusionplant.featureDefs.dead.damage = 0.6000 * Def.afusionplant.maxDamage
Def.afusionplant.featureDefs.dead.metal = 0.8000 * Def.afusionplant.buildCostMetal
Def.afusionplant.featureDefs.heap.damage = 0.3600 * Def.afusionplant.maxDamage
Def.afusionplant.featureDefs.heap.metal = 0.6400 * Def.afusionplant.buildCostMetal
Def.ahermes.buildTime = 3.0064 * Def.ahermes.buildCostEnergy
Def.ahermes.featureDefs.dead.damage = 0.6000 * Def.ahermes.maxDamage
Def.ahermes.featureDefs.dead.description = Def.ahermes.name .. [[ Wreckage]]
Def.ahermes.featureDefs.dead.metal = 0.8000 * Def.ahermes.buildCostMetal
Def.ahermes.featureDefs.heap.damage = 0.3600 * Def.ahermes.maxDamage
Def.ahermes.featureDefs.heap.description = Def.ahermes.name .. [[ Wreckage]]
Def.ahermes.featureDefs.heap.metal = 0.6400 * Def.ahermes.buildCostMetal
Def.airwolf3g.buildTime = 0.3809 * Def.airwolf3g.buildCostEnergy
Def.ajuno.buildTime = 1.3167 * Def.ajuno.buildCostEnergy
Def.akmech.buildTime = 0.4768 * Def.akmech.buildCostEnergy
Def.akmech.featureDefs.heap.damage = 0.3600 * Def.akmech.maxDamage
Def.akmech.featureDefs.heap.metal = 0.6400 * Def.akmech.buildCostMetal
Def.ametalmakerlvl1.buildTime = 0.8342 * Def.ametalmakerlvl1.buildCostEnergy
Def.ametalmakerlvl2.buildTime = 0.1666 * Def.ametalmakerlvl2.buildCostEnergy
Def.ametalmakerlvl2.featureDefs.dead.damage = 0.6000 * Def.ametalmakerlvl2.maxDamage
Def.ametalmakerlvl2.featureDefs.dead.metal = 0.8000 * Def.ametalmakerlvl2.buildCostMetal
Def.ametalmakerlvl2.featureDefs.heap.damage = 0.3600 * Def.ametalmakerlvl2.maxDamage
Def.ametalmakerlvl2.featureDefs.heap.metal = 0.6400 * Def.ametalmakerlvl2.buildCostMetal
Def.amgeo.buildTime = 2.2727 * Def.amgeo.buildCostEnergy
Def.amortor.buildTime = 1.1531 * Def.amortor.buildCostEnergy
Def.amortor.featureDefs.dead.damage = 0.6000 * Def.amortor.maxDamage
Def.amortor.featureDefs.dead.metal = 0.8000 * Def.amortor.buildCostMetal
Def.amortor.featureDefs.heap.damage = 0.3600 * Def.amortor.maxDamage
Def.amortor.featureDefs.heap.metal = 0.6400 * Def.amortor.buildCostMetal
Def.ananotower.buildTime = 0.7070 * Def.ananotower.buildCostEnergy
Def.ananotower.featureDefs.dead.damage = 0.6000 * Def.ananotower.maxDamage
Def.ananotower.featureDefs.dead.metal = 0.8000 * Def.ananotower.buildCostMetal
Def.apache.buildTime = 1.9878 * Def.apache.buildCostEnergy
Def.apocketfusion.buildTime = 1.4490 * Def.apocketfusion.buildCostEnergy
Def.apocketfusion.featureDefs.dead.damage = 0.6000 * Def.apocketfusion.maxDamage
Def.apocketfusion.featureDefs.dead.description = Def.apocketfusion.name .. [[ Wreckage]]
Def.apocketfusion.featureDefs.dead.metal = 0.8000 * Def.apocketfusion.buildCostMetal
Def.arm_big_bertha.buildTime = 1.4919 * Def.arm_big_bertha.buildCostEnergy
Def.arm_furie.buildTime = 1.0319 * Def.arm_furie.buildCostEnergy
Def.arm_furie.featureDefs.dead.damage = 0.6000 * Def.arm_furie.maxDamage
Def.arm_furie.featureDefs.dead.metal = 0.8000 * Def.arm_furie.buildCostMetal
Def.arm_furie.featureDefs.furie_heap.damage = 0.3600 * Def.arm_furie.maxDamage
Def.arm_furie.featureDefs.furie_heap.metal = 0.6400 * Def.arm_furie.buildCostMetal
Def.arm_guardian.buildTime = 0.6756 * Def.arm_guardian.buildCostEnergy
Def.arm_guardian.featureDefs.core_immolator_heap.damage = 0.6000 * Def.arm_guardian.maxDamage
Def.arm_guardian.featureDefs.core_immolator_heap.metal = 0.8000 * Def.arm_guardian.buildCostMetal
Def.arm_guardian.featureDefs.dead.damage = 0.3600 * Def.arm_guardian.maxDamage
Def.arm_guardian.featureDefs.dead.description = Def.arm_guardian.name .. [[ Wreckage]]
Def.arm_guardian.featureDefs.dead.metal = 0.6400 * Def.arm_guardian.buildCostMetal
Def.arm_immolator.buildTime = 0.3812 * Def.arm_immolator.buildCostEnergy
Def.arm_immolator.featureDefs.core_immolator_dead.damage = 0.6000 * Def.arm_immolator.maxDamage
Def.arm_immolator.featureDefs.core_immolator_dead.description = Def.arm_immolator.name .. [[ Wreckage]]
Def.arm_immolator.featureDefs.core_immolator_dead.metal = 0.8000 * Def.arm_immolator.buildCostMetal
Def.arm_immolator.featureDefs.core_immolator_heap.damage = 0.3600 * Def.arm_immolator.maxDamage
Def.arm_immolator.featureDefs.core_immolator_heap.description = Def.arm_immolator.name .. [[ Heap]]
Def.arm_immolator.featureDefs.core_immolator_heap.metal = 0.6400 * Def.arm_immolator.buildCostMetal
Def.arm_wind_generator.buildTime = 3.1493 * Def.arm_wind_generator.buildCostEnergy
Def.arm_wind_generator.featureDefs.core_wind_generator_heap.damage = 0.6000 * Def.arm_wind_generator.maxDamage
Def.arm_wind_generator.featureDefs.core_wind_generator_heap.metal = 0.8000 * Def.arm_wind_generator.buildCostMetal
Def.arm_wind_generator.featureDefs.dead.damage = 0.3600 * Def.arm_wind_generator.maxDamage
Def.arm_wind_generator.featureDefs.dead.metal = 0.6400 * Def.arm_wind_generator.buildCostMetal
Def.armaak.buildTime = 1.3213 * Def.armaak.buildCostEnergy
Def.armaap.buildTime = 0.6286 * Def.armaap.buildCostEnergy
Def.armaas.buildTime = 1.2224 * Def.armaas.buildCostEnergy
Def.armaaspd.buildTime = 1.8562 * Def.armaaspd.buildCostEnergy
Def.armaaspd.featureDefs.dead.damage = 0.6000 * Def.armaaspd.maxDamage
Def.armaaspd.featureDefs.dead.metal = 0.8000 * Def.armaaspd.buildCostMetal
Def.armaaspd.featureDefs.heap.damage = 0.3600 * Def.armaaspd.maxDamage
Def.armaaspd.featureDefs.heap.metal = 0.6400 * Def.armaaspd.buildCostMetal
Def.armaca.buildTime = 0.9542 * Def.armaca.buildCostEnergy
Def.armack.buildTime = 0.6176 * Def.armack.buildCostEnergy
Def.armacsub.buildTime = 1.5057 * Def.armacsub.buildCostEnergy
Def.armacv.buildTime = 0.3918 * Def.armacv.buildCostEnergy
Def.armadvsol.buildTime = 1.4957 * Def.armadvsol.buildCostEnergy
Def.armah.buildTime = 0.8414 * Def.armah.buildCostEnergy
Def.armah256.buildTime = 1.4124 * Def.armah256.buildCostEnergy
Def.armalab.buildTime = 0.7371 * Def.armalab.buildCostEnergy
Def.armamb.buildTime = 1.6094 * Def.armamb.buildCostEnergy
Def.armamd.buildTime = 1.4052 * Def.armamd.buildCostEnergy
Def.armamd1.buildTime = 0.9811 * Def.armamd1.buildCostEnergy
Def.armamd2.buildTime = 0.6279 * Def.armamd2.buildCostEnergy
Def.armamex.buildTime = 0.8650 * Def.armamex.buildCostEnergy
Def.armamph.buildTime = 2.0997 * Def.armamph.buildCostEnergy
Def.armamspd.buildTime = 2.5372 * Def.armamspd.buildCostEnergy
Def.armamspd.featureDefs.heap.damage = 0.6000 * Def.armamspd.maxDamage
Def.armamspd.featureDefs.heap.description = Def.armamspd.name .. [[ Heap]]
Def.armamspd.featureDefs.heap.metal = 0.8000 * Def.armamspd.buildCostMetal
Def.armanac.buildTime = 1.3069 * Def.armanac.buildCostEnergy
Def.armanni.buildTime = 0.6307 * Def.armanni.buildCostEnergy
Def.armanni1.buildTime = 1.5506 * Def.armanni1.buildCostEnergy
Def.armantar.buildTime = 0.7082 * Def.armantar.buildCostEnergy
Def.armantar.featureDefs.dead.damage = 0.6000 * Def.armantar.maxDamage
Def.armantar.featureDefs.dead.description = Def.armantar.name .. [[ Wreckage]]
Def.armantar.featureDefs.dead.metal = 0.8000 * Def.armantar.buildCostMetal
Def.armantar.featureDefs.heap.damage = 0.3600 * Def.armantar.maxDamage
Def.armantar.featureDefs.heap.description = Def.armantar.name .. [[ Heap]]
Def.armantar.featureDefs.heap.metal = 0.6400 * Def.armantar.buildCostMetal
Def.armap.buildTime = 5.2847 * Def.armap.buildCostEnergy
Def.armarad.buildTime = 0.6618 * Def.armarad.buildCostEnergy
Def.armarch.buildTime = 0.3193 * Def.armarch.buildCostEnergy
Def.armarch.featureDefs.dead.damage = 0.6000 * Def.armarch.maxDamage
Def.armarch.featureDefs.dead.description = Def.armarch.name .. [[ Wreckage]]
Def.armarch.featureDefs.dead.metal = 0.8000 * Def.armarch.buildCostMetal
Def.armarch.featureDefs.heap.damage = 0.3600 * Def.armarch.maxDamage
Def.armarch.featureDefs.heap.description = Def.armarch.name .. [[ Heap]]
Def.armarch.featureDefs.heap.metal = 0.6400 * Def.armarch.buildCostMetal
Def.armarty.buildTime = 2.0047 * Def.armarty.buildCostEnergy
Def.armarty.featureDefs.dead.damage = 0.6000 * Def.armarty.maxDamage
Def.armarty.featureDefs.dead.description = Def.armarty.name .. [[ Wreckage]]
Def.armarty.featureDefs.dead.metal = 0.8000 * Def.armarty.buildCostMetal
Def.armarty.featureDefs.heap.damage = 0.3600 * Def.armarty.maxDamage
Def.armarty.featureDefs.heap.description = Def.armarty.name .. [[ Heap]]
Def.armarty.featureDefs.heap.metal = 0.6400 * Def.armarty.buildCostMetal
Def.armaser.buildTime = 3.7232 * Def.armaser.buildCostEnergy
Def.armason.buildTime = 2.4917 * Def.armason.buildCostEnergy
Def.armasp.buildTime = 4.1699 * Def.armasp.buildCostEnergy
Def.armasy.buildTime = 1.1208 * Def.armasy.buildCostEnergy
Def.armatl.buildTime = 1.0777 * Def.armatl.buildCostEnergy
Def.armatlas.buildTime = 3.1073 * Def.armatlas.buildCostEnergy
Def.armavp.buildTime = 0.5101 * Def.armavp.buildCostEnergy
Def.armawac.buildTime = 1.5901 * Def.armawac.buildCostEnergy
Def.armbanth.buildTime = 1.3848 * Def.armbanth.buildCostEnergy
Def.armbanth1.buildTime = 1.3183 * Def.armbanth1.buildCostEnergy
Def.armbats.buildTime = 2.8330 * Def.armbats.buildCostEnergy
Def.armbc.buildTime = 1.2868 * Def.armbc.buildCostEnergy
Def.armbc.featureDefs.dead.damage = 0.6000 * Def.armbc.maxDamage
Def.armbc.featureDefs.dead.description = Def.armbc.name .. [[ Wreckage]]
Def.armbc.featureDefs.dead.metal = 0.8000 * Def.armbc.buildCostMetal
Def.armbc.featureDefs.heap.damage = 0.3600 * Def.armbc.maxDamage
Def.armbc.featureDefs.heap.description = Def.armbc.name .. [[ Heap]]
Def.armbc.featureDefs.heap.metal = 0.6400 * Def.armbc.buildCostMetal
Def.armbc.featureDefs.tllviking_heap2.damage = 0.2160 * Def.armbc.maxDamage
Def.armbc.featureDefs.tllviking_heap2.metal = 0.5120 * Def.armbc.buildCostMetal
Def.armbeaver.buildTime = 2.2910 * Def.armbeaver.buildCostEnergy
Def.armblab.buildTime = 2.9445 * Def.armblab.buildCostEnergy
Def.armblz.buildTime = 2.3553 * Def.armblz.buildCostEnergy
Def.armbrawl.buildTime = 3.6854 * Def.armbrawl.buildCostEnergy
Def.armbrtha.buildTime = 1.4038 * Def.armbrtha.buildCostEnergy
Def.armbrtha1.buildTime = 1.2290 * Def.armbrtha1.buildCostEnergy
Def.armbull.buildTime = 1.1806 * Def.armbull.buildCostEnergy
Def.armbull2.buildTime = 0.9084 * Def.armbull2.buildCostEnergy
Def.armbull2.featureDefs.heap.damage = 0.3600 * Def.armbull2.maxDamage
Def.armbull2.featureDefs.heap.metal = 0.6400 * Def.armbull2.buildCostMetal
Def.armca.buildTime = 2.0472 * Def.armca.buildCostEnergy
Def.armcarry.buildTime = 1.1984 * Def.armcarry.buildCostEnergy
Def.armcav.buildTime = 1.1530 * Def.armcav.buildCostEnergy
Def.armcav.featureDefs.dead.damage = 0.6000 * Def.armcav.maxDamage
Def.armcav.featureDefs.dead.description = Def.armcav.name .. [[ Wreckage]]
Def.armcav.featureDefs.dead.metal = 0.8000 * Def.armcav.buildCostMetal
Def.armcav.featureDefs.heap.damage = 0.3600 * Def.armcav.maxDamage
Def.armcav.featureDefs.heap.description = Def.armcav.name .. [[ Heap]]
Def.armcav.featureDefs.heap.metal = 0.6400 * Def.armcav.buildCostMetal
Def.armcbomb.buildTime = 2.7251 * Def.armcbomb.buildCostEnergy
Def.armcd.buildTime = 1.0195 * Def.armcd.buildCostEnergy
Def.armcd.featureDefs.dead.damage = 0.6000 * Def.armcd.maxDamage
Def.armcd.featureDefs.dead.description = Def.armcd.name .. [[ Wreckage]]
Def.armcd.featureDefs.dead.metal = 0.8000 * Def.armcd.buildCostMetal
Def.armcd.featureDefs.heap.damage = 0.3600 * Def.armcd.maxDamage
Def.armcd.featureDefs.heap.description = Def.armcd.name .. [[ Heap]]
Def.armcd.featureDefs.heap.metal = 0.6400 * Def.armcd.buildCostMetal
Def.armch.buildTime = 1.7725 * Def.armch.buildCostEnergy
Def.armciph.buildTime = 1.5159 * Def.armciph.buildCostEnergy
Def.armciph.featureDefs.dead.damage = 0.6000 * Def.armciph.maxDamage
Def.armciph.featureDefs.dead.description = Def.armciph.name .. [[ Wreckage]]
Def.armciph.featureDefs.dead.metal = 0.8000 * Def.armciph.buildCostMetal
Def.armciph.featureDefs.heap.damage = 0.3600 * Def.armciph.maxDamage
Def.armciph.featureDefs.heap.description = Def.armciph.name .. [[ Heap]]
Def.armciph.featureDefs.heap.metal = 0.6400 * Def.armciph.buildCostMetal
Def.armcir.buildTime = 2.3332 * Def.armcir.buildCostEnergy
Def.armcir1.buildTime = 2.3332 * Def.armcir1.buildCostEnergy
Def.armck.buildTime = 2.2702 * Def.armck.buildCostEnergy
Def.armckfus.buildTime = 1.9305 * Def.armckfus.buildCostEnergy
Def.armclaw.buildTime = 3.0000 * Def.armclaw.buildCostEnergy
Def.armcom.buildTime = 30.0000 * Def.armcom.buildCostEnergy
Def.armcom1.buildTime = 20.0000 * Def.armcom1.buildCostEnergy
Def.armcom4.buildTime = 40.0000 * Def.armcom4.buildCostEnergy
Def.armcom5.buildTime = 3.0000 * Def.armcom5.buildCostEnergy
Def.armcom6.buildTime = 0.8125 * Def.armcom6.buildCostEnergy
Def.armcom7.buildTime = 0.3500 * Def.armcom7.buildCostEnergy
Def.armcp.buildTime = 1.5554 * Def.armcp.buildCostEnergy
Def.armcp.featureDefs.dead.damage = 0.6000 * Def.armcp.maxDamage
Def.armcp.featureDefs.dead.metal = 0.8000 * Def.armcp.buildCostMetal
Def.armcrabe.buildTime = 2.0197 * Def.armcrabe.buildCostEnergy
Def.armcrabe.featureDefs.dead.damage = 0.6000 * Def.armcrabe.maxDamage
Def.armcrabe.featureDefs.dead.description = Def.armcrabe.name .. [[ Wreckage]]
Def.armcrabe.featureDefs.dead.metal = 0.8000 * Def.armcrabe.buildCostMetal
Def.armcrabe.featureDefs.heap.damage = 0.3600 * Def.armcrabe.maxDamage
Def.armcrabe.featureDefs.heap.description = Def.armcrabe.name .. [[ Heap]]
Def.armcrabe.featureDefs.heap.metal = 0.6400 * Def.armcrabe.buildCostMetal
Def.armcroc.buildTime = 1.1611 * Def.armcroc.buildCostEnergy
Def.armcrus.buildTime = 1.4542 * Def.armcrus.buildCostEnergy
Def.armcs.buildTime = 2.4042 * Def.armcs.buildCostEnergy
Def.armcsa.buildTime = 1.9935 * Def.armcsa.buildCostEnergy
Def.armcspid.buildTime = 0.6618 * Def.armcspid.buildCostEnergy
Def.armcspid.featureDefs.dead.damage = 0.6000 * Def.armcspid.maxDamage
Def.armcspid.featureDefs.dead.metal = 0.8000 * Def.armcspid.buildCostMetal
Def.armcspid.featureDefs.heap.damage = 0.3600 * Def.armcspid.maxDamage
Def.armcspid.featureDefs.heap.metal = 0.6400 * Def.armcspid.buildCostMetal
Def.armcv.buildTime = 2.2564 * Def.armcv.buildCostEnergy
Def.armcybr.buildTime = 1.8876 * Def.armcybr.buildCostEnergy
Def.armdark.buildTime = 2.8480 * Def.armdark.buildCostEnergy
Def.armdark.featureDefs.dead.damage = 0.6000 * Def.armdark.maxDamage
Def.armdark.featureDefs.dead.description = Def.armdark.name .. [[ Wreckage]]
Def.armdark.featureDefs.dead.metal = 0.8000 * Def.armdark.buildCostMetal
Def.armdark.featureDefs.heap.damage = 0.3600 * Def.armdark.maxDamage
Def.armdark.featureDefs.heap.description = Def.armdark.name .. [[ Heap]]
Def.armdark.featureDefs.heap.metal = 0.6400 * Def.armdark.buildCostMetal
Def.armdecom.buildTime = 2.0801 * Def.armdecom.buildCostEnergy
Def.armdf.buildTime = 7.5000 * Def.armdf.buildCostEnergy
Def.armdfly.buildTime = 2.5635 * Def.armdfly.buildCostEnergy
Def.armdl.buildTime = 1.7727 * Def.armdl.buildCostEnergy
Def.armdrag.buildTime = 1.7000 * Def.armdrag.buildCostEnergy
Def.armdragf.buildTime = 5.1501 * Def.armdragf.buildCostEnergy
Def.armeman.buildTime = 1.4709 * Def.armeman.buildCostEnergy
Def.armeman.featureDefs.dead.damage = 0.6000 * Def.armeman.maxDamage
Def.armeman.featureDefs.dead.description = Def.armeman.name .. [[ Wreckage]]
Def.armeman.featureDefs.dead.metal = 0.8000 * Def.armeman.buildCostMetal
Def.armeman.featureDefs.heap.damage = 0.3600 * Def.armeman.maxDamage
Def.armeman.featureDefs.heap.description = Def.armeman.name .. [[ Heap]]
Def.armeman.featureDefs.heap.metal = 0.6400 * Def.armeman.buildCostMetal
Def.armemp.buildTime = 2.9170 * Def.armemp.buildCostEnergy
Def.armestor.buildTime = 2.4497 * Def.armestor.buildCostEnergy
Def.armesy.buildTime = 0.6241 * Def.armesy.buildCostEnergy
Def.armesy.featureDefs.dead.damage = 0.3600 * Def.armesy.maxDamage
Def.armesy.featureDefs.dead.description = Def.armesy.name .. [[ Wreckage]]
Def.armesy.featureDefs.dead.metal = 0.6400 * Def.armesy.buildCostMetal
Def.armevp.buildTime = 3.2106 * Def.armevp.buildCostEnergy
Def.armevp.featureDefs.dead.damage = 0.6000 * Def.armevp.maxDamage
Def.armevp.featureDefs.dead.description = Def.armevp.name .. [[ Wreckage]]
Def.armevp.featureDefs.dead.metal = 0.8000 * Def.armevp.buildCostMetal
Def.armevp.featureDefs.heap.damage = 0.3600 * Def.armevp.maxDamage
Def.armevp.featureDefs.heap.description = Def.armevp.name .. [[ Heap]]
Def.armevp.featureDefs.heap.metal = 0.6400 * Def.armevp.buildCostMetal
Def.armeyes.buildTime = 1.8750 * Def.armeyes.buildCostEnergy
Def.armfark.buildTime = 1.5403 * Def.armfark.buildCostEnergy
Def.armfark1.buildTime = 1.5403 * Def.armfark1.buildCostEnergy
Def.armfast.buildTime = 0.7230 * Def.armfast.buildCostEnergy
Def.armfatf.buildTime = 1.4532 * Def.armfatf.buildCostEnergy
Def.armfav.buildTime = 2.6667 * Def.armfav.buildCostEnergy
Def.armfboy.buildTime = 2.0010 * Def.armfboy.buildCostEnergy
Def.armfboy1.buildTime = 2.0010 * Def.armfboy1.buildCostEnergy
Def.armfdrag.buildTime = 1.5500 * Def.armfdrag.buildCostEnergy
Def.armfflak.buildTime = 1.0034 * Def.armfflak.buildCostEnergy
Def.armfhlt.buildTime = 1.7560 * Def.armfhlt.buildCostEnergy
Def.armfhp.buildTime = 3.5096 * Def.armfhp.buildCostEnergy
Def.armfido.buildTime = 1.3153 * Def.armfido.buildCostEnergy
Def.armfig.buildTime = 1.2895 * Def.armfig.buildCostEnergy
Def.armflak.buildTime = 0.5078 * Def.armflak.buildCostEnergy
Def.armflash.buildTime = 2.1477 * Def.armflash.buildCostEnergy
Def.armflash1.buildTime = 1.3264 * Def.armflash1.buildCostEnergy
Def.armflea.buildTime = 2.4503 * Def.armflea.buildCostEnergy
Def.armflea1.buildTime = 2.4503 * Def.armflea1.buildCostEnergy
Def.armflosh.buildTime = 2.1161 * Def.armflosh.buildCostEnergy
Def.armflspd.buildTime = 1.9182 * Def.armflspd.buildCostEnergy
Def.armflspd.featureDefs.dead.damage = 0.6000 * Def.armflspd.maxDamage
Def.armflspd.featureDefs.dead.description = Def.armflspd.name .. [[ Wreckage]]
Def.armflspd.featureDefs.dead.metal = 0.8000 * Def.armflspd.buildCostMetal
Def.armflspd.featureDefs.heap.damage = 0.3600 * Def.armflspd.maxDamage
Def.armflspd.featureDefs.heap.description = Def.armflspd.name .. [[ Heap]]
Def.armflspd.featureDefs.heap.metal = 0.6400 * Def.armflspd.buildCostMetal
Def.armfmine3.buildTime = 0.1000 * Def.armfmine3.buildCostEnergy
Def.armfmkr.buildTime = 1.0449 * Def.armfmkr.buildCostEnergy
Def.armfor.buildTime = 0.5092 * Def.armfor.buildCostEnergy
Def.armfort.buildTime = 1.4296 * Def.armfort.buildCostEnergy
Def.armfrad.buildTime = 1.6619 * Def.armfrad.buildCostEnergy
Def.armfrt.buildTime = 2.1915 * Def.armfrt.buildCostEnergy
Def.armfsilo.buildTime = 0.5456 * Def.armfsilo.buildCostEnergy
Def.armfsilo.featureDefs.dead.damage = 0.6000 * Def.armfsilo.maxDamage
Def.armfsilo.featureDefs.dead.description = Def.armfsilo.name .. [[ Wreckage]]
Def.armfsilo.featureDefs.dead.metal = 0.8000 * Def.armfsilo.buildCostMetal
Def.armfsilo.featureDefs.heap.damage = 0.3600 * Def.armfsilo.maxDamage
Def.armfsilo.featureDefs.heap.description = Def.armfsilo.name .. [[ heap]]
Def.armfsilo.featureDefs.heap.metal = 0.6400 * Def.armfsilo.buildCostMetal
Def.armfus.buildTime = 1.7085 * Def.armfus.buildCostEnergy
Def.armgant.buildTime = 2.0745 * Def.armgant.buildCostEnergy
Def.armgant.featureDefs.dead.damage = 0.6000 * Def.armgant.maxDamage
Def.armgant.featureDefs.dead.description = Def.armgant.name .. [[ Wreckage]]
Def.armgant.featureDefs.dead.metal = 0.8000 * Def.armgant.buildCostMetal
Def.armgant.featureDefs.heap.damage = 0.3600 * Def.armgant.maxDamage
Def.armgant.featureDefs.heap.description = Def.armgant.name .. [[ Heap]]
Def.armgant.featureDefs.heap.metal = 0.6400 * Def.armgant.buildCostMetal
Def.armgate.buildTime = 0.8705 * Def.armgate.buildCostEnergy
Def.armgate1.buildTime = 2.8472 * Def.armgate1.buildCostEnergy
Def.armgate2.buildTime = 6.7674 * Def.armgate2.buildCostEnergy
Def.armgeo.buildTime = 2.5301 * Def.armgeo.buildCostEnergy
Def.armgeo.featureDefs.dead.damage = 0.3600 * Def.armgeo.maxDamage
Def.armgeo.featureDefs.dead.description = Def.armgeo.name .. [[ Wreckage]]
Def.armgeo.featureDefs.dead.metal = 0.6400 * Def.armgeo.buildCostMetal
Def.armgmm.buildTime = 1.9091 * Def.armgmm.buildCostEnergy
Def.armgor.buildTime = 1.1392 * Def.armgor.buildCostEnergy
Def.armgor.featureDefs.dead.damage = 0.6000 * Def.armgor.maxDamage
Def.armgor.featureDefs.dead.description = Def.armgor.name .. [[ Wreckage]]
Def.armgor.featureDefs.dead.metal = 0.8000 * Def.armgor.buildCostMetal
Def.armgor.featureDefs.heap.damage = 0.3600 * Def.armgor.maxDamage
Def.armgor.featureDefs.heap.description = Def.armgor.name .. [[ Heap]]
Def.armgor.featureDefs.heap.metal = 0.6400 * Def.armgor.buildCostMetal
Def.armguard.buildTime = 1.8291 * Def.armguard.buildCostEnergy
Def.armham.buildTime = 1.7953 * Def.armham.buildCostEnergy
Def.armham1.buildTime = 1.0371 * Def.armham1.buildCostEnergy
Def.armhawk.buildTime = 1.7723 * Def.armhawk.buildCostEnergy
Def.armhcar.buildTime = 0.5879 * Def.armhcar.buildCostEnergy
Def.armhcar.featureDefs.dead.damage = 0.6000 * Def.armhcar.maxDamage
Def.armhcar.featureDefs.dead.description = Def.armhcar.name .. [[ Wreckage]]
Def.armhcar.featureDefs.dead.metal = 0.8000 * Def.armhcar.buildCostMetal
Def.armhdpw.buildTime = 0.7239 * Def.armhdpw.buildCostEnergy
Def.armhdpw.featureDefs.dead.damage = 0.6000 * Def.armhdpw.maxDamage
Def.armhdpw.featureDefs.dead.description = Def.armhdpw.name .. [[ Wreckage]]
Def.armhdpw.featureDefs.dead.metal = 0.8000 * Def.armhdpw.buildCostMetal
Def.armhdpw.featureDefs.heap.damage = 0.3600 * Def.armhdpw.maxDamage
Def.armhdpw.featureDefs.heap.description = Def.armhdpw.name .. [[ Heap]]
Def.armhdpw.featureDefs.heap.metal = 0.6400 * Def.armhdpw.buildCostMetal
Def.armhevsenan.buildTime = 1.7090 * Def.armhevsenan.buildCostEnergy
Def.armhh.buildTime = 1.9700 * Def.armhh.buildCostEnergy
Def.armhh.featureDefs.dead.damage = 0.6000 * Def.armhh.maxDamage
Def.armhh.featureDefs.dead.description = Def.armhh.name .. [[ Wreckage]]
Def.armhh.featureDefs.dead.metal = 0.8000 * Def.armhh.buildCostMetal
Def.armhh.featureDefs.heap.damage = 0.3600 * Def.armhh.maxDamage
Def.armhh.featureDefs.heap.description = Def.armhh.name .. [[ Heap]]
Def.armhh.featureDefs.heap.metal = 0.6400 * Def.armhh.buildCostMetal
Def.armhls.buildTime = 2.7492 * Def.armhls.buildCostEnergy
Def.armhls.featureDefs.dead.damage = 0.6000 * Def.armhls.maxDamage
Def.armhls.featureDefs.dead.description = Def.armhls.name .. [[ Wreckage]]
Def.armhls.featureDefs.dead.metal = 0.8000 * Def.armhls.buildCostMetal
Def.armhlt.buildTime = 2.1771 * Def.armhlt.buildCostEnergy
Def.armhlt1.buildTime = 1.9101 * Def.armhlt1.buildCostEnergy
Def.armhp.buildTime = 3.5102 * Def.armhp.buildCostEnergy
Def.armhplasma.buildTime = 0.7911 * Def.armhplasma.buildCostEnergy
Def.armhplasma.featureDefs.dead.damage = 0.6000 * Def.armhplasma.maxDamage
Def.armhplasma.featureDefs.dead.description = Def.armhplasma.name .. [[ Wreckage]]
Def.armhplasma.featureDefs.dead.metal = 0.8000 * Def.armhplasma.buildCostMetal
Def.armhplasma.featureDefs.heap.damage = 0.3600 * Def.armhplasma.maxDamage
Def.armhplasma.featureDefs.heap.description = Def.armhplasma.name .. [[ Heap]]
Def.armhplasma.featureDefs.heap.metal = 0.6400 * Def.armhplasma.buildCostMetal
Def.armiguana.buildTime = 1.8259 * Def.armiguana.buildCostEnergy
Def.armiguana.featureDefs.corsent_dead.damage = 0.3600 * Def.armiguana.maxDamage
Def.armiguana.featureDefs.corsent_dead.metal = 0.6400 * Def.armiguana.buildCostMetal
Def.armjade.buildTime = 1.0888 * Def.armjade.buildCostEnergy
Def.armjag.buildTime = 1.2103 * Def.armjag.buildCostEnergy
Def.armjag.featureDefs.dead.damage = 0.6000 * Def.armjag.maxDamage
Def.armjag.featureDefs.dead.description = Def.armjag.name .. [[ Wreckage]]
Def.armjag.featureDefs.dead.metal = 0.8000 * Def.armjag.buildCostMetal
Def.armjag.featureDefs.heap.damage = 0.3600 * Def.armjag.maxDamage
Def.armjag.featureDefs.heap.description = Def.armjag.name .. [[ Heap]]
Def.armjag.featureDefs.heap.metal = 0.6400 * Def.armjag.buildCostMetal
Def.armjam.buildTime = 3.6601 * Def.armjam.buildCostEnergy
Def.armjam.featureDefs.dead.damage = 0.3600 * Def.armjam.maxDamage
Def.armjam.featureDefs.dead.description = Def.armjam.name .. [[ Wreckage]]
Def.armjam.featureDefs.dead.metal = 0.6400 * Def.armjam.buildCostMetal
Def.armjamt.buildTime = 1.2530 * Def.armjamt.buildCostEnergy
Def.armjanus.buildTime = 1.5015 * Def.armjanus.buildCostEnergy
Def.armjanus1.buildTime = 1.0871 * Def.armjanus1.buildCostEnergy
Def.armjaspd.buildTime = 3.5055 * Def.armjaspd.buildCostEnergy
Def.armjaspd.featureDefs.dead.damage = 0.6000 * Def.armjaspd.maxDamage
Def.armjaspd.featureDefs.dead.description = Def.armjaspd.name .. [[ Wreckage]]
Def.armjaspd.featureDefs.dead.metal = 0.8000 * Def.armjaspd.buildCostMetal
Def.armjaspd.featureDefs.heap.damage = 0.3600 * Def.armjaspd.maxDamage
Def.armjaspd.featureDefs.heap.description = Def.armjaspd.name .. [[ Heap]]
Def.armjaspd.featureDefs.heap.metal = 0.6400 * Def.armjaspd.buildCostMetal
Def.armjeth.buildTime = 1.6691 * Def.armjeth.buildCostEnergy
Def.armjugg.buildTime = 1.3761 * Def.armjugg.buildCostEnergy
Def.armjugg.featureDefs.dead.damage = 0.6000 * Def.armjugg.maxDamage
Def.armjugg.featureDefs.dead.description = Def.armjugg.name .. [[ Wreckage]]
Def.armjugg.featureDefs.dead.metal = 0.8000 * Def.armjugg.buildCostMetal
Def.armjugg.featureDefs.heap.damage = 0.3600 * Def.armjugg.maxDamage
Def.armjugg.featureDefs.heap.description = Def.armjugg.name .. [[ Heap]]
Def.armjugg.featureDefs.heap.metal = 0.6400 * Def.armjugg.buildCostMetal
Def.armkam.buildTime = 2.2668 * Def.armkam.buildCostEnergy
Def.armkrmi.buildTime = 1.5793 * Def.armkrmi.buildCostEnergy
Def.armkrmi.featureDefs.dead.damage = 0.6000 * Def.armkrmi.maxDamage
Def.armkrmi.featureDefs.dead.metal = 0.8000 * Def.armkrmi.buildCostMetal
Def.armkrmi.featureDefs.heap.damage = 0.3600 * Def.armkrmi.maxDamage
Def.armkrmi.featureDefs.heap.metal = 0.6400 * Def.armkrmi.buildCostMetal
Def.armlab.buildTime = 4.6549 * Def.armlab.buildCostEnergy
Def.armlance.buildTime = 2.2880 * Def.armlance.buildCostEnergy
Def.armlashover.buildTime = 2.0423 * Def.armlashover.buildCostEnergy
Def.armlashover.featureDefs.dead.damage = 0.6000 * Def.armlashover.maxDamage
Def.armlashover.featureDefs.dead.metal = 0.8000 * Def.armlashover.buildCostMetal
Def.armlashover.featureDefs.heap.damage = 0.3600 * Def.armlashover.maxDamage
Def.armlashover.featureDefs.heap.metal = 0.6400 * Def.armlashover.buildCostMetal
Def.armlaspd.buildTime = 2.1550 * Def.armlaspd.buildCostEnergy
Def.armlaspd.featureDefs.dead.damage = 0.6000 * Def.armlaspd.maxDamage
Def.armlaspd.featureDefs.dead.description = Def.armlaspd.name .. [[ Wreckage]]
Def.armlaspd.featureDefs.dead.metal = 0.8000 * Def.armlaspd.buildCostMetal
Def.armlaspd.featureDefs.heap.damage = 0.3600 * Def.armlaspd.maxDamage
Def.armlaspd.featureDefs.heap.description = Def.armlaspd.name .. [[ Heap]]
Def.armlaspd.featureDefs.heap.metal = 0.6400 * Def.armlaspd.buildCostMetal
Def.armlatnk.buildTime = 1.0763 * Def.armlatnk.buildCostEnergy
Def.armllt.buildTime = 4.1790 * Def.armllt.buildCostEnergy
Def.armllt1.buildTime = 4.0769 * Def.armllt1.buildCostEnergy
Def.armmagneto.buildTime = 0.8450 * Def.armmagneto.buildCostEnergy
Def.armmakr.buildTime = 0.9833 * Def.armmakr.buildCostEnergy
Def.armmanni.buildTime = 2.0603 * Def.armmanni.buildCostEnergy
Def.armmark.buildTime = 3.2986 * Def.armmark.buildCostEnergy
Def.armmark.featureDefs.dead.damage = 0.3600 * Def.armmark.maxDamage
Def.armmark.featureDefs.dead.description = Def.armmark.name .. [[ Wreckage]]
Def.armmark.featureDefs.dead.metal = 0.6400 * Def.armmark.buildCostMetal
Def.armmart.buildTime = 0.8862 * Def.armmart.buildCostEnergy
Def.armmas.buildTime = 1.2328 * Def.armmas.buildCostEnergy
Def.armmav.buildTime = 1.5094 * Def.armmav.buildCostEnergy
Def.armmav.featureDefs.heap.damage = 0.3600 * Def.armmav.maxDamage
Def.armmav.featureDefs.heap.description = Def.armmav.name .. [[ Heap]]
Def.armmav.featureDefs.heap.metal = 0.6400 * Def.armmav.buildCostMetal
Def.armmcv.buildTime = 0.9343 * Def.armmcv.buildCostEnergy
Def.armmcv.featureDefs.dead.damage = 0.6000 * Def.armmcv.maxDamage
Def.armmcv.featureDefs.dead.description = Def.armmcv.name .. [[ Wreckage]]
Def.armmcv.featureDefs.dead.metal = 0.8000 * Def.armmcv.buildCostMetal
Def.armmcv.featureDefs.heap.damage = 0.3600 * Def.armmcv.maxDamage
Def.armmcv.featureDefs.heap.description = Def.armmcv.name .. [[ Heap]]
Def.armmcv.featureDefs.heap.metal = 0.6400 * Def.armmcv.buildCostMetal
Def.armmech.buildTime = 1.0116 * Def.armmech.buildCostEnergy
Def.armmech.featureDefs.heap.damage = 0.3600 * Def.armmech.maxDamage
Def.armmech.featureDefs.heap.description = Def.armmech.name .. [[ Heap]]
Def.armmech.featureDefs.heap.metal = 0.6400 * Def.armmech.buildCostMetal
Def.armmechl.buildTime = 2.0584 * Def.armmechl.buildCostEnergy
Def.armmechl.featureDefs.corgant_heap.damage = 0.6000 * Def.armmechl.maxDamage
Def.armmechl.featureDefs.corgant_heap.metal = 0.8000 * Def.armmechl.buildCostMetal
Def.armmechl.featureDefs.dead.damage = 0.3600 * Def.armmechl.maxDamage
Def.armmechl.featureDefs.dead.description = Def.armmechl.name .. [[ Wreckage]]
Def.armmechl.featureDefs.dead.metal = 0.6400 * Def.armmechl.buildCostMetal
Def.armmedt.buildTime = 2.7372 * Def.armmedt.buildCostEnergy
Def.armmedt.featureDefs.dead.damage = 0.6000 * Def.armmedt.maxDamage
Def.armmedt.featureDefs.dead.description = Def.armmedt.name .. [[ Wreckage]]
Def.armmedt.featureDefs.dead.metal = 0.8000 * Def.armmedt.buildCostMetal
Def.armmedt.featureDefs.heap.damage = 0.3600 * Def.armmedt.maxDamage
Def.armmedt.featureDefs.heap.description = Def.armmedt.name .. [[ Heap]]
Def.armmedt.featureDefs.heap.metal = 0.6400 * Def.armmedt.buildCostMetal
Def.armmerl.buildTime = 2.5369 * Def.armmerl.buildCostEnergy
Def.armmex.buildTime = 3.4549 * Def.armmex.buildCostEnergy
Def.armmex1.buildTime = 0.3260 * Def.armmex1.buildCostEnergy
Def.armmh.buildTime = 1.1687 * Def.armmh.buildCostEnergy
Def.armmine1.buildTime = 0.2000 * Def.armmine1.buildCostEnergy
Def.armmine2.buildTime = 0.1000 * Def.armmine2.buildCostEnergy
Def.armmine3.buildTime = 0.1000 * Def.armmine3.buildCostEnergy
Def.armmlrs.buildTime = 0.5950 * Def.armmlrs.buildCostEnergy
Def.armmls.buildTime = 1.4086 * Def.armmls.buildCostEnergy
Def.armmlspd.buildTime = 1.3427 * Def.armmlspd.buildCostEnergy
Def.armmlspd.featureDefs.dead.damage = 0.6000 * Def.armmlspd.maxDamage
Def.armmlspd.featureDefs.dead.metal = 0.8000 * Def.armmlspd.buildCostMetal
Def.armmlspd.featureDefs.heap.damage = 0.3600 * Def.armmlspd.maxDamage
Def.armmlspd.featureDefs.heap.metal = 0.6400 * Def.armmlspd.buildCostMetal
Def.armmlv.buildTime = 3.4132 * Def.armmlv.buildCostEnergy
Def.armmmkr.buildTime = 0.9939 * Def.armmmkr.buildCostEnergy
Def.armmoho.buildTime = 2.0707 * Def.armmoho.buildCostEnergy
Def.armmship.buildTime = 2.2763 * Def.armmship.buildCostEnergy
Def.armmstor.buildTime = 5.4673 * Def.armmstor.buildCostEnergy
Def.armnanotc.buildTime = 0.5888 * Def.armnanotc.buildCostEnergy
Def.armorca.buildTime = 2.4484 * Def.armorca.buildCostEnergy
Def.armorca.featureDefs.dead.damage = 0.6000 * Def.armorca.maxDamage
Def.armorca.featureDefs.dead.description = Def.armorca.name .. [[ Wreckage]]
Def.armorca.featureDefs.dead.metal = 0.8000 * Def.armorca.buildCostMetal
Def.armorca.featureDefs.heap.damage = 0.3600 * Def.armorca.maxDamage
Def.armorca.featureDefs.heap.description = Def.armorca.name .. [[ Heap]]
Def.armorca.featureDefs.heap.metal = 0.6400 * Def.armorca.buildCostMetal
Def.armorco.buildTime = 0.9352 * Def.armorco.buildCostEnergy
Def.armorco.featureDefs.heap.damage = 0.3600 * Def.armorco.maxDamage
Def.armorco.featureDefs.heap.description = Def.armorco.name .. [[ Debris]]
Def.armorco.featureDefs.heap.metal = 0.6400 * Def.armorco.buildCostMetal
Def.armpaspd.buildTime = 1.4669 * Def.armpaspd.buildCostEnergy
Def.armpaspd.featureDefs.dead.damage = 0.6000 * Def.armpaspd.maxDamage
Def.armpaspd.featureDefs.dead.description = Def.armpaspd.name .. [[ Wreckage]]
Def.armpaspd.featureDefs.dead.metal = 0.8000 * Def.armpaspd.buildCostMetal
Def.armpaspd.featureDefs.heap.damage = 0.3600 * Def.armpaspd.maxDamage
Def.armpaspd.featureDefs.heap.description = Def.armpaspd.name .. [[ Heap]]
Def.armpaspd.featureDefs.heap.metal = 0.6400 * Def.armpaspd.buildCostMetal
Def.armpb.buildTime = 1.0595 * Def.armpb.buildCostEnergy
Def.armpeep.buildTime = 1.7525 * Def.armpeep.buildCostEnergy
Def.armpers.buildTime = 2.3817 * Def.armpers.buildCostEnergy
Def.armpincer.buildTime = 1.3602 * Def.armpincer.buildCostEnergy
Def.armplat.buildTime = 0.4882 * Def.armplat.buildCostEnergy
Def.armpnix.buildTime = 2.9239 * Def.armpnix.buildCostEnergy
Def.armpod.buildTime = 1.1027 * Def.armpod.buildCostEnergy
Def.armpod.featureDefs.dead.damage = 0.6000 * Def.armpod.maxDamage
Def.armpod.featureDefs.dead.description = Def.armpod.name .. [[ Wreckage]]
Def.armpod.featureDefs.dead.metal = 0.8000 * Def.armpod.buildCostMetal
Def.armpraet.buildTime = 1.0771 * Def.armpraet.buildCostEnergy
Def.armpt.buildTime = 2.0934 * Def.armpt.buildCostEnergy
Def.armpw.buildTime = 1.5831 * Def.armpw.buildCostEnergy
Def.armpw1.buildTime = 1.5831 * Def.armpw1.buildCostEnergy
Def.armrad.buildTime = 1.8950 * Def.armrad.buildCostEnergy
Def.armrad1.buildTime = 1.8950 * Def.armrad1.buildCostEnergy
Def.armraptor.buildTime = 0.9780 * Def.armraptor.buildCostEnergy
Def.armraptor.featureDefs.dead.damage = 0.6000 * Def.armraptor.maxDamage
Def.armraptor.featureDefs.dead.description = Def.armraptor.name .. [[ Wreckage]]
Def.armraptor.featureDefs.dead.metal = 0.8000 * Def.armraptor.buildCostMetal
Def.armraptor.featureDefs.heap.damage = 0.3600 * Def.armraptor.maxDamage
Def.armraptor.featureDefs.heap.description = Def.armraptor.name .. [[ Heap]]
Def.armraptor.featureDefs.heap.metal = 0.6400 * Def.armraptor.buildCostMetal
Def.armraven.buildTime = 1.6730 * Def.armraven.buildCostEnergy
Def.armraven1.buildTime = 0.9977 * Def.armraven1.buildCostEnergy
Def.armraz.buildTime = 0.5213 * Def.armraz.buildCostEnergy
Def.armraz1.buildTime = 1.1659 * Def.armraz1.buildCostEnergy
Def.armrech18.buildTime = 5.0000 * Def.armrech18.buildCostEnergy
Def.armrech21.buildTime = 5.0000 * Def.armrech21.buildCostEnergy
Def.armrech3.buildTime = 0.7813 * Def.armrech3.buildCostEnergy
Def.armrecl.buildTime = 1.3397 * Def.armrecl.buildCostEnergy
Def.armrectr.buildTime = 1.7143 * Def.armrectr.buildCostEnergy
Def.armrezspd.buildTime = 6.0851 * Def.armrezspd.buildCostEnergy
Def.armrezspd.featureDefs.dead.damage = 0.6000 * Def.armrezspd.maxDamage
Def.armrezspd.featureDefs.dead.description = Def.armrezspd.name .. [[ Wreckage]]
Def.armrezspd.featureDefs.dead.metal = 0.8000 * Def.armrezspd.buildCostMetal
Def.armrezspd.featureDefs.heap.damage = 0.3600 * Def.armrezspd.maxDamage
Def.armrezspd.featureDefs.heap.description = Def.armrezspd.name .. [[ Heap]]
Def.armrezspd.featureDefs.heap.metal = 0.6400 * Def.armrezspd.buildCostMetal
Def.armrl.buildTime = 2.1862 * Def.armrl.buildCostEnergy
Def.armrl1.buildTime = 2.1862 * Def.armrl1.buildCostEnergy
Def.armrock.buildTime = 1.9989 * Def.armrock.buildCostEnergy
Def.armrock1.buildTime = 1.1478 * Def.armrock1.buildCostEnergy
Def.armroy.buildTime = 2.3613 * Def.armroy.buildCostEnergy
Def.armsaber.buildTime = 1.8409 * Def.armsaber.buildCostEnergy
Def.armsam.buildTime = 1.4529 * Def.armsam.buildCostEnergy
Def.armsam1.buildTime = 1.1605 * Def.armsam1.buildCostEnergy
Def.armsb.buildTime = 1.2837 * Def.armsb.buildCostEnergy
Def.armscab.buildTime = 1.0873 * Def.armscab.buildCostEnergy
Def.armscab1.buildTime = 1.0940 * Def.armscab1.buildCostEnergy
Def.armscar.buildTime = 3.3829 * Def.armscar.buildCostEnergy
Def.armscar.featureDefs.dead.damage = 0.6000 * Def.armscar.maxDamage
Def.armscar.featureDefs.dead.description = Def.armscar.name .. [[ Wreckage]]
Def.armscar.featureDefs.dead.metal = 0.8000 * Def.armscar.buildCostMetal
Def.armscar.featureDefs.heap.damage = 0.3600 * Def.armscar.maxDamage
Def.armscar.featureDefs.heap.description = Def.armscar.name .. [[ Heap]]
Def.armscar.featureDefs.heap.metal = 0.6400 * Def.armscar.buildCostMetal
Def.armscpion.buildTime = 2.6691 * Def.armscpion.buildCostEnergy
Def.armscpion.featureDefs.dead.damage = 0.6000 * Def.armscpion.maxDamage
Def.armscpion.featureDefs.dead.description = Def.armscpion.name .. [[ Wreckage]]
Def.armscpion.featureDefs.dead.metal = 0.8000 * Def.armscpion.buildCostMetal
Def.armscpion.featureDefs.heap.damage = 0.3600 * Def.armscpion.maxDamage
Def.armscpion.featureDefs.heap.description = Def.armscpion.name .. [[ Heap]]
Def.armscpion.featureDefs.heap.metal = 0.6400 * Def.armscpion.buildCostMetal
Def.armsd.buildTime = 1.7624 * Def.armsd.buildCostEnergy
Def.armseap.buildTime = 2.0887 * Def.armseap.buildCostEnergy
Def.armseer.buildTime = 3.1870 * Def.armseer.buildCostEnergy
Def.armsehak.buildTime = 1.3684 * Def.armsehak.buildCostEnergy
Def.armsfig.buildTime = 1.7031 * Def.armsfig.buildCostEnergy
Def.armsh.buildTime = 2.8988 * Def.armsh.buildCostEnergy
Def.armsh175.buildTime = 0.4780 * Def.armsh175.buildCostEnergy
Def.armshltx.buildTime = 1.1254 * Def.armshltx.buildCostEnergy
Def.armshltx1.buildTime = 1.0269 * Def.armshltx1.buildCostEnergy
Def.armshock.buildTime = 1.1184 * Def.armshock.buildCostEnergy
Def.armshock1.buildTime = 0.8542 * Def.armshock1.buildCostEnergy
Def.armsiege.buildTime = 0.3240 * Def.armsiege.buildCostEnergy
Def.armsiege.featureDefs.dead.damage = 0.6000 * Def.armsiege.maxDamage
Def.armsiege.featureDefs.dead.description = Def.armsiege.name .. [[ Wreckage]]
Def.armsiege.featureDefs.dead.metal = 0.8000 * Def.armsiege.buildCostMetal
Def.armsiege.featureDefs.heap.damage = 0.3600 * Def.armsiege.maxDamage
Def.armsiege.featureDefs.heap.description = Def.armsiege.name .. [[ Heap]]
Def.armsiege.featureDefs.heap.metal = 0.6400 * Def.armsiege.buildCostMetal
Def.armsilo.buildTime = 2.1177 * Def.armsilo.buildCostEnergy
Def.armsilo1.buildTime = 1.3291 * Def.armsilo1.buildCostEnergy
Def.armsjam.buildTime = 3.4793 * Def.armsjam.buildCostEnergy
Def.armsl.buildTime = 2.5101 * Def.armsl.buildCostEnergy
Def.armsnipe.buildTime = 1.2994 * Def.armsnipe.buildCostEnergy
Def.armsolar.buildTime = 1.#INF * Def.armsolar.buildCostEnergy
Def.armsonar.buildTime = 2.2630 * Def.armsonar.buildCostEnergy
Def.armsonic.buildTime = 2.0368 * Def.armsonic.buildCostEnergy
Def.armsonic.featureDefs.dead.damage = 0.6000 * Def.armsonic.maxDamage
Def.armsonic.featureDefs.dead.metal = 0.8000 * Def.armsonic.buildCostMetal
Def.armsonic.featureDefs.heap.damage = 0.3600 * Def.armsonic.maxDamage
Def.armsonic.featureDefs.heap.metal = 0.6400 * Def.armsonic.buildCostMetal
Def.armspid.buildTime = 1.6057 * Def.armspid.buildCostEnergy
Def.armsptk.buildTime = 2.0893 * Def.armsptk.buildCostEnergy
Def.armspy.buildTime = 2.1452 * Def.armspy.buildCostEnergy
Def.armst.buildTime = 1.9264 * Def.armst.buildCostEnergy
Def.armstump.buildTime = 1.6632 * Def.armstump.buildCostEnergy
Def.armstump1.buildTime = 1.2284 * Def.armstump1.buildCostEnergy
Def.armsub.buildTime = 2.6568 * Def.armsub.buildCostEnergy
Def.armsubk.buildTime = 1.8740 * Def.armsubk.buildCostEnergy
Def.armsy.buildTime = 7.8065 * Def.armsy.buildCostEnergy
Def.armtabi.buildTime = 0.6204 * Def.armtabi.buildCostEnergy
Def.armtarg.buildTime = 1.2801 * Def.armtarg.buildCostEnergy
Def.armtem.buildTime = 2.3091 * Def.armtem.buildCostEnergy
Def.armtem.featureDefs.dead.damage = 0.6000 * Def.armtem.maxDamage
Def.armtem.featureDefs.dead.description = Def.armtem.name .. [[ Wreckage]]
Def.armtem.featureDefs.dead.metal = 0.8000 * Def.armtem.buildCostMetal
Def.armtem.featureDefs.heap.damage = 0.3600 * Def.armtem.maxDamage
Def.armtem.featureDefs.heap.description = Def.armtem.name .. [[ Heap]]
Def.armtem.featureDefs.heap.metal = 0.6400 * Def.armtem.buildCostMetal
Def.armthovr.buildTime = 2.5625 * Def.armthovr.buildCostEnergy
Def.armthund.buildTime = 0.9415 * Def.armthund.buildCostEnergy
Def.armtick.buildTime = 6.5215 * Def.armtick.buildCostEnergy
Def.armtick.featureDefs.dead.damage = 0.6000 * Def.armtick.maxDamage
Def.armtick.featureDefs.dead.description = Def.armtick.name .. [[ Wreckage]]
Def.armtick.featureDefs.dead.metal = 0.8000 * Def.armtick.buildCostMetal
Def.armtick.featureDefs.heap.damage = 0.3600 * Def.armtick.maxDamage
Def.armtick.featureDefs.heap.description = Def.armtick.name .. [[ Heap]]
Def.armtick.featureDefs.heap.metal = 0.6400 * Def.armtick.buildCostMetal
Def.armtide.buildTime = 5.3107 * Def.armtide.buildCostEnergy
Def.armtigre2.buildTime = 0.8231 * Def.armtigre2.buildCostEnergy
Def.armtigre2.featureDefs.armtigre_heap.damage = 0.6000 * Def.armtigre2.maxDamage
Def.armtigre2.featureDefs.armtigre_heap.description = Def.armtigre2.name .. [[ Heap]]
Def.armtigre2.featureDefs.armtigre_heap.metal = 0.8000 * Def.armtigre2.buildCostMetal
Def.armtigre2.featureDefs.dead.damage = 0.3600 * Def.armtigre2.maxDamage
Def.armtigre2.featureDefs.dead.description = Def.armtigre2.name .. [[ Wreckage]]
Def.armtigre2.featureDefs.dead.metal = 0.6400 * Def.armtigre2.buildCostMetal
Def.armtl.buildTime = 2.0019 * Def.armtl.buildCostEnergy
Def.armtrmph.buildTime = 0.4724 * Def.armtrmph.buildCostEnergy
Def.armtrmph.featureDefs.dead.damage = 0.6000 * Def.armtrmph.maxDamage
Def.armtrmph.featureDefs.dead.description = Def.armtrmph.name .. [[ Wreckage]]
Def.armtrmph.featureDefs.dead.metal = 0.8000 * Def.armtrmph.buildCostMetal
Def.armtship.buildTime = 3.1339 * Def.armtship.buildCostEnergy
Def.armtspd.buildTime = 3.0967 * Def.armtspd.buildCostEnergy
Def.armtspd.featureDefs.dead.damage = 0.6000 * Def.armtspd.maxDamage
Def.armtspd.featureDefs.dead.description = Def.armtspd.name .. [[ Wreckage]]
Def.armtspd.featureDefs.dead.metal = 0.8000 * Def.armtspd.buildCostMetal
Def.armtspd.featureDefs.heap.damage = 0.3600 * Def.armtspd.maxDamage
Def.armtspd.featureDefs.heap.description = Def.armtspd.name .. [[ Heap]]
Def.armtspd.featureDefs.heap.metal = 0.6400 * Def.armtspd.buildCostMetal
Def.armtys.buildTime = 1.2393 * Def.armtys.buildCostEnergy
Def.armuwadves.buildTime = 2.0113 * Def.armuwadves.buildCostEnergy
Def.armuwadvms.buildTime = 1.9433 * Def.armuwadvms.buildCostEnergy
Def.armuwes.buildTime = 2.8978 * Def.armuwes.buildCostEnergy
Def.armuwfus.buildTime = 1.6071 * Def.armuwfus.buildCostEnergy
Def.armuwfus1.buildTime = 1.6393 * Def.armuwfus1.buildCostEnergy
Def.armuwmex.buildTime = 2.7819 * Def.armuwmex.buildCostEnergy
Def.armuwmme.buildTime = 3.8597 * Def.armuwmme.buildCostEnergy
Def.armuwmmm.buildTime = 0.5818 * Def.armuwmmm.buildCostEnergy
Def.armuwms.buildTime = 2.9809 * Def.armuwms.buildCostEnergy
Def.armvader.buildTime = 1.4436 * Def.armvader.buildCostEnergy
Def.armveil.buildTime = 0.5188 * Def.armveil.buildCostEnergy
Def.armvisit.buildTime = 2.7051 * Def.armvisit.buildCostEnergy
Def.armvisit.featureDefs.dead.damage = 0.6000 * Def.armvisit.maxDamage
Def.armvisit.featureDefs.dead.description = Def.armvisit.name .. [[ Wreckage]]
Def.armvisit.featureDefs.dead.metal = 0.8000 * Def.armvisit.buildCostMetal
Def.armvp.buildTime = 3.0378 * Def.armvp.buildCostEnergy
Def.armvulc.buildTime = 2.4845 * Def.armvulc.buildCostEnergy
Def.armvulc1.buildTime = 1.5374 * Def.armvulc1.buildCostEnergy
Def.armvulc2.buildTime = 1.7262 * Def.armvulc2.buildCostEnergy
Def.armwar.buildTime = 1.3003 * Def.armwar.buildCostEnergy
Def.armwin.buildTime = 9.8951 * Def.armwin.buildCostEnergy
Def.armyork.buildTime = 1.5611 * Def.armyork.buildCostEnergy
Def.armzeus.buildTime = 1.2795 * Def.armzeus.buildCostEnergy
Def.armzeus1.buildTime = 1.2795 * Def.armzeus1.buildCostEnergy
Def.aseadragon.buildTime = 1.2564 * Def.aseadragon.buildCostEnergy
Def.ashipyardlvl3.buildTime = 5.0505 * Def.ashipyardlvl3.buildCostEnergy
Def.ashipyardlvl3.featureDefs.dead.damage = 0.6000 * Def.ashipyardlvl3.maxDamage
Def.ashipyardlvl3.featureDefs.dead.description = Def.ashipyardlvl3.name .. [[Aero Wreckage]]
Def.ashipyardlvl3.featureDefs.dead.metal = 0.8000 * Def.ashipyardlvl3.buildCostMetal
Def.aspdbunk.buildTime = 1.4838 * Def.aspdbunk.buildCostEnergy
Def.aspdbunk.featureDefs.dead.damage = 0.6000 * Def.aspdbunk.maxDamage
Def.aspdbunk.featureDefs.dead.metal = 0.8000 * Def.aspdbunk.buildCostMetal
Def.aspdbunk.featureDefs.heap.damage = 0.3600 * Def.aspdbunk.maxDamage
Def.aspdbunk.featureDefs.heap.metal = 0.6400 * Def.aspdbunk.buildCostMetal
Def.asubpen.buildTime = 2.1602 * Def.asubpen.buildCostEnergy
Def.avtr.buildTime = 0.8109 * Def.avtr.buildCostEnergy
Def.avtr.featureDefs.dead.damage = 0.3600 * Def.avtr.maxDamage
Def.avtr.featureDefs.dead.description = Def.avtr.name .. [[ Wreckage]]
Def.avtr.featureDefs.dead.metal = 0.6400 * Def.avtr.buildCostMetal
Def.b52g.buildTime = 0.9065 * Def.b52g.buildCostEnergy
Def.blackdawn.buildTime = 2.2543 * Def.blackdawn.buildCostEnergy
Def.blade.buildTime = 1.5242 * Def.blade.buildCostEnergy
Def.bladew.buildTime = 1.7275 * Def.bladew.buildCostEnergy
Def.blotter.buildTime = 3.2280 * Def.blotter.buildCostEnergy
Def.blotter.featureDefs.dead.damage = 0.6000 * Def.blotter.maxDamage
Def.blotter.featureDefs.dead.description = Def.blotter.name .. [[ Wreckage]]
Def.blotter.featureDefs.dead.metal = 0.8000 * Def.blotter.buildCostMetal
Def.blotter.featureDefs.heap.damage = 0.3600 * Def.blotter.maxDamage
Def.blotter.featureDefs.heap.description = Def.blotter.name .. [[ Heap]]
Def.blotter.featureDefs.heap.metal = 0.6400 * Def.blotter.buildCostMetal
Def.cach.buildTime = 2.3506 * Def.cach.buildCostEnergy
Def.cach.featureDefs.dead.damage = 0.6000 * Def.cach.maxDamage
Def.cach.featureDefs.dead.description = Def.cach.name .. [[ Wreckage]]
Def.cach.featureDefs.dead.metal = 0.8000 * Def.cach.buildCostMetal
Def.cadvmsto.buildTime = 1.5849 * Def.cadvmsto.buildCostEnergy
Def.cadvmsto.featureDefs.dead.damage = 0.6000 * Def.cadvmsto.maxDamage
Def.cadvmsto.featureDefs.dead.description = Def.cadvmsto.name .. [[ Wreckage]]
Def.cadvmsto.featureDefs.dead.metal = 0.8000 * Def.cadvmsto.buildCostMetal
Def.cadvmsto.featureDefs.heap.damage = 0.3600 * Def.cadvmsto.maxDamage
Def.cadvmsto.featureDefs.heap.description = Def.cadvmsto.name .. [[ Heap]]
Def.cadvmsto.featureDefs.heap.metal = 0.6400 * Def.cadvmsto.buildCostMetal
Def.cafus.buildTime = 3.0588 * Def.cafus.buildCostEnergy
Def.cahp.buildTime = 2.0888 * Def.cahp.buildCostEnergy
Def.cahp.featureDefs.dead.damage = 0.6000 * Def.cahp.maxDamage
Def.cahp.featureDefs.dead.metal = 0.8000 * Def.cahp.buildCostMetal
Def.cahp.featureDefs.heap.damage = 0.3600 * Def.cahp.maxDamage
Def.cahp.featureDefs.heap.metal = 0.6400 * Def.cahp.buildCostMetal
Def.cahpns.buildTime = 1.0601 * Def.cahpns.buildCostEnergy
Def.cahpns.featureDefs.dead.damage = 0.6000 * Def.cahpns.maxDamage
Def.cahpns.featureDefs.dead.metal = 0.8000 * Def.cahpns.buildCostMetal
Def.cahpns.featureDefs.heap.damage = 0.3600 * Def.cahpns.maxDamage
Def.cahpns.featureDefs.heap.metal = 0.6400 * Def.cahpns.buildCostMetal
Def.cbrutus.buildTime = 1.6839 * Def.cbrutus.buildCostEnergy
Def.cbrutus.featureDefs.dead.damage = 0.6000 * Def.cbrutus.maxDamage
Def.cbrutus.featureDefs.dead.description = Def.cbrutus.name .. [[ Wreckage]]
Def.cbrutus.featureDefs.dead.metal = 0.8000 * Def.cbrutus.buildCostMetal
Def.cbrutus.featureDefs.heap.damage = 0.3600 * Def.cbrutus.maxDamage
Def.cbrutus.featureDefs.heap.description = Def.cbrutus.name .. [[ Heap]]
Def.cbrutus.featureDefs.heap.metal = 0.6400 * Def.cbrutus.buildCostMetal
Def.cbuilderlvl1.buildTime = 3.8360 * Def.cbuilderlvl1.buildCostEnergy
Def.cbuilderlvl2.buildTime = 1.2630 * Def.cbuilderlvl2.buildCostEnergy
Def.cbuilderlvl2.featureDefs.dead.damage = 0.6000 * Def.cbuilderlvl2.maxDamage
Def.cbuilderlvl2.featureDefs.dead.description = Def.cbuilderlvl2.name .. [[ Wreckage]]
Def.cbuilderlvl2.featureDefs.dead.metal = 0.8000 * Def.cbuilderlvl2.buildCostMetal
Def.cbuilderlvl3.buildTime = 0.6164 * Def.cbuilderlvl3.buildCostEnergy
Def.cbuilderlvl3.featureDefs.dead.damage = 0.6000 * Def.cbuilderlvl3.maxDamage
Def.cbuilderlvl3.featureDefs.dead.metal = 0.8000 * Def.cbuilderlvl3.buildCostMetal
Def.ccovertopscentre.buildTime = 0.0502 * Def.ccovertopscentre.buildCostEnergy
Def.ccovertopscentre.featureDefs.dead.damage = 0.6000 * Def.ccovertopscentre.maxDamage
Def.ccovertopscentre.featureDefs.dead.metal = 0.8000 * Def.ccovertopscentre.buildCostMetal
Def.cdevastator.buildTime = 1.5569 * Def.cdevastator.buildCostEnergy
Def.cdevastator.featureDefs.dead.damage = 0.6000 * Def.cdevastator.maxDamage
Def.cdevastator.featureDefs.dead.metal = 0.8000 * Def.cdevastator.buildCostMetal
Def.cfusionplant.buildTime = 2.2680 * Def.cfusionplant.buildCostEnergy
Def.cfusionplant.featureDefs.dead.damage = 0.6000 * Def.cfusionplant.maxDamage
Def.cfusionplant.featureDefs.dead.metal = 0.8000 * Def.cfusionplant.buildCostMetal
Def.cfusionplant.featureDefs.heap.damage = 0.3600 * Def.cfusionplant.maxDamage
Def.cfusionplant.featureDefs.heap.metal = 0.6400 * Def.cfusionplant.buildCostMetal
Def.champ.buildTime = 1.1622 * Def.champ.buildCostEnergy
Def.champ.featureDefs.dead.damage = 0.6000 * Def.champ.maxDamage
Def.champ.featureDefs.dead.description = Def.champ.name .. [[ Wreckage]]
Def.champ.featureDefs.dead.metal = 0.8000 * Def.champ.buildCostMetal
Def.chopper.buildTime = 1.0797 * Def.chopper.buildCostEnergy
Def.cjuno.buildTime = 1.8303 * Def.cjuno.buildCostEnergy
Def.clb.buildTime = 0.8117 * Def.clb.buildCostEnergy
Def.clb.featureDefs.dead.damage = 0.6000 * Def.clb.maxDamage
Def.clb.featureDefs.dead.description = Def.clb.name .. [[ Wreckage]]
Def.clb.featureDefs.dead.metal = 0.8000 * Def.clb.buildCostMetal
Def.clb.featureDefs.heap.damage = 0.3600 * Def.clb.maxDamage
Def.clb.featureDefs.heap.description = Def.clb.name .. [[ Heap]]
Def.clb.featureDefs.heap.metal = 0.6400 * Def.clb.buildCostMetal
Def.cmetalmakerlvl1.buildTime = 0.8016 * Def.cmetalmakerlvl1.buildCostEnergy
Def.cmetalmakerlvl2.buildTime = 0.1590 * Def.cmetalmakerlvl2.buildCostEnergy
Def.cmetalmakerlvl2.featureDefs.dead.damage = 0.6000 * Def.cmetalmakerlvl2.maxDamage
Def.cmetalmakerlvl2.featureDefs.dead.metal = 0.8000 * Def.cmetalmakerlvl2.buildCostMetal
Def.cmetalmakerlvl2.featureDefs.heap.damage = 0.3600 * Def.cmetalmakerlvl2.maxDamage
Def.cmetalmakerlvl2.featureDefs.heap.metal = 0.6400 * Def.cmetalmakerlvl2.buildCostMetal
Def.cmgeo.buildTime = 1.4043 * Def.cmgeo.buildCostEnergy
Def.cmortor.buildTime = 1.0795 * Def.cmortor.buildCostEnergy
Def.cmortor.featureDefs.dead.damage = 0.6000 * Def.cmortor.maxDamage
Def.cmortor.featureDefs.dead.metal = 0.8000 * Def.cmortor.buildCostMetal
Def.cmortor.featureDefs.heap.damage = 0.3600 * Def.cmortor.maxDamage
Def.cmortor.featureDefs.heap.metal = 0.6400 * Def.cmortor.buildCostMetal
Def.cnanotower.buildTime = 0.7078 * Def.cnanotower.buildCostEnergy
Def.cnanotower.featureDefs.dead.damage = 0.6000 * Def.cnanotower.maxDamage
Def.cnanotower.featureDefs.dead.metal = 0.8000 * Def.cnanotower.buildCostMetal
Def.commando.buildTime = 1.1937 * Def.commando.buildCostEnergy
Def.concealer.buildTime = 3.2937 * Def.concealer.buildCostEnergy
Def.concealer.featureDefs.dead.damage = 0.6000 * Def.concealer.maxDamage
Def.concealer.featureDefs.dead.description = Def.concealer.name .. [[ Wreckage]]
Def.concealer.featureDefs.dead.metal = 0.8000 * Def.concealer.buildCostMetal
Def.concealer.featureDefs.heap.damage = 0.3600 * Def.concealer.maxDamage
Def.concealer.featureDefs.heap.description = Def.concealer.name .. [[ Heap]]
Def.concealer.featureDefs.heap.metal = 0.6400 * Def.concealer.buildCostMetal
Def.consul.buildTime = 1.6864 * Def.consul.buildCostEnergy
Def.consul1.buildTime = 1.2317 * Def.consul1.buildCostEnergy
Def.coraak.buildTime = 1.3039 * Def.coraak.buildCostEnergy
Def.coraap.buildTime = 0.6399 * Def.coraap.buildCostEnergy
Def.coraca.buildTime = 0.9714 * Def.coraca.buildCostEnergy
Def.corack.buildTime = 0.6825 * Def.corack.buildCostEnergy
Def.coracsub.buildTime = 1.5095 * Def.coracsub.buildCostEnergy
Def.coracv.buildTime = 0.3796 * Def.coracv.buildCostEnergy
Def.coradon.buildTime = 2.3125 * Def.coradon.buildCostEnergy
Def.coradon.featureDefs.dead.damage = 0.6000 * Def.coradon.maxDamage
Def.coradon.featureDefs.dead.description = Def.coradon.name .. [[ Wreckage]]
Def.coradon.featureDefs.dead.metal = 0.8000 * Def.coradon.buildCostMetal
Def.coradon.featureDefs.heap.damage = 0.3600 * Def.coradon.maxDamage
Def.coradon.featureDefs.heap.description = Def.coradon.name .. [[ Heap]]
Def.coradon.featureDefs.heap.metal = 0.6400 * Def.coradon.buildCostMetal
Def.coradvsol.buildTime = 1.9195 * Def.coradvsol.buildCostEnergy
Def.corah.buildTime = 0.8210 * Def.corah.buildCostEnergy
Def.corak.buildTime = 1.5484 * Def.corak.buildCostEnergy
Def.corak1.buildTime = 1.5484 * Def.corak1.buildCostEnergy
Def.coralab.buildTime = 0.7434 * Def.coralab.buildCostEnergy
Def.coramph.buildTime = 1.0800 * Def.coramph.buildCostEnergy
Def.corap.buildTime = 5.3582 * Def.corap.buildCostEnergy
Def.corape.buildTime = 3.2161 * Def.corape.buildCostEnergy
Def.corarad.buildTime = 0.6674 * Def.corarad.buildCostEnergy
Def.corarch.buildTime = 1.2361 * Def.corarch.buildCostEnergy
Def.corason.buildTime = 2.7009 * Def.corason.buildCostEnergy
Def.corasp.buildTime = 3.9455 * Def.corasp.buildCostEnergy
Def.corasship.buildTime = 2.5571 * Def.corasship.buildCostEnergy
Def.corasship.featureDefs.dead.damage = 0.6000 * Def.corasship.maxDamage
Def.corasship.featureDefs.dead.description = Def.corasship.name .. [[ Wreckage]]
Def.corasship.featureDefs.dead.metal = 0.8000 * Def.corasship.buildCostMetal
Def.corasy.buildTime = 1.1238 * Def.corasy.buildCostEnergy
Def.coratl.buildTime = 1.2590 * Def.coratl.buildCostEnergy
Def.coravp.buildTime = 0.5084 * Def.coravp.buildCostEnergy
Def.corawac.buildTime = 1.6953 * Def.corawac.buildCostEnergy
Def.corbats.buildTime = 2.7638 * Def.corbats.buildCostEnergy
Def.corbhmth.buildTime = 1.8000 * Def.corbhmth.buildCostEnergy
Def.corbhmth.featureDefs.dead.damage = 0.3600 * Def.corbhmth.maxDamage
Def.corbhmth.featureDefs.dead.description = Def.corbhmth.name .. [[ Wreckage]]
Def.corbhmth.featureDefs.dead.metal = 0.6400 * Def.corbhmth.buildCostMetal
Def.corbhmth1.buildTime = 1.1667 * Def.corbhmth1.buildCostEnergy
Def.corbhmth1.featureDefs.corbhmth_dead.damage = 0.3600 * Def.corbhmth1.maxDamage
Def.corbhmth1.featureDefs.corbhmth_dead.metal = 0.6400 * Def.corbhmth1.buildCostMetal
Def.corblackhy.buildTime = 1.2257 * Def.corblackhy.buildCostEnergy
Def.corboucher.buildTime = 1.9140 * Def.corboucher.buildCostEnergy
Def.corboucher.featureDefs.dead.damage = 0.6000 * Def.corboucher.maxDamage
Def.corboucher.featureDefs.dead.metal = 0.8000 * Def.corboucher.buildCostMetal
Def.corboucher.featureDefs.heap.damage = 0.3600 * Def.corboucher.maxDamage
Def.corboucher.featureDefs.heap.metal = 0.6400 * Def.corboucher.buildCostMetal
Def.corbt.buildTime = 0.7703 * Def.corbt.buildCostEnergy
Def.corbt.featureDefs.dead.damage = 0.3600 * Def.corbt.maxDamage
Def.corbt.featureDefs.dead.description = Def.corbt.name .. [[ Wreckage]]
Def.corbt.featureDefs.dead.metal = 0.6400 * Def.corbt.buildCostMetal
Def.corbt.featureDefs.heap.damage = 0.6000 * Def.corbt.maxDamage
Def.corbt.featureDefs.heap.description = Def.corbt.name .. [[ Heap]]
Def.corbt.featureDefs.heap.metal = 0.8000 * Def.corbt.buildCostMetal
Def.corbuzz.buildTime = 1.8359 * Def.corbuzz.buildCostEnergy
Def.corbuzz1.buildTime = 1.4780 * Def.corbuzz1.buildCostEnergy
Def.corbuzz2.buildTime = 1.6266 * Def.corbuzz2.buildCostEnergy
Def.corca.buildTime = 2.0275 * Def.corca.buildCostEnergy
Def.corcan.buildTime = 1.3453 * Def.corcan.buildCostEnergy
Def.corcarry.buildTime = 1.1413 * Def.corcarry.buildCostEnergy
Def.corch.buildTime = 1.6514 * Def.corch.buildCostEnergy
Def.corck.buildTime = 2.1893 * Def.corck.buildCostEnergy
Def.corcom.buildTime = 30.0000 * Def.corcom.buildCostEnergy
Def.corcom1.buildTime = 20.0000 * Def.corcom1.buildCostEnergy
Def.corcom3.buildTime = 35.2941 * Def.corcom3.buildCostEnergy
Def.corcom5.buildTime = 3.0000 * Def.corcom5.buildCostEnergy
Def.corcom6.buildTime = 0.8125 * Def.corcom6.buildCostEnergy
Def.corcom7.buildTime = 0.3500 * Def.corcom7.buildCostEnergy
Def.corcrab.buildTime = 1.5535 * Def.corcrab.buildCostEnergy
Def.corcrab.featureDefs.dead.damage = 0.6000 * Def.corcrab.maxDamage
Def.corcrab.featureDefs.dead.metal = 0.8000 * Def.corcrab.buildCostMetal
Def.corcrab.featureDefs.heap.damage = 0.3600 * Def.corcrab.maxDamage
Def.corcrab.featureDefs.heap.metal = 0.6400 * Def.corcrab.buildCostMetal
Def.corcrash.buildTime = 1.7257 * Def.corcrash.buildCostEnergy
Def.corcrus.buildTime = 1.4722 * Def.corcrus.buildCostEnergy
Def.corcrw.buildTime = 2.1183 * Def.corcrw.buildCostEnergy
Def.corcs.buildTime = 2.3314 * Def.corcs.buildCostEnergy
Def.corcsa.buildTime = 2.1149 * Def.corcsa.buildCostEnergy
Def.corcut.buildTime = 2.0298 * Def.corcut.buildCostEnergy
Def.corcv.buildTime = 2.1021 * Def.corcv.buildCostEnergy
Def.cordecom.buildTime = 2.2293 * Def.cordecom.buildCostEnergy
Def.cordem.buildTime = 0.7158 * Def.cordem.buildCostEnergy
Def.cordem.featureDefs.dead.damage = 0.6000 * Def.cordem.maxDamage
Def.cordem.featureDefs.dead.description = Def.cordem.name .. [[ Wreckage]]
Def.cordem.featureDefs.dead.metal = 0.8000 * Def.cordem.buildCostMetal
Def.cordem.featureDefs.heap.damage = 0.3600 * Def.cordem.maxDamage
Def.cordem.featureDefs.heap.description = Def.cordem.name .. [[ Heap]]
Def.cordem.featureDefs.heap.metal = 0.6400 * Def.cordem.buildCostMetal
Def.cordl.buildTime = 1.8291 * Def.cordl.buildCostEnergy
Def.cordoom.buildTime = 1.2976 * Def.cordoom.buildCostEnergy
Def.cordoom1.buildTime = 0.7913 * Def.cordoom1.buildCostEnergy
Def.cordrag.buildTime = 1.7000 * Def.cordrag.buildCostEnergy
Def.cordrag1.buildTime = 1.5093 * Def.cordrag1.buildCostEnergy
Def.core_immolator.buildTime = 0.3812 * Def.core_immolator.buildCostEnergy
Def.core_immolator.featureDefs.dead.damage = 0.6000 * Def.core_immolator.maxDamage
Def.core_immolator.featureDefs.dead.description = Def.core_immolator.name .. [[ Wreckage]]
Def.core_immolator.featureDefs.dead.metal = 0.8000 * Def.core_immolator.buildCostMetal
Def.core_immolator.featureDefs.heap.damage = 0.3600 * Def.core_immolator.maxDamage
Def.core_immolator.featureDefs.heap.description = Def.core_immolator.name .. [[ Heap]]
Def.core_immolator.featureDefs.heap.metal = 0.6400 * Def.core_immolator.buildCostMetal
Def.core_intimidator.buildTime = 1.7954 * Def.core_intimidator.buildCostEnergy
Def.core_wind_generator.buildTime = 3.2256 * Def.core_wind_generator.buildCostEnergy
Def.core_wind_generator.featureDefs.dead.damage = 0.6000 * Def.core_wind_generator.maxDamage
Def.core_wind_generator.featureDefs.dead.metal = 0.8000 * Def.core_wind_generator.buildCostMetal
Def.core_wind_generator.featureDefs.heap.damage = 0.3600 * Def.core_wind_generator.maxDamage
Def.core_wind_generator.featureDefs.heap.metal = 0.6400 * Def.core_wind_generator.buildCostMetal
Def.corech18.buildTime = 5.0000 * Def.corech18.buildCostEnergy
Def.corech21.buildTime = 5.0000 * Def.corech21.buildCostEnergy
Def.corech3.buildTime = 0.7813 * Def.corech3.buildCostEnergy
Def.coredauber.buildTime = 1.9758 * Def.coredauber.buildCostEnergy
Def.coredauber.featureDefs.dead.damage = 0.6000 * Def.coredauber.maxDamage
Def.coredauber.featureDefs.dead.description = Def.coredauber.name .. [[ Wreckage]]
Def.coredauber.featureDefs.dead.metal = 0.8000 * Def.coredauber.buildCostMetal
Def.corehpad.buildTime = 1.1372 * Def.corehpad.buildCostEnergy
Def.corehpad.featureDefs.dead.damage = 0.6000 * Def.corehpad.maxDamage
Def.corehpad.featureDefs.dead.metal = 0.8000 * Def.corehpad.buildCostMetal
Def.corehpad.featureDefs.heap.damage = 0.3600 * Def.corehpad.maxDamage
Def.corehpad.featureDefs.heap.metal = 0.6400 * Def.corehpad.buildCostMetal
Def.corekaty.buildTime = 2.2586 * Def.corekaty.buildCostEnergy
Def.corekaty.featureDefs.dead.damage = 0.6000 * Def.corekaty.maxDamage
Def.corekaty.featureDefs.dead.description = Def.corekaty.name .. [[ Wreckage]]
Def.corekaty.featureDefs.dead.metal = 0.8000 * Def.corekaty.buildCostMetal
Def.corekaty.featureDefs.heap.damage = 0.3600 * Def.corekaty.maxDamage
Def.corekaty.featureDefs.heap.description = Def.corekaty.name .. [[ Heap]]
Def.corekaty.featureDefs.heap.metal = 0.6400 * Def.corekaty.buildCostMetal
Def.coremech.buildTime = 2.0470 * Def.coremech.buildCostEnergy
Def.coremech.featureDefs.heap.damage = 0.3600 * Def.coremech.maxDamage
Def.coremech.featureDefs.heap.description = Def.coremech.name .. [[ Heap]]
Def.coremech.featureDefs.heap.metal = 0.6400 * Def.coremech.buildCostMetal
Def.corenaa.buildTime = 0.9741 * Def.corenaa.buildCostEnergy
Def.corerad.buildTime = 2.2880 * Def.corerad.buildCostEnergy
Def.corerad1.buildTime = 2.2880 * Def.corerad1.buildCostEnergy
Def.corerex.buildTime = 0.6778 * Def.corerex.buildCostEnergy
Def.corerex.featureDefs.dead.damage = 0.6000 * Def.corerex.maxDamage
Def.corerex.featureDefs.dead.metal = 0.8000 * Def.corerex.buildCostMetal
Def.corerex.featureDefs.heap.damage = 0.3600 * Def.corerex.maxDamage
Def.corerex.featureDefs.heap.metal = 0.6400 * Def.corerex.buildCostMetal
Def.corestor.buildTime = 2.3508 * Def.corestor.buildCostEnergy
Def.coresupp.buildTime = 3.4833 * Def.coresupp.buildCostEnergy
Def.coresy.buildTime = 0.5919 * Def.coresy.buildCostEnergy
Def.coresy.featureDefs.dead.damage = 0.3600 * Def.coresy.maxDamage
Def.coresy.featureDefs.dead.description = Def.coresy.name .. [[ Wreckage]]
Def.coresy.featureDefs.dead.metal = 0.6400 * Def.coresy.buildCostMetal
Def.coreter.buildTime = 3.6448 * Def.coreter.buildCostEnergy
Def.corevp.buildTime = 3.2469 * Def.corevp.buildCostEnergy
Def.corevp.featureDefs.dead.damage = 0.6000 * Def.corevp.maxDamage
Def.corevp.featureDefs.dead.description = Def.corevp.name .. [[ Wreckage]]
Def.corevp.featureDefs.dead.metal = 0.8000 * Def.corevp.buildCostMetal
Def.corevp.featureDefs.heap.damage = 0.3600 * Def.corevp.maxDamage
Def.corevp.featureDefs.heap.description = Def.corevp.name .. [[ Heap]]
Def.corevp.featureDefs.heap.metal = 0.6400 * Def.corevp.buildCostMetal
Def.corexp.buildTime = 1.2032 * Def.corexp.buildCostEnergy
Def.coreyes.buildTime = 1.8750 * Def.coreyes.buildCostEnergy
Def.corfalc.buildTime = 4.7970 * Def.corfalc.buildCostEnergy
Def.corfast.buildTime = 1.8108 * Def.corfast.buildCostEnergy
Def.corfast1.buildTime = 1.8108 * Def.corfast1.buildCostEnergy
Def.corfatf.buildTime = 1.4551 * Def.corfatf.buildCostEnergy
Def.corfav.buildTime = 4.3125 * Def.corfav.buildCostEnergy
Def.corfdrag.buildTime = 1.5873 * Def.corfdrag.buildCostEnergy
Def.corfhlt.buildTime = 2.1767 * Def.corfhlt.buildCostEnergy
Def.corfhp.buildTime = 3.5059 * Def.corfhp.buildCostEnergy
Def.corfink.buildTime = 1.5749 * Def.corfink.buildCostEnergy
Def.corflak.buildTime = 0.5158 * Def.corflak.buildCostEnergy
Def.corflshd.buildTime = 2.1162 * Def.corflshd.buildCostEnergy
Def.corflu.buildTime = 0.5960 * Def.corflu.buildCostEnergy
Def.corfmd.buildTime = 1.3406 * Def.corfmd.buildCostEnergy
Def.corfmd1.buildTime = 0.9615 * Def.corfmd1.buildCostEnergy
Def.corfmd2.buildTime = 0.6950 * Def.corfmd2.buildCostEnergy
Def.corfmine3.buildTime = 0.1000 * Def.corfmine3.buildCostEnergy
Def.corfmkr.buildTime = 1.0979 * Def.corfmkr.buildCostEnergy
Def.corfort.buildTime = 1.3235 * Def.corfort.buildCostEnergy
Def.corfrad.buildTime = 1.6917 * Def.corfrad.buildCostEnergy
Def.corfrog.buildTime = 1.8243 * Def.corfrog.buildCostEnergy
Def.corfrog.featureDefs.corsent_dead.damage = 0.3600 * Def.corfrog.maxDamage
Def.corfrog.featureDefs.corsent_dead.metal = 0.6400 * Def.corfrog.buildCostMetal
Def.corfrt.buildTime = 2.2362 * Def.corfrt.buildCostEnergy
Def.corfsilo.buildTime = 0.5481 * Def.corfsilo.buildCostEnergy
Def.corfsilo.featureDefs.dead.damage = 0.6000 * Def.corfsilo.maxDamage
Def.corfsilo.featureDefs.dead.description = Def.corfsilo.name .. [[ Wreckage]]
Def.corfsilo.featureDefs.dead.metal = 0.8000 * Def.corfsilo.buildCostMetal
Def.corfsilo.featureDefs.heap.damage = 0.3600 * Def.corfsilo.maxDamage
Def.corfsilo.featureDefs.heap.description = Def.corfsilo.name .. [[ Heap]]
Def.corfsilo.featureDefs.heap.metal = 0.6400 * Def.corfsilo.buildCostMetal
Def.corfus.buildTime = 3.1086 * Def.corfus.buildCostEnergy
Def.corgala.buildTime = 0.5000 * Def.corgala.buildCostEnergy
Def.corgant.buildTime = 1.1503 * Def.corgant.buildCostEnergy
Def.corgant1.buildTime = 1.0340 * Def.corgant1.buildCostEnergy
Def.corgarp.buildTime = 1.2704 * Def.corgarp.buildCostEnergy
Def.corgate.buildTime = 0.8956 * Def.corgate.buildCostEnergy
Def.corgate1.buildTime = 2.9543 * Def.corgate1.buildCostEnergy
Def.corgate2.buildTime = 9.6457 * Def.corgate2.buildCostEnergy
Def.corgator.buildTime = 1.6900 * Def.corgator.buildCostEnergy
Def.corgator1.buildTime = 1.2212 * Def.corgator1.buildCostEnergy
Def.corgeo.buildTime = 2.0870 * Def.corgeo.buildCostEnergy
Def.corgeo.featureDefs.dead.damage = 0.3600 * Def.corgeo.maxDamage
Def.corgeo.featureDefs.dead.description = Def.corgeo.name .. [[ Wreckage]]
Def.corgeo.featureDefs.dead.metal = 0.6400 * Def.corgeo.buildCostMetal
Def.corgfbt.buildTime = 0.9540 * Def.corgfbt.buildCostEnergy
Def.corgfbt.featureDefs.heap.damage = 0.3600 * Def.corgfbt.maxDamage
Def.corgfbt.featureDefs.heap.metal = 0.6400 * Def.corgfbt.buildCostMetal
Def.corgol.buildTime = 1.3133 * Def.corgol.buildCostEnergy
Def.corgol1.buildTime = 1.5781 * Def.corgol1.buildCostEnergy
Def.corgripn.buildTime = 1.8650 * Def.corgripn.buildCostEnergy
Def.corhcar.buildTime = 0.5870 * Def.corhcar.buildCostEnergy
Def.corhcar.featureDefs.dead.damage = 0.6000 * Def.corhcar.maxDamage
Def.corhcar.featureDefs.dead.description = Def.corhcar.name .. [[ Wreckage]]
Def.corhcar.featureDefs.dead.metal = 0.8000 * Def.corhcar.buildCostMetal
Def.corhelo.buildTime = 0.6789 * Def.corhelo.buildCostEnergy
Def.corhevsenan.buildTime = 1.7090 * Def.corhevsenan.buildCostEnergy
Def.corhlt.buildTime = 2.1657 * Def.corhlt.buildCostEnergy
Def.corhlt1.buildTime = 2.1250 * Def.corhlt1.buildCostEnergy
Def.corhover3g.buildTime = 2.8562 * Def.corhover3g.buildCostEnergy
Def.corhover3g.featureDefs.dead.damage = 0.3600 * Def.corhover3g.maxDamage
Def.corhover3g.featureDefs.dead.description = Def.corhover3g.name .. [[ Wreckage]]
Def.corhover3g.featureDefs.dead.metal = 0.6400 * Def.corhover3g.buildCostMetal
Def.corhp.buildTime = 3.5063 * Def.corhp.buildCostEnergy
Def.corhrk.buildTime = 1.1968 * Def.corhrk.buildCostEnergy
Def.corhunt.buildTime = 1.4814 * Def.corhunt.buildCostEnergy
Def.corhurc.buildTime = 2.3990 * Def.corhurc.buildCostEnergy
Def.corint.buildTime = 1.4913 * Def.corint.buildCostEnergy
Def.corint1.buildTime = 1.2670 * Def.corint1.buildCostEnergy
Def.corjamt.buildTime = 0.9553 * Def.corjamt.buildCostEnergy
Def.corjeag.buildTime = 2.3930 * Def.corjeag.buildCostEnergy
Def.corjeag.featureDefs.dead.damage = 0.6000 * Def.corjeag.maxDamage
Def.corjeag.featureDefs.dead.description = Def.corjeag.name .. [[ Wreckage]]
Def.corjeag.featureDefs.dead.metal = 0.8000 * Def.corjeag.buildCostMetal
Def.corjurgen.buildTime = 0.8670 * Def.corjurgen.buildCostEnergy
Def.corjurgen.featureDefs.dead.damage = 0.6000 * Def.corjurgen.maxDamage
Def.corjurgen.featureDefs.dead.description = Def.corjurgen.name .. [[ Wreckage]]
Def.corjurgen.featureDefs.dead.metal = 0.8000 * Def.corjurgen.buildCostMetal
Def.corjurgen.featureDefs.heap.damage = 0.3600 * Def.corjurgen.maxDamage
Def.corjurgen.featureDefs.heap.description = Def.corjurgen.name .. [[ Heap]]
Def.corjurgen.featureDefs.heap.metal = 0.6400 * Def.corjurgen.buildCostMetal
Def.corkarg.buildTime = 0.8612 * Def.corkarg.buildCostEnergy
Def.corkarg1.buildTime = 1.0473 * Def.corkarg1.buildCostEnergy
Def.corkrog.buildTime = 1.1574 * Def.corkrog.buildCostEnergy
Def.corkrog1.buildTime = 0.7559 * Def.corkrog1.buildCostEnergy
Def.corlab.buildTime = 4.4000 * Def.corlab.buildCostEnergy
Def.corlevlr.buildTime = 1.2606 * Def.corlevlr.buildCostEnergy
Def.corlevlr1.buildTime = 0.9441 * Def.corlevlr1.buildCostEnergy
Def.corllt.buildTime = 4.1779 * Def.corllt.buildCostEnergy
Def.corllt1.buildTime = 4.1538 * Def.corllt1.buildCostEnergy
Def.cormabm.buildTime = 1.0447 * Def.cormabm.buildCostEnergy
Def.cormabm1.buildTime = 0.5942 * Def.cormabm1.buildCostEnergy
Def.cormachn.buildTime = 3.2760 * Def.cormachn.buildCostEnergy
Def.cormakr.buildTime = 0.9360 * Def.cormakr.buildCostEnergy
Def.cormart.buildTime = 0.7757 * Def.cormart.buildCostEnergy
Def.cormas.buildTime = 1.0690 * Def.cormas.buildCostEnergy
Def.cormatch.buildTime = 2.5921 * Def.cormatch.buildCostEnergy
Def.cormatch.featureDefs.corsnap_dead.damage = 0.3600 * Def.cormatch.maxDamage
Def.cormatch.featureDefs.corsnap_dead.metal = 0.6400 * Def.cormatch.buildCostMetal
Def.cormaw.buildTime = 3.1296 * Def.cormaw.buildCostEnergy
Def.cormddm.buildTime = 2.3438 * Def.cormddm.buildCostEnergy
Def.cormddm.featureDefs.dead.damage = 0.6000 * Def.cormddm.maxDamage
Def.cormddm.featureDefs.dead.description = Def.cormddm.name .. [[ Wreckage]]
Def.cormddm.featureDefs.dead.metal = 0.8000 * Def.cormddm.buildCostMetal
Def.cormddm.featureDefs.heap.damage = 0.3600 * Def.cormddm.maxDamage
Def.cormddm.featureDefs.heap.description = Def.cormddm.name .. [[ Heap]]
Def.cormddm.featureDefs.heap.metal = 0.6400 * Def.cormddm.buildCostMetal
Def.cormena.buildTime = 2.1103 * Def.cormena.buildCostEnergy
Def.cormena.featureDefs.corgol_heap.damage = 0.6000 * Def.cormena.maxDamage
Def.cormena.featureDefs.corgol_heap.metal = 0.8000 * Def.cormena.buildCostMetal
Def.cormena.featureDefs.dead.damage = 0.3600 * Def.cormena.maxDamage
Def.cormena.featureDefs.dead.description = Def.cormena.name .. [[ Wreckage]]
Def.cormena.featureDefs.dead.metal = 0.6400 * Def.cormena.buildCostMetal
Def.cormex.buildTime = 3.6459 * Def.cormex.buildCostEnergy
Def.cormex1.buildTime = 0.3399 * Def.cormex1.buildCostEnergy
Def.cormexp.buildTime = 2.6813 * Def.cormexp.buildCostEnergy
Def.cormh.buildTime = 1.1519 * Def.cormh.buildCostEnergy
Def.cormine1.buildTime = 0.2000 * Def.cormine1.buildCostEnergy
Def.cormine2.buildTime = 0.1000 * Def.cormine2.buildCostEnergy
Def.cormine3.buildTime = 0.1000 * Def.cormine3.buildCostEnergy
Def.cormist.buildTime = 1.4079 * Def.cormist.buildCostEnergy
Def.cormist1.buildTime = 1.2150 * Def.cormist1.buildCostEnergy
Def.cormls.buildTime = 1.3716 * Def.cormls.buildCostEnergy
Def.cormlv.buildTime = 2.9910 * Def.cormlv.buildCostEnergy
Def.cormmkr.buildTime = 0.8975 * Def.cormmkr.buildCostEnergy
Def.cormoho.buildTime = 1.8399 * Def.cormoho.buildCostEnergy
Def.cormonsta.buildTime = 2.9386 * Def.cormonsta.buildCostEnergy
Def.cormonsta.featureDefs.dead.damage = 0.6000 * Def.cormonsta.maxDamage
Def.cormonsta.featureDefs.dead.description = Def.cormonsta.name .. [[ Wreckage]]
Def.cormonsta.featureDefs.dead.metal = 0.8000 * Def.cormonsta.buildCostMetal
Def.cormonsta.featureDefs.heap.damage = 0.3600 * Def.cormonsta.maxDamage
Def.cormonsta.featureDefs.heap.description = Def.cormonsta.name .. [[ Heap]]
Def.cormonsta.featureDefs.heap.metal = 0.6400 * Def.cormonsta.buildCostMetal
Def.cormort.buildTime = 2.4886 * Def.cormort.buildCostEnergy
Def.cormship.buildTime = 2.2981 * Def.cormship.buildCostEnergy
Def.cormstor.buildTime = 5.3182 * Def.cormstor.buildCostEnergy
Def.cormuskrat.buildTime = 2.1343 * Def.cormuskrat.buildCostEnergy
Def.cornanotc.buildTime = 0.5888 * Def.cornanotc.buildCostEnergy
Def.cornecro.buildTime = 1.7143 * Def.cornecro.buildCostEnergy
Def.corparrow.buildTime = 0.8260 * Def.corparrow.buildCostEnergy
Def.corplat.buildTime = 0.5112 * Def.corplat.buildCostEnergy
Def.corpre.buildTime = 0.1787 * Def.corpre.buildCostEnergy
Def.corpre.featureDefs.dead.damage = 0.6000 * Def.corpre.maxDamage
Def.corpre.featureDefs.dead.description = Def.corpre.name .. [[ Wreckage]]
Def.corpre.featureDefs.dead.metal = 0.8000 * Def.corpre.buildCostMetal
Def.corpre.featureDefs.heap.damage = 0.3600 * Def.corpre.maxDamage
Def.corpre.featureDefs.heap.description = Def.corpre.name .. [[ Heap]]
Def.corpre.featureDefs.heap.metal = 0.6400 * Def.corpre.buildCostMetal
Def.corprot.buildTime = 2.3750 * Def.corprot.buildCostEnergy
Def.corprot.featureDefs.dead.damage = 0.6000 * Def.corprot.maxDamage
Def.corprot.featureDefs.dead.description = Def.corprot.name .. [[ Wreckage]]
Def.corprot.featureDefs.dead.metal = 0.8000 * Def.corprot.buildCostMetal
Def.corprot.featureDefs.heap.damage = 0.3600 * Def.corprot.maxDamage
Def.corprot.featureDefs.heap.description = Def.corprot.name .. [[ Heap]]
Def.corprot.featureDefs.heap.metal = 0.6400 * Def.corprot.buildCostMetal
Def.corpt.buildTime = 2.0469 * Def.corpt.buildCostEnergy
Def.corpun.buildTime = 1.5310 * Def.corpun.buildCostEnergy
Def.corpyro.buildTime = 1.8063 * Def.corpyro.buildCostEnergy
Def.corrad.buildTime = 1.8950 * Def.corrad.buildCostEnergy
Def.corrad1.buildTime = 1.8950 * Def.corrad1.buildCostEnergy
Def.corraid.buildTime = 1.4926 * Def.corraid.buildCostEnergy
Def.corraid1.buildTime = 1.1833 * Def.corraid1.buildCostEnergy
Def.correap.buildTime = 1.1923 * Def.correap.buildCostEnergy
Def.correcl.buildTime = 1.4456 * Def.correcl.buildCostEnergy
Def.corrl.buildTime = 2.1727 * Def.corrl.buildCostEnergy
Def.corrl1.buildTime = 2.1727 * Def.corrl1.buildCostEnergy
Def.corroach.buildTime = 1.4438 * Def.corroach.buildCostEnergy
Def.corroy.buildTime = 2.3224 * Def.corroy.buildCostEnergy
Def.corsb.buildTime = 1.1368 * Def.corsb.buildCostEnergy
Def.corsd.buildTime = 1.8788 * Def.corsd.buildCostEnergy
Def.corseal.buildTime = 0.7294 * Def.corseal.buildCostEnergy
Def.corseap.buildTime = 2.0189 * Def.corseap.buildCostEnergy
Def.corsent.buildTime = 1.5792 * Def.corsent.buildCostEnergy
Def.corsfig.buildTime = 1.9435 * Def.corsfig.buildCostEnergy
Def.corsh.buildTime = 2.8346 * Def.corsh.buildCostEnergy
Def.corshad.buildTime = 0.9033 * Def.corshad.buildCostEnergy
Def.corshark.buildTime = 1.6797 * Def.corshark.buildCostEnergy
Def.corshroud.buildTime = 0.5131 * Def.corshroud.buildCostEnergy
Def.corsilo.buildTime = 2.3375 * Def.corsilo.buildCostEnergy
Def.corsilo1.buildTime = 1.3178 * Def.corsilo1.buildCostEnergy
Def.corsjam.buildTime = 3.1167 * Def.corsjam.buildCostEnergy
Def.corsktl.buildTime = 0.6866 * Def.corsktl.buildCostEnergy
Def.corsnap.buildTime = 1.2205 * Def.corsnap.buildCostEnergy
Def.corsolar.buildTime = 1.#INF * Def.corsolar.buildCostEnergy
Def.corsonar.buildTime = 2.2556 * Def.corsonar.buildCostEnergy
Def.corspec.buildTime = 3.7433 * Def.corspec.buildCostEnergy
Def.corspec.featureDefs.dead.damage = 0.3600 * Def.corspec.maxDamage
Def.corspec.featureDefs.dead.description = Def.corspec.name .. [[ Wreckage]]
Def.corspec.featureDefs.dead.metal = 0.6400 * Def.corspec.buildCostMetal
Def.corspy.buildTime = 1.9426 * Def.corspy.buildCostEnergy
Def.corssub.buildTime = 1.9269 * Def.corssub.buildCostEnergy
Def.corstorm.buildTime = 2.0188 * Def.corstorm.buildCostEnergy
Def.corstorm1.buildTime = 1.7733 * Def.corstorm1.buildCostEnergy
Def.corsub.buildTime = 2.4933 * Def.corsub.buildCostEnergy
return lowerkeys(Def)
