local Def = {
	corthud = {
		acceleration = 0.113,
		badTargetCategory = [[VTOL]],
		bmcode = 1,
		brakeRate = 0.225,
		buildCostEnergy = 1061,
		buildCostMetal = 132,
		buildPic = [[CORTHUD.png]],
		buildTime = 1971,
		builder = false,
		canAttack = true,
		canGuard = true,
		canMove = true,
		canPatrol = true,
		canstop = 1,
		category = [[ALL MOBILE NOTVTOL NOTSUB NOTDEFENSE SMALL NOTSUBNOTSHIP NOTHOVERNOTVTOL]],
		corpse = [[DEAD]],
		defaultmissiontype = [[Standby]],
		description = [[Light Plasma Kbot]],
		energyMake = 0.6,
		energyStorage = 0,
		energyUse = 0.6,
		explodeAs = [[BIG_UNITEX]],
		featureDefs = {
			DEAD = {
				blocking = true,
				category = [[corpses]],
				damage = nil,
				description = nil,
				energy = 0,
				featureDead = [[HEAP]],
				featurereclamate = [[SMUDGE01]],
				footprintX = 2,
				footprintZ = 2,
				height = 20,
				hitdensity = 100,
				metal = nil,
				object = [[CORTHUD_DEAD]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
			HEAP = {
				blocking = false,
				category = [[heaps]],
				damage = nil,
				description = nil,
				energy = 0,
				featurereclamate = [[SMUDGE01]],
				footprintX = 2,
				footprintZ = 2,
				height = 4,
				hitdensity = 100,
				metal = nil,
				object = [[2X2D]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
		},
		firestandorders = 1,
		footprintX = 2,
		footprintZ = 2,
		idleAutoHeal = 5,
		idleTime = 1800,
		maneuverleashlength = 640,
		mass = 300,
		maxDamage = 900,
		maxSlope = 14,
		maxVelocity = 1.5,
		maxWaterDepth = 12,
		metalStorage = 0,
		mobilestandorders = 1,
		movementClass = [[KBOT2]],
		name = [[Thud]],
		noAutoFire = false,
		noChaseCategory = [[VTOL SUB]],
		objectName = [[CORTHUD]],
		seismicSignature = 0,
		selfDestructAs = [[BIG_UNIT]],
		side = [[CORE]],
		sightDistance = 380,
		smoothAnim = true,
		sounds = {
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[cantdo4]],
			},
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			ok = {
				[1] = [[kbcormov]],
			},
			select = {
				[1] = [[kbcorsel]],
			},
			underattack = [[warning1]],
		},
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 2,
		turnRate = 1099,
		unitname = [[corthud]],
		upright = true,
		weaponDefs = {
			ARM_HAM = {
				areaOfEffect = 36,
				ballistic = true,
				craterBoost = 0,
				craterMult = 0,
				damage = {
					default = 104,
					gunships = 21,
					hgunships = 21,
					l1bombers = 21,
					l1fighters = 21,
					l1subs = 5,
					l2bombers = 21,
					l2fighters = 21,
					l2subs = 5,
					l3subs = 5,
					vradar = 21,
					vtol = 21,
					vtrans = 21,
				},
				explosionGenerator = [[custom:LIGHT_PLASMA]],
				gravityaffected = [[true]],
				impulseBoost = 0.123,
				impulseFactor = 0.123,
				minbarrelangle = -35,
				name = [[PlasmaCannon]],
				noSelfDamage = true,
				predictBoost = 0.4,
				range = 380,
				reloadtime = 1.75,
				renderType = 4,
				soundHit = [[xplomed3]],
				soundStart = [[cannon1]],
				startsmoke = 1,
				turret = true,
				weaponType = [[Cannon]],
				weaponVelocity = 286,
			},
		},
		weapons = {
			[1] = {
				badTargetCategory = [[VTOL]],
				def = [[ARM_HAM]],
			},
		},
		workerTime = 0,
	},
}
Def.corthud.featureDefs.DEAD.damage = 0.6000 * Def.corthud.maxDamage
Def.corthud.featureDefs.DEAD.description = Def.corthud.name .. [[ Wreckage]]
Def.corthud.featureDefs.DEAD.metal = 0.8000 * Def.corthud.buildCostMetal
Def.corthud.featureDefs.HEAP.damage = 0.3600 * Def.corthud.maxDamage
Def.corthud.featureDefs.HEAP.description = Def.corthud.name .. [[ Heap]]
Def.corthud.featureDefs.HEAP.metal = 0.6400 * Def.corthud.buildCostMetal
return lowerkeys(Def)
