return {
	cortigre = {
		acceleration = 0.09,
		brakerate = 0.03,
		buildcostenergy = 106320,
		buildcostmetal = 5802,
		builder = false,
		buildpic = "cortigre.dds",
		buildtime = 75000,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL LARGE MOBILE SURFACE UNDERWATER",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Amphibious Assault Tank",
		downloadable = 1,
		explodeas = "CRAWL_BLASTSML",
		firestandorders = 1,
		footprintx = 4,
		footprintz = 4,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 45,
		maneuverleashlength = 640,
		mass = 5902,
		maxdamage = 20250,
		maxslope = 12,
		maxvelocity = 1.45,
		maxwaterdepth = 255,
		mobilestandorders = 1,
		movementclass = "ATANK4",
		name = "Black Tiger",
		noautofire = false,
		objectname = "core/cortigre.s3o",
		radaremitheight = 44,
		selfdestructas = "CRAWL_BLAST",
		sightdistance = 500,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0.726,
		turnrate = 340,
		unitname = "cortigre",
		customparams = {
			buildpic = "cortigre.dds",
			faction = "CORE",
			normaltex = "unittextures/core_normals.dds",
		},
		featuredefs = {
			armtigre_heap = {
				blocking = false,
				damage = 13203,
				description = "Black Tiger Debris",
				footprintx = 4,
				footprintz = 4,
				metal = 2360,
				object = "4x4a.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			dead = {
				blocking = true,
				damage = 10562,
				description = "Black Tiger Wreckage",
				featuredead = "armtigre_heap",
				footprintx = 4,
				footprintz = 6,
				metal = 4425,
				object = "core/cortigre_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			explosiongenerators = {
				"custom:goliathflare",
			},
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"krogok1",
			},
			select = {
				"krogsel1",
			},
		},
		weapondefs = {
			tigre_weapon = {
				areaofeffect = 256,
				avoidfeature = false,
				cegtag = "Trail_cannon_med",
				craterareaofeffect = 256,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:flash192_fakelight",
				gravityaffected = "TRUE",
				impulseboost = 0,
				impulsefactor = 0,
				name = "HeavyCannon",
				nogap = 1,
				noselfdamage = true,
				range = 700,
				reloadtime = 2.5,
				separation = 0.45,
				size = 2.2,
				sizedecay = -0.15,
				soundhitdry = "xplomed4",
				soundhitwet = "splslrg",
				soundhitwetvolume = 0.6,
				soundstart = "cannhvy2",
				stages = 20,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 325,
				damage = {
					commanders = 700,
					default = 1400,
					subs = 5,
				},
				tracks = false,
			},
			rave_missile = {
				acceleration = 0.3,
				areaofeffect = 48,
				avoidfeature = false,
				cegtag = "titan_trail",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:Explosion_Medium_VLight",
				firestarter = 70,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				model = "titan_missile.s3o",
				name = "Mini-Rocket",
				noselfdamage = true,
				proximitypriority = -1,
				range = 900,
				reloadtime = 2,
				smoketrail = true,
				soundhitdry = "xplosml2",
				soundhitwet = "splshbig",
				soundhitwetvolume = 0.6,
				soundstart = "rocklit1",
				startvelocity = 220,
				targetable = 16,
				texture1 = "null",
				texture2 = "null",
				texture3 = "null",
				texture4 = "null",
				tolerance = 9000,
				tracks = false,
				turnrate = 35000,
				weaponacceleration = 150,
				weapontimer = 0.6,
				weapontype = "StarburstLauncher",
				weaponvelocity = 2100,
				damage = {
					default = 150,
					subs = 5,
				},
			},
		},
		weapons = {
			{
				badtargetcategory = "MINOR",
				def = "TIGRE_WEAPON",
				onlytargetcategory = "SURFACE",
			},
			[3] = {
				def = "RAVE_MISSILE",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}