local Def = {
	cortl = {
		acceleration = 0,
		activateWhenBuilt = true,
		badTargetCategory = [[HOVER NOTSHIP]],
		bmcode = 0,
		brakeRate = 0,
		buildAngle = 16384,
		buildCostEnergy = 2058,
		buildCostMetal = 316,
		buildPic = [[CORTL.png]],
		buildTime = 4233,
		builder = false,
		canAttack = true,
		canstop = 1,
		category = [[ALL NOTMOBILE NOTVTOL NOTSUB NOTSUBNOTSHIP NOTHOVERNOTVTOL]],
		corpse = [[DEAD]],
		description = [[Torpedo Launcher]],
		energyMake = 0.2,
		energyStorage = 0,
		energyUse = 0.2,
		explodeAs = [[MEDIUM_BUILDINGEX]],
		featureDefs = {
			DEAD = {
				blocking = false,
				category = [[corpses]],
				damage = nil,
				description = nil,
				energy = 0,
				footprintX = 3,
				footprintZ = 3,
				height = 4,
				hitdensity = 100,
				metal = nil,
				object = [[CORTL_DEAD]],
				reclaimable = true,
				seqnamereclamate = [[TREE1RECLAMATE]],
				world = [[All Worlds]],
			},
		},
		firestandorders = 1,
		footprintX = 3,
		footprintZ = 3,
		iconType = [[building]],
		idleAutoHeal = 5,
		idleTime = 1800,
		maxDamage = 1977,
		maxSlope = 10,
		maxVelocity = 0,
		metalStorage = 0,
		minWaterDepth = 1,
		name = [[Urchin]],
		noAutoFire = false,
		noChaseCategory = [[ALL]],
		objectName = [[CORTL]],
		seismicSignature = 0,
		selfDestructAs = [[MEDIUM_BUILDING]],
		side = [[CORE]],
		sightDistance = 455,
		smoothAnim = true,
		sounds = {
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[cantdo4]],
			},
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			ok = {
				[1] = [[shcormov]],
			},
			select = {
				[1] = [[shcorsel]],
			},
			underattack = [[warning1]],
		},
		standingfireorder = 2,
		turnRate = 0,
		unitname = [[cortl]],
		waterline = 13,
		weaponDefs = {
			COAX_TORPEDO = {
				areaOfEffect = 16,
				avoidFriendly = false,
				burnblow = true,
				collideFriendly = false,
				craterBoost = 0,
				craterMult = 0,
				damage = {
					commanders = 260,
					default = 280,
					krogoth = 260,
				},
				explosionGenerator = [[custom:FLASH2]],
				guidance = true,
				impactonly = 1,
				impulseBoost = 0.123,
				impulseFactor = 0.123,
				lineOfSight = true,
				model = [[torpedo]],
				name = [[Level1TorpedoLauncher]],
				noSelfDamage = true,
				propeller = 1,
				range = 600,
				reloadtime = 1.9,
				renderType = 1,
				selfprop = true,
				soundHit = [[xplodep2]],
				soundStart = [[torpedo1]],
				startVelocity = 200,
				tracks = true,
				turnRate = 2500,
				turret = true,
				waterWeapon = true,
				weaponAcceleration = 40,
				weaponTimer = 3,
				weaponType = [[TorpedoLauncher]],
				weaponVelocity = 320,
			},
		},
		weapons = {
			[1] = {
				badTargetCategory = [[HOVER NOTSHIP]],
				def = [[COAX_TORPEDO]],
			},
		},
		workerTime = 5,
		yardMap = [[wwwwwwwww]],
	},
}
Def.cortl.featureDefs.DEAD.damage = 0.6000 * Def.cortl.maxDamage
Def.cortl.featureDefs.DEAD.description = Def.cortl.name .. [[ Wreckage]]
Def.cortl.featureDefs.DEAD.metal = 0.8000 * Def.cortl.buildCostMetal
return lowerkeys(Def)
