return {
	crnns = {
		activatewhenbuilt = true,
		buildangle = 16000,
		buildcostenergy = 155415,
		buildcostmetal = 18191,
		builder = false,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 11,
		buildinggrounddecalsizey = 11,
		buildinggrounddecaltype = "crnns_aoplane.dds",
		buildpic = "crnns.dds",
		buildtime = 360000,
		category = "ALL NOTDEFENSE NOTHOVERNOTVTOL NOTMOBILE NOTSUB NOTSUBNOTSHIP NOTVTOL NOTWEAPON UNDERWATER SURFACE",
		damagemodifier = 0.9,
		description = "Produces Energy / Storage",
		energymake = 5120,
		energystorage = 51200,
		explodeas = "NUCLEAR_MISSILE_CORE",
		footprintx = 10,
		footprintz = 8,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 56,
		mass = 18191,
		maxdamage = 10400,
		minwaterdepth = 15,
		name = "Advanced Antimater Fusion",
		noautofire = false,
		nochasecategory = "ALL",
		noshadow = 1,
		objectname = "crnns",
		onoffable = true,
		radardistance = 0,
		radaremitheight = 56,
		selfdestructas = "CRBLMSSL_CORE",
		sightdistance = 210,
		unitname = "crnns",
		usebuildinggrounddecal = true,
		waterline = 10,
		yardmap = "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
		customparams = {
			buildpic = "crnns.dds",
			faction = "CORE",
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail5",
				[2] = "piecetrail5",
				[3] = "piecetrail4",
				[4] = "piecetrail6",
			},
		},
		sounds = {
			activate = "mohorun1",
			canceldestruct = "cancel2",
			deactivate = "mohooff1",
			underattack = "warning1",
			working = "mohorun1",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "twractv2",
			},
			select = {
				[1] = "mohoon1",
			},
		},
	},
}
