return {
	gok_pound = {
		acceleration = 0.11,
		brakerate = 0.21,
		buildcostenergy = 149850,
		buildcostmetal = 7415,
		builder = false,
		buildpic = "gok_pound.dds",
		buildtime = 27000,
		canattack = true,
		canguard = true,
		canhover = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL LARGE MOBILE SURFACE",
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "90 130 130",
		collisionvolumetype = "ellipsoid",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Lightning Hovercraft",
		downloadable = 1,
		explodeas = "CRAWL_BLAST",
		firestandorders = 1,
		footprintx = 8,
		footprintz = 8,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 49,
		maneuverleashlength = 640,
		mass = 7415,
		maxdamage = 7350,
		maxslope = 10,
		maxvelocity = 1.2,
		maxwaterdepth = 0,
		mobilestandorders = 1,
		movementclass = "TANKHOVER6",
		name = "Pound",
		noautofire = false,
		objectname = "gok/gok_pound.s3o",
		radardistance = 0,
		radaremitheight = 48,
		selfdestructas = "CRAWL_BLAST",
		sightdistance = 450,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplace = 0,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0.99,
		turnrate = 250,
		unitname = "gok_pound",
		customparams = {
			buildpic = "gok_pound.dds",
			faction = "GOK",
			normaltex = "unittextures/gok_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 20554,
				description = "Pound Wreckage",
				footprintx = 5,
				footprintz = 5,
				object = "gok/gok_pound_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"hovmdok1",
			},
			select = {
				"hovmdsl1",
			},
		},
		weapondefs = {
			storm = {
				areaofeffect = 24,
				beamttl = 10,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 10,
				energypershot = 450,
				firestarter = 50,
				firesubmersed = true,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				intensity = 12,
				name = "Storm Lightning",
				noselfdamage = true,
				range = 1300,
				reloadtime = 0.5,
				rgbcolor = "0.78 0.08 0.55",
				soundhitdry = "lashit",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "techa_sounds/gok_hero_lighting",
				soundtrigger = true,
				sprayangle = 850,
				texture1 = "strike",
				thickness = 10,
				turret = true,
				weapontype = "LightningCannon",
				weaponvelocity = 400,
				damage = {
					air = 300,
					commanders = 300,
					default = 600,
					subs = 5,
				},
			},
		},
		weapons = {
			{
				badtargetcategory = "SMALL MINOR VTOL",
				def = "STORM",
			},
		},
	},
}
