return {
	gok_blackpollen = {
		buildangle = 32700,
		buildcostenergy = 20852,
		buildcostmetal = 1546,
		builder = false,
		buildpic = "gok_blackpollen.dds",
		buildtime = 15000,
		canattack = true,
		canstop = 1,
		category = "ALL SURFACE",
		corpse = "dead",
		defaultmissiontype = "GUARD_NOMOVE",
		description = "Cut Launcher",
		explodeas = "LARGE_BUILDING",
		firestandorders = 1,
		footprintx = 5,
		footprintz = 5,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 71,
		mass = 1546,
		maxdamage = 2150,
		maxslope = 12,
		maxvelocity = 0,
		maxwaterdepth = 0,
		name = "Black Pollen",
		objectname = "gok/gok_blackpollen.s3o",
		radaremitheight = 70,
		seismicsignature = 0,
		selfdestructas = "CRAWL_BLAST",
		sightdistance = 273,
		standingfireorder = 0,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0,
		turnrate = 0,
		unitname = "gok_blackpollen",
		usepiececollisionvolumes = true,
		usepieceselectionvolumes = true,
		yardmap = "ooooo ooooo ooooo ooooo ooooo",
		customparams = {
			buildpic = "gok_blackpollen.dds",
			canareaattack = 1,
			faction = "GOK",
			normaltex = "unittextures/gok_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "120 140 180",
				collisionvolumetype = "Box",
				damage = 3509,
				description = "Black Pollen Wreckage",
				energy = 0,
				featuredead = "heap",
				footprintx = 3,
				footprintz = 3,
				metal = 720,
				object = "gok/gok_blackpollen_dead",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				damage = 4387,
				description = "Black Pollen Debris",
				energy = 0,
				footprintx = 3,
				footprintz = 3,
				metal = 384,
				object = "3x3e",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servlrg3",
			},
			select = {
				[1] = "servlrg3",
			},
		},
		weapondefs = {
			cut_launcher = {
				accuracy = 500,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0.01,
				cratermult = 0,
				energypershot = 425,
				gravityaffected = "TRUE",
				impulseboost = 0.1,
				impulsefactor = 0.1,
				commandfire = true,
				metalpershot = 24,
				model = "gok/gok_cut.s3o",
				name = "Cut Launcher",
				noselfdamage = true,
				range = 2800,
				reloadtime = 0.3,
				soundhitdry = "flakhit",
				soundhitwet = "",
				soundstart = "blackpollen",
				sprayangle = 600,
				stockpile = true,
				stockpiletime = 2,
				trajectoryheight = 1.8,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 500,
				wobble = 1800,
				damage = {
					default = 30,
				},
			},
		},
		weapons = {
			[1] = {
				def = "CUT_LAUNCHER",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
