return {
	gok_tzenth = {
		acceleration = 0.04,
		activatewhenbuilt = true,
		brakerate = 0.057,
		buildcostenergy = 1085621,
		buildcostmetal = 48677,
		builder = false,
		buildpic = "gok_tzenth.dds",
		buildtime = 150000,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL HUGE MOBILE UNDERWATER",
		collisionvolumeoffsets = "0 -20 -15",
		collisionvolumescales = "180 70 400",
		collisionvolumetype = "Ell",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Ultimate Battle Sub",
		explodeas = "CRAWL_BLASTSML",
		firestandorders = 1,
		footprintx = 8,
		footprintz = 8,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 45,
		maneuverleashlength = 640,
		mass = 48677,
		maxdamage = 69200,
		maxvelocity = 1,
		minwaterdepth = 22,
		mobilestandorders = 1,
		movementclass = "UBOAT8",
		name = "Tzenth",
		noautofire = false,
		objectname = "gok/gok_tzenth.s3o",
		radaremitheight = 45,
		selfdestructas = "CRAWL_BLAST",
		sightdistance = 750,
		sonardistance = 2000,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0.99,
		turnrate = 75,
		unitname = "gok_tzenth",
		upright = true,
		waterline = 70,
		customparams = {
			buildpic = "gok_tzenth.dds",
			faction = "ARM",
			normaltex = "unittextures/gok_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 30061,
				description = "Tzenth Wreckage",
				featuredead = "heap",
				footprintx = 7,
				footprintz = 7,
				metal = 2799,
				object = "gok/gok_tzenth_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				damage = 30826,
				description = "Tzenth Debris",
				footprintx = 8,
				footprintz = 8,
				metal = 1493,
				object = "7x7d.s3o",
				reclaimable = true,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "sucormov",
			},
			select = {
				[1] = "sucorsel",
			},
		},
		weapondefs = {
			sub_weapon_front = {
				areaofeffect = 96,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				burst = 3,
				burstrate = 0.16,
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASH3",
				impactonly = 1,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				model = "weapon_torpedo_adv_gok.s3o",
				name = "advTorpedo",
				noselfdamage = true,
				range = 1200,
				reloadtime = 1.2,
				soundhitdry = "xplodep1",
				soundhitwet = "xplodep1",
				soundstart = "torpedo1",
				startvelocity = 165,
				tracks = true,
				turnrate = 1500,
				turret = true,
				waterweapon = true,
				weaponacceleration = 30,
				weapontimer = 4,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 250,
				damage = {
					default = 1200,
				},
			},
			sub_weapon_back = {
				areaofeffect = 96,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASH3",
				impactonly = 1,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				model = "weapon_torpedo_adv_gok.s3o",
				name = "advTorpedo",
				noselfdamage = true,
				range = 1200,
				reloadtime = 1,
				soundhitdry = "xplodep1",
				soundhitwet = "xplodep1",
				soundstart = "torpedo1",
				startvelocity = 165,
				tracks = true,
				turnrate = 1500,
				turret = true,
				waterweapon = true,
				weaponacceleration = 30,
				weapontimer = 4,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 250,
				damage = {
					default = 1200,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "SURFACE",
				def = "SUB_WEAPON_FRONT",
				maindir = "0 0 1",
				maxangledif = 60,
				onlytargetcategory = "UNDERWATER",
			},
			[3] = {
				badtargetcategory = "SURFACE",
				def = "SUB_WEAPON_BACK",
				maindir = "0 0 -1",
				maxangledif = 60,
				onlytargetcategory = "UNDERWATER",
			},
		},
	},
}
