return {
	gok_gen = {
		activatewhenbuilt = true,
		buildangle = 0,
		buildcostenergy = 8595,
		buildcostmetal = 587,
		builder = false,
		buildpic = "gok_gen.dds",
		buildtime = 10000,
		category = "ALL SURFACE",
		collisionvolumescales = "45 38 45",
		collisionvolumetype = "CylY",
		corpse = "dead",
		description = "Produce Energy",
		energymake = 160,
		explodeas = "MEDIUM_BUILDINGEX",
		footprintx = 3,
		footprintz = 3,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 32,
		mass = 587,
		maxdamage = 1250,
		maxslope = 10,
		maxwaterdepth = 0,
		name = "Mini Fusion Reactor",
		noautofire = false,
		objectname = "gok/gok_gen.s3o",
		radaremitheight = 32,
		selfdestructas = "MEDIUM_BUILDING",
		sightdistance = 250,
		unitname = "gok_gen",
		yardmap = "ooo ooo ooo",
		customparams = {
			buildpic = "gok_gen.dds",
			faction = "gok",
			normaltex = "unittextures/gok_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 2360,
				description = "Light Fusion Power Plant Wreckage",
				featuredead = "heap",
				footprintx = 6,
				footprintz = 6,
				metal = 1147,
				object = "gok/gok_gen_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				damage = 2950,
				description = "Light Fusion Power Plant Debris",
				footprintx = 6,
				footprintz = 6,
				metal = 612,
				object = "3x3a.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:reactor_sfx_new_other",
			},
			pieceexplosiongenerators = {
				[1] = "piecetrail5",
				[2] = "piecetrail5",
				[3] = "piecetrail4",
				[4] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "geothrm1",
			},
		},
	},
}
