return {
	gok_revenant = {
		acceleration = 0.15,
		bankscale = 1,
		blocking = false,
		brakerate = 0.4,
		buildcostenergy = 12994,
		buildcostmetal = 301,
		builder = false,
		buildpic = "gok_revenant.dds",
		buildtime = 20000,
		canattack = true,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MOBILE VTOL",
		collide = false,
		corpse = "heap",
		cruisealt = 80,
		defaultmissiontype = "VTOL_standby",
		description = "Torpedo Gunship",
		explodeas = "GUNSHIPEX",
		firestandorders = 1,
		footprintx = 3,
		footprintz = 3,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 8,
		maneuverleashlength = 1280,
		mass = 301,
		maxdamage = 1220,
		maxslope = 10,
		maxvelocity = 5.0,
		maxwaterdepth = 0,
		mobilestandorders = 1,
		name = "Revenant",
		noautofire = false,
		objectname = "gok/gok_revenant.s3o",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT_VTOL",
		sightdistance = 550,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 360,
		turninplacespeedlimit = 3.2,
		turnrate = 550,
		unitname = "gok_revenant",
		customparams = {
			buildpic = "gok_revenant.dds",
			faction = "GOK",
			normaltex = "unittextures/gok_normals.dds",
		},
		featuredefs = {
			heap = {
				blocking = false,
				damage = 39641,
				description = "Aircraft Debris",
				footprintx = 3,
				footprintz = 3,
				metal = 150,
				object = "3x3z.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			explosiongenerators = {
				"custom:muendungsfeuer",
			},
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"vtolarmv",
			},
			select = {
				"vtolarac",
			},
		},
		weapondefs = {
			torpedo = {
				areaofeffect = 16,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				bouncerebound = 0.6,
				bounceslip = 0.6,
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASH2",
				flighttime = 2,
				impactonly = 1,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				numbounce = 1,
				model = "weapon_torpedo.s3o",
				name = "TorpedoLauncher",
				noselfdamage = true,
				range = 500,
				reloadtime = 2,
				soundhitdry = "xplodep2",
				soundhitwet = "xplodep2",
				soundstart = "bombrel",
				startvelocity = 250,
				tracks = false,
				tolerance = 8000,
				turnrate = 64000,
				turret = false,
				waterweapon = true,
				weapontimer = 1,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 250,
				damage = {
					default = 300,
					subs = 600,
				},
			},
		},
		weapons = {
			{
				badtargetcategory = "SURFACE",
				def = "TORPEDO",
				onlytargetcategory = "UNDERWATER",
			},
		},
	},
}