return {
	gok_spook = {
		acceleration = 0.24,
		bankscale = 1,
		blocking = false,
		brakerate = 0.441,
		buildcostenergy = 7951,
		buildcostmetal = 304,
		builder = false,
		buildpic = "gok_spook.dds",
		buildtime = 20000,
		canattack = true,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MOBILE VTOL",
		collide = false,
		corpse = "heap",
		cruisealt = 100,
		defaultmissiontype = "VTOL_standby",
		description = "Gunship",
		explodeas = "GUNSHIPEX",
		firestandorders = 1,
		footprintx = 3,
		footprintz = 3,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 8,
		maneuverleashlength = 1280,
		mass = 301,
		maxdamage = 1390,
		maxslope = 10,
		maxvelocity = 5.0,
		maxwaterdepth = 0,
		mobilestandorders = 1,
		name = "Spook",
		noautofire = false,
		objectname = "gok/gok_spook.s3o",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT_VTOL",
		sightdistance = 550,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 360,
		turninplacespeedlimit = 3.2,
		turnrate = 775,
		unitname = "gok_spook",
		customparams = {
			buildpic = "gok_spook.dds",
			faction = "ARM",
			normaltex = "unittextures/gok_normals.dds",
		},
		featuredefs = {
			heap = {
				blocking = false,
				damage = 4341,
				description = "Aircraft Debris",
				footprintx = 2,
				footprintz = 2,
				metal = 122,
				object = "2x2z.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"vtolarmv",
			},
			select = {
				"vtolarac",
			},
		},
		weapondefs = {
			gok_plasma = {
				accuracy = 100,
				areaofeffect = 32,
				avoidfeature = false,
				burnblow = true,
				cegtag = "gokblaster",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:gokexplosion",
				impulseboost = 0.123,
				impulsefactor = 0.123,
				intensity = 1,
				name = "Gok Blaster",
				noselfdamage = true,
				range = 350,
				reloadtime = 2.5,
				rgbcolor = "0.78 0.08 0.52",
				size = 0.25,
				soundhitdry = "",
				soundhitwet = "splssml",
				soundhitwetvolume = 0.6,
				soundstart = "techa_sounds/gok_plasma",
				sprayangle = 200,
				tolerance = 6000,
				weapontype = "Cannon",
				weaponvelocity = 350,
				damage = {
					commanders = 150,
					default = 300,
					subs = 5,
				},
				tracks = false,
			},
		},
		weapons = {
			{
				def = "GOK_PLASMA",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}