return {
	halloween = {
		acceleration = 0.1,
		blocking = false,
		brakerate = 0.5,
		buildcostenergy = 10000,
		buildcostmetal = 1000,
		buildpic = "halloween.dds",
		buildtime = 5000,
		canattack = true,
		canfly = true,
		canguard = true,
		canmove = true,
		category = "ALL SURFACE VTOL",
		collide = false,
		cruisealt = 50,
		description = "Be frightened",
		energymake = 100,
		explodeas = "TINY_BUILDINGEX",
		firestandorders = 1,
		footprintx = 2,
		footprintz = 2,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 2,
		maneuverleashlength = 75,
		mass = 1000000,
		maxdamage = 100000,
		maxslope = 10,
		maxvelocity = 2.5,
		maxwaterdepth = 0,
		mobilestandorders = 1,
		name = "Pumpkin",
		noautofire = false,
		objectname = "halloween",
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT_VTOL",
		sightdistance = 350,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 360,
		turninplacespeedlimit = 5,
		turnrate = 750,
		unitname = "halloween",
		upright = true,
		customparams = {
			buildpic = "halloween.dds",
			faction = "ALL",
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail5",
				[2] = "piecetrail5",
				[3] = "piecetrail4",
				[4] = "piecetrail6",
			},
		},
		sounds = {
			activate = "solar1",
			canceldestruct = "cancel2",
			deactivate = "solar1",
			underattack = "warning1",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "warning1",
			},
		},
	},
}
