-- UNITDEF -- MACROSS --
--------------------------------------------------------------------------------

local unitName = "macross"

--------------------------------------------------------------------------------

local unitDef = {
  acceleration       = 0.3,
  badTargetCategory  = [[VTOL]],
  bmcode             = 1,
  brakeRate          = 0.32,
  buildCostEnergy    = 241568,
  buildCostMetal     = 15489,
  builder            = false,
  buildTime          = 102487,
  canAttack          = true,
  canGuard           = true,
  canMove            = true,
  canPatrol          = true,
  canstop            = 1,
  cantBeTransported  = true,
  category           = [[KBOT WEAPON ALL NOTSUB NOTAIR]],
  copyright          = [[Copyright 1997 Humongous Entertainment. All rights reserved.]],
  corpse             = [[dead]],
  defaultmissiontype = [[Standby]],
  description        = [[Krogoth class k-bot All-terrain]],
  designation        = [[GPB-1S]],
  energyMake         = 22.5,
  energyStorage      = 100,
  energyUse          = 10.75,
  explodeAs          = [[CRAWL_BLAST]],
  firestandorders    = 1,
  footprintX         = 4,
  footprintZ         = 4,
  frenchdescription  = [[Kbot de classe Krogoth]],
  germandescription  = [[Kbot der Krogoth Klasse]],
  immunetoparalyzer  = 1,
  maneuverleashlength = 640,
  maxDamage          = 69950,
  maxSlope           = 20,
  maxVelocity        = 1.05,
  maxWaterDepth      = 12,
  metalStorage       = 0,
  mobilestandorders  = 1,
  movementClass      = [[HTKBOT4]],
  name               = [[Macross]],
  noAutoFire         = false,
  noChaseCategory    = [[VTOL]],
  objectName         = [[macross5]],
  radarDistance      = 0,
  selfDestructAs     = [[NUCLEAR_MISSILE]],
  selfDestructCountdown = 10,
  shootme            = 1,
  side               = [[CORE]],
  sightDistance      = 380,
  standingfireorder  = 2,
  standingmoveorder  = 1,
  steeringmode       = 2,
  threed             = 1,
  turnRate           = 205,
  unitname           = [[macross]],
  unitnumber         = 29675,
  upright            = true,
  version            = 3.1,
  workerTime         = 0,
  zbuffer            = 1,
  sounds = {
    canceldestruct     = [[cancel2]],
    underattack        = [[warning1]],
    cant = {
      [[cantdo4]],
    },
    count = {
      [[count6]],
      [[count5]],
      [[count4]],
      [[count3]],
      [[count2]],
      [[count1]],
    },
    ok = {
      [[krogok1]],
    },
    select = {
      [[krogsel1]],
    },
  },
  weapons = {
    [1]  = {
      badTargetCategory  = [[VTOL]],
      def                = [[MACROSS_FIRE]],
    },
    [2]  = {
      def                = [[MACROSS_ARM_GUN]],
      onlyTargetCategory = [[Notair]],
    },
    [3]  = {
      def                = [[MACROSS_MISSILE]],
      onlyTargetCategory = [[Notair]],
    },
  },
}


--------------------------------------------------------------------------------

local weaponDefs = {
  MACROSS_ARM_GUN = {
    areaOfEffect       = 75,
    explosionart       = [[explode4]],
    explosiongaf       = [[fx]],
    id                 = 142,
    lavaexplosionart   = [[lavasplashsm]],
    lavaexplosiongaf   = [[fx]],
    lineOfSight        = true,
    minbarrelangle     = -15,
    model              = [[macrossbullets]],
    name               = [[Macross Arm Canon]],
    range              = 600,
    reloadtime         = 1.15,
    renderType         = 1,
    soundHit           = [[macrossmhit]],
    soundStart         = [[macrossmissile]],
    startsmoke         = 1,
    tolerance          = 1000,
    turret             = true,
    waterexplosionart  = [[h2oboom1]],
    waterexplosiongaf  = [[fx]],
    weaponType         = [[Cannon]],
    weaponVelocity     = 500,
    damage = {
      default            = 1000,
    },
  },
  MACROSS_FIRE = {
    areaOfEffect       = 48,
    color              = 2,
    id                 = 6,
    impulseFactor      = 2,
    lineOfSight        = true,
    minbarrelangle     = -50,
    name               = [[GaussCannon]],
    noExplode          = true,
    pitchtolerance     = 12000,
    range              = 590,
    reloadtime         = 1.4,
    renderType         = 4,
    soundHit           = [[xplomed2]],
    soundStart         = [[Krogun1]],
    startsmoke         = 1,
    tolerance          = 2400,
    turret             = true,
    weaponType         = [[EmgCannon]],
    weaponVelocity     = 530,
    damage = {
      anniddm            = 190,
      default            = 140,
    },
  },
  MACROSS_MISSILE = {
    areaOfEffect       = 148,
    explosionart       = [[macrossgun]],
    explosiongaf       = [[macrossgun]],
    fireStarter        = 70,
    guidance           = true,
    id                 = 170,
    lavaexplosionart   = [[lavasplash]],
    lavaexplosiongaf   = [[fx]],
    lineOfSight        = true,
    metalpershot       = 0,
    model              = [[macrossmissile]],
    name               = [[Macross Missiles]],
    range              = 620,
    reloadtime         = 1.05,
    renderType         = 1,
    selfprop           = true,
    smokedelay         = .25,
    smokeTrail         = true,
    soundHit           = [[macrossmhit]],
    soundStart         = [[macrossmissile]],
    startsmoke         = 1,
    startVelocity      = 150,
    tolerance          = 8000,
    tracks             = true,
    turnRate           = 30000,
    turret             = true,
    waterexplosionart  = [[h2o]],
    waterexplosiongaf  = [[fx]],
    weaponAcceleration = 150,
    weaponTimer        = 30,
    weaponType         = [[MissileLauncher]],
    weaponVelocity     = 440,
    damage = {
      default            = 900,
    },
  },
}
unitDef.weaponDefs = weaponDefs


--------------------------------------------------------------------------------

local featureDefs = {
  dead = {
    blocking           = true,
    category           = [[core_corpses]],
    damage             = unitDef.maxDamage*0.6,
    description        = [[Macross Wreckage]],
    featureDead        = [[heap]],
    featurereclamate   = [[smudge01]],
    footprintX         = 3,
    footprintZ         = 3,
    height             = 31,
    hitdensity         = 105,
    metal              = unitDef.buildCostMetal*0.8,
    object             = [[macross_dead]],
    reclaimable        = true,
    seqnamereclamate   = [[tree1reclamate]],
    world              = [[All Worlds]],
  },
  heap = {
    blocking           = false,
    category           = [[heaps]],
    damage             = unitDef.maxDamage*0.36,
    description        = [[Macross Heap]],
    featurereclamate   = [[smudge01]],
    footprintX         = 3,
    footprintZ         = 3,
    height             = 2,
    hitdensity         = 105,
    metal              = unitDef.buildCostMetal*0.64,
    object             = [[3x3a]],
    reclaimable        = true,
    seqnamereclamate   = [[tree1reclamate]],
    world              = [[All Worlds]],
  },
}
unitDef.featureDefs = featureDefs


--------------------------------------------------------------------------------

return lowerkeys({ [unitName] = unitDef })

--------------------------------------------------------------------------------
