return {
	nsaagriz = {
		acceleration = 0.04,
		brakerate = 0.285,
		buildcostenergy = 520133,
		buildcostmetal = 29101,
		builder = false,
		buildpic = "nsaagriz.dds",
		buildtime = 520000,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		cantbetransported = true,
		category = "ALL HUGE MOBILE NOTDEFENSE NOTHOVERNOTVTOL NOTSUB NOTSUBNOTSHIP NOTVTOL WEAPON SURFACE",
		collisionvolumeoffsets = "9 0 0",
		collisionvolumescales = "80 77 92",
		collisionvolumetype = "box",
		corpse = "dead",
		damagemodifier = 0.05,
		defaultmissiontype = "Standby",
		description = "Armored Mobile Blaster",
		downloadable = 1,
		energystorage = 1000,
		explodeas = "BANTHA_NUKE",
		firestandorders = 1,
		footprintx = 5,
		footprintz = 5,
		germaname = "Krypto-Blaster",
		healtime = 50,
		idleautoheal = 4,
		idletime = 2000,
		immunetoparalyzer = 1,
		losemitheight = 70,
		maneuverleashlength = 640,
		mass = 29101,
		maxdamage = 26195,
		maxslope = 30,
		maxvelocity = 1,
		maxwaterdepth = 12,
		mobilestanorders = 1,
		movementclass = "VHTANK5",
		name = "Krypto-Blaster",
		noautofire = false,
		nochasecategory = "SUB VTOL",
		objectname = "NSAAGRIZ",
		onoffable = true,
		radardistance = 1000,
		radaremitheight = 70,
		selfdestructas = "CRBLMSSL",
		selfdestructcountdown = 10,
		sightdistance = 240,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 2,
		turninplace = 0,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0.66,
		turnrate = 600,
		unitname = "nsaagriz",
		customparams = {
			buildpic = "nsaagriz.dds",
			faction = "ARM",
			requiretech = "Advanced T3 Unit Research Centre",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 9920,
				description = "Krypto-Blaster Wreckage",
				featuredead = "heap",
				featurereclaimate = "smudge01",
				footprintx = 3,
				footprintz = 3,
				metal = 21750,
				object = "nsaagriz_dead",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				damage = 12400,
				description = "Krypto-Blaster Debris",
				footprintx = 3,
				footprintz = 3,
				metal = 11600,
				object = "3x3a",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:tllroaster_muzzle",
			},
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
		weapondefs = {
			k666blaster = {
				accuracy = 100,
				areaofeffect = 24,
				beamdecay = 0.9,
				beamtime = 0.6,
				beamttl = 9,
				burst = 20,
				burstrate = 0.1,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 1.79,
				energypershot = 10000,
				firestarter = 0,
				impulseboost = 0,
				impulsefactor = 0,
				metalpershot = 0,
				name = "Heavy Blaster Doomer's creation",
				noexplode = true,
				pulsespeed = 4,
				range = 1400,
				reloadtime = 1.2,
				rgbcolor = "0.5 0.4 1.0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "krypto",
				soundtrigger = 1,
				sprayangle = 800,
				sweepfire = false,
				texture1 = "strike",
				texture2 = "null",
				texture3 = "null",
				texture4 = "null",
				thickness = 20,
				tolerance = 5000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 600,
				customparams = {
					light_mult = 1.8,
					light_radius_mult = 1.2,
				},
				damage = {
					commanders = 2500,
					default = 15000,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "MEDIUM SMALL TINY",
				def = "K666BLASTER",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
