return {
	rumad_gala = {
		acceleration = 0.08,
		brakerate = 0.63,
		buildcostenergy = 1950430,
		buildcostmetal = 119000,
		builder = false,
		buildpic = "rumad_gala.dds",
		buildtime = 1250000,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canmanualfire = true,
		canstop = 1,
		cantbetransported = true,
		category = "ALL MAJOR MOBILE SURFACE UNDERWATER",
		collisionvolumeoffsets = "0 -15 0",
		collisionvolumescales = "180 262 129",
		collisionvolumetype = "ellipsoid",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Experimental Artillery/Nuke Kbot",
		explodeas = "KROG_BLAST",
		firestandorders = 1,
		footprintx = 9,
		footprintz = 9,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 225,
		maneuverleashlength = 640,
		mass = 115000,
		maxdamage = 295000,
		maxslope = 15,
		maxvelocity = 1,
		maxwaterdepth = 16,
		metalstorage = 50,
		mobilestandorders = 1,
		movementclass = "VKBOT9",
		name = "Galacticus",
		noautofire = false,
		objectname = "rumad_gala",
		radaremitheight = 225,
		selfdestructas = "EXO_BLAST",
		selfdestructcountdown = 10,
		sightdistance = 750,
		standingfireorder = 2,
		standingmoveorder = 0,
		steeringmode = 2,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0.924,
		turnrate = 320,
		unitname = "rumad_gala",
		upright = true,
		customparams = {
			buildpic = "rumad_gala.dds",
			faction = "RUMAD",
		},
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumeoffsets = "0 -11 0",
				collisionvolumescales = "96 88 134",
				collisionvolumetype = "Ell",
				damage = 107435,
				description = "Galacticus Wreckage",
				energy = 0,
				featuredead = "heap",
				footprintx = 5,
				footprintz = 5,
				metal = 60400,
				object = "rumad_gala_DEAD",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				damage = 171794,
				description = "Galacticus Debris",
				energy = 0,
				footprintx = 7,
				footprintz = 7,
				metal = 25880,
				object = "7X7A",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:lrpt",
				--[2] = "custom:gala_flare",
				--[3] = "custom:gala_ring_large",
				--[4] = "custom:gala_ring_small",
			},
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		weapondefs = {
			rumad_plasma = {
				accuracy = 200,
				areaofeffect = 256,
				avoidfeature = false,
				craterareaofeffect = 64,
				craterboost = 0,
				cratermult = 0,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				name = "Plasma",
				noselfdamage = true,
				range = 2400,
				reloadtime = 5,
				rgbcolor = "0.9 0.9 0.9",
				separation = 0.45,
				size = 2,
				sizedecay = -0.15,
				soundhitdry = "xplomed2",
				soundhitwet = "splshbig",
				soundhitwetvolume = 0.5,
				soundstart = "techa_sounds/rumad_plasma",
				sprayangle = 360,
				stages = 20,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 650,
				damage = {
					default = 4800,
					subs = 5,
				},
			},
			rumad_advmissilex12 = {
				areaofeffect = 96,
				avoidfeature = false,
				burst = 12,
				burstrate = 0.15,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASH2",
				firestarter = 70,
				flighttime = 2,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				model = "weapon_missile_rumad",
				name = "Missiles",
				noselfdamage = true,
				range = 1000,
				reloadtime = 2.4,
				smoketrail = true,
				soundhitdry = "xplosml2",
				soundhitwet = "splshbig",
				soundhitwetvolume = 0.6,
				soundstart = "rocklit1",
				startvelocity = 500,
				tracks = true,
				turnrate = 20000,
				turret = true,
				weaponacceleration = 100,
				weapontimer = 2,
				weapontype = "MissileLauncher",
				weaponvelocity = 600,
				damage = {
					default = 180,
					subs = 5,
				},
			},
			nuclear_missile = {
				areaofeffect = 1280,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "Trail_nuke",
				collidefriendly = false,
				commandfire = true,
				craterareaofeffect = 1280,
				craterboost = 0.72,
				cratermult = 0.36,
				edgeeffectiveness = 0.3,
				explosiongenerator = "custom:nuke_explo_1280",
				firestarter = 0,
				flighttime = 400,
				impulseboost = 0.5,
				impulsefactor = 2.5,
				model = "weapon_nuke_gala",
				name = "Nuclear Missiles",
				range = 5000,
				reloadtime = 1,
				smoketrail = true,
				soundhitdry = "xplomed4",
				soundstart = "misicbm1",
				startvelocity = 400,
				targetable = 16,
				texture1 = "null",
				texture2 = "null",
				texture3 = "null",
				texture4 = "null",
				tolerance = 8000,
				turret = true,
				turnrate = 32000,
				weaponacceleration = 140,
				weapontimer = 3,
				weapontype = "MissileLauncher",
				weaponvelocity = 1300,
				damage = {
					commanders = 3750,
					default = 15000,
					subs = 1500,
				},
				customparams = {
					light_color = "1 0.6 0.2",
					light_mult = 7,
					light_radius_mult = 2,
					expl_light_color = "1 0.85 0.55",
					expl_light_mult = 1.25,
					expl_light_life_mult = 2.4,
					expl_light_radius_mult = 0.9,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "HUGE LARGE MEDIUM SMALL MINOR",
				def = "RUMAD_PLASMA",
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				def = "RUMAD_ADVMISSILEX12",
				onlytargetcategory = "SURFACE",
			},
			[3] = {
				def = "NUCLEAR_MISSILE",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
