return {
	rumad_ascout_lvl2 = {
		acceleration = 0.04095,
		altfromsealevel = 1,
		bankscale = 1,
		blocking = false,
		brakerate = 0.05,
		buildcostenergy = 6290,
		buildcostmetal = 135,
		builder = false,
		buildpic = "rumad_ascout_lvl2.dds",
		buildtime = 7500,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MINOR MOBILE VTOL",
		collide = false,
		cruisealt = 160,
		defaultmissiontype = "VTOL_standby",
		description = "Radar/Sonar Plane",
		explodeas = "BIG_UNITEX",
		footprintx = 3,
		footprintz = 3,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 6,
		maneuverleashlength = 1280,
		mass = 135,
		maxdamage = 800,
		maxslope = 10,
		maxvelocity = 11,
		maxwaterdepth = 0,
		mobilestandorders = 1,
		name = "Desert Eagle",
		noautofire = false,
		objectname = "rumad_ascout_lvl2",
		radardistance = 1600,
		radaremitheight = 6,
		script = "rumad_ascout_lvl1.cob",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT_VTOL",
		sightdistance = 1200,
		sonardistance = 1200,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 7.26,
		turnrate = 392,
		unitname = "rumad_ascout_lvl2",
		customparams = {
			buildpic = "rumad_ascout_lvl2.dds",
			faction = "RUMAD",
			--requiretech = "Advanced T2 Unit Research Centre",
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "aaradsel",
			},
		},
	},
}
