return {
	rumad_gunship_lvl1 = {
		acceleration = 0.1,
		bankscale = 1,
		blocking = false,
		brakerate = 0.375,
		buildcostenergy = 2525,
		buildcostmetal = 155,
		builder = false,
		buildpic = "rumad_gunship_lvl1.dds",
		buildtime = 5000,
		canattack = true,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MOBILE VTOL",
		collide = false,
		cruisealt = 60,
		defaultmissiontype = "VTOL_standby",
		description = "Light Gunship",
		explodeas = "BIG_UNITEX",
		firestandorders = 1,
		footprintx = 2,
		footprintz = 2,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 5.5,
		maneuverleashlength = 1280,
		mass = 155,
		maxdamage = 435,
		maxslope = 10,
		maxvelocity = 4.5,
		maxwaterdepth = 0,
		mobilestandorders = 1,
		name = "Apache",
		noautofire = false,
		objectname = "rumad/rumad_gunship_lvl1.s3o",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT_VTOL",
		sightdistance = 520,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 360,
		turninplacespeedlimit = 2.0,
		turnrate = 400,
		unitname = "rumad_gunship_lvl1",
		customparams = {
			buildpic = "rumad_gunship_lvl1.dds",
			faction = "RUMAD",
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"vtolarmv",
			},
			select = {
				"vtolarac",
			},
		},
		weapondefs = {
			rumad_missile = {
				areaofeffect = 48,
				avoidfeature = false,
				burst = 2,
				burstrate = 0.15,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:none",
				firestarter = 70,
				flighttime = 2,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				model = "weapon_missile.s3o",
				name = "Missiles",
				noselfdamage = true,
				range = 500,
				reloadtime = 4,
				smoketrail = false,
				soundhitdry = "xplosml2",
				soundhitwet = "splshbig",
				soundhitwetvolume = 0.6,
				soundstart = "rocklit1",
				startvelocity = 450,
				tracks = false,
				tolerance = 10000,
				turnrate = 10000,
				turret = false,
				weaponacceleration = 100,
				weapontimer = 2,
				weapontype = "MissileLauncher",
				weaponvelocity = 540,
				damage = {
					default = 50,
					subs = 5,
				},
			},
		},
		weapons = {
			{
				def = "RUMAD_MISSILE",
				onlytargetcategory = "SURFACE",
			},
			{
				def = "RUMAD_MISSILE",
				onlytargetcategory = "SURFACE",
				slaveto = 1,
			},
		},
	},
}