return {
	rumad_antarion = {
		acceleration = 0.03,
		brakerate = 0.09,
		buildcostenergy = 275660,
		buildcostmetal = 23045,
		builder = false,
		buildpic = "rumad_antarion.dds",
		buildtime = 285000,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL HUGE MOBILE SURFACE UNDERWATER",
		collisionvolumeoffsets = "0 -3 7",
		collisionvolumescales = "95 70 90",
		collisionvolumetype = "box",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Experimental Siege Tank",
		explodeas = "BANTHA_BLAST",
		firestandorders = 1,
		footprintx = 7,
		footprintz = 7,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 45,
		maneuverleashlength = 640,
		mass = 23045,
		maxdamage = 90590,
		maxslope = 12,
		maxvelocity = 1.1,
		maxwaterdepth = 20,
		mobilestandorders = 1,
		movementclass = "HTANK6",
		name = "Antarion",
		noautofire = false,
		objectname = "rumad/rumad_antarion.s3o",
		radardistance = 0,
		radaremitheight = 45,
		selfdestructas = "KROG_BLAST",
		sightdistance = 500,
		turninplace = 0,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0.9,
		turnrate = 225,
		unitname = "rumad_antarion",
		customparams = {
			buildpic = "rumad_antarion.dds",
			faction = "RUMAD",
			normaltex = "unittextures/rumad_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 18543,
				description = "Antarion Wreckage",
				featuredead = "heap",
				footprintx = 3,
				footprintz = 3,
				metal = 13875,
				object = "rumad/rumad_antarion_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				damage = 23179,
				description = "Antarion Debris",
				footprintx = 4,
				footprintz = 4,
				metal = 7400,
				object = "4x4a.s3o",
				reclamable = 1,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"tcormove",
			},
			select = {
				"tcorsel",
			},
		},
		weapondefs = {
			rumad_plasma = {
				accuracy = 200,
				areaofeffect = 128,
				avoidfeature = false,
				craterareaofeffect = 64,
				craterboost = 0,
				cratermult = 0,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				name = "Plasma",
				noselfdamage = true,
				range = 1200,
				reloadtime = 5,
				rgbcolor = "0.9 0.9 0.9",
				separation = 0.45,
				size = 2,
				sizedecay = -0.15,
				soundhitdry = "xplomed2",
				soundhitwet = "splshbig",
				soundhitwetvolume = 0.5,
				soundstart = "techa_sounds/rumad_plasma",
				sprayangle = 360,
				stages = 20,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 500,
				damage = {
					default = 1200,
					subs = 5,
				},
				tracks = false,
			},
			rumad_advmissilex4 = {
				areaofeffect = 96,
				avoidfeature = false,
				burst = 4,
				burstrate = 0.15,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASH2",
				firestarter = 70,
				flighttime = 2,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				model = "weapon_missilexl_rumad.s3o",
				name = "Missiles",
				noselfdamage = true,
				range = 1000,
				reloadtime = 2.4,
				smoketrail = true,
				soundhitdry = "xplosml2",
				soundhitwet = "splshbig",
				soundhitwetvolume = 0.6,
				soundstart = "rocklit1",
				startvelocity = 500,
				tracks = false,
				tolerance = 4000,
				weaponacceleration = 100,
				weapontimer = 2,
				weapontype = "MissileLauncher",
				weaponvelocity = 600,
				damage = {
					default = 180,
					subs = 5,
				},
			},
		},
		weapons = {
			{
				badtargetcategory = "MINOR SMALL MEDIUM",
				def = "RUMAD_PLASMA",
				maindir = "1 0 0",
				maxangledif = 250,
				onlytargetcategory = "SURFACE",
			},
			{
				badtargetcategory = "MINOR SMALL MEDIUM",
				def = "RUMAD_PLASMA",
				maindir = "1 0 0",
				maxangledif = 250,
				onlytargetcategory = "SURFACE",
				slaveto = 1,
			},
			{
				badtargetcategory = "MINOR SMALL MEDIUM",
				def = "RUMAD_PLASMA",
				maindir = "1 0 0",
				maxangledif = 250,
				onlytargetcategory = "SURFACE",
				slaveto = 1,
			},
			{
				badtargetcategory = "MINOR SMALL MEDIUM",
				def = "RUMAD_PLASMA",
				maindir = "-1 0 0",
				maxangledif = 250,
				onlytargetcategory = "SURFACE",
			},
			{
				badtargetcategory = "MINOR SMALL MEDIUM",
				def = "RUMAD_PLASMA",
				maindir = "-1 0 0",
				maxangledif = 250,
				onlytargetcategory = "SURFACE",
				slaveto = 4,
			},
			{
				badtargetcategory = "MINOR SMALL MEDIUM",
				def = "RUMAD_PLASMA",
				maindir = "-1 0 0",
				maxangledif = 250,
				onlytargetcategory = "SURFACE",
				slaveto = 4,
			},
			{
				badtargetcategory = "MEDIUM SMALL MINOR",
				def = "RUMAD_ADVMISSILEX4",
				onlytargetcategory = "SURFACE",
			},
			{
				badtargetcategory = "MEDIUM SMALL MINOR",
				def = "RUMAD_ADVMISSILEX4",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}