return {
	rumad_egeo = {
		activatewhenbuilt = true,
		buildangle = 8192,
		buildcostenergy = 390000,
		buildcostmetal = 19350,
		builder = false,
		buildpic = "rumad_egeo.dds",
		buildtime = 400000,
		category = "ALL SURFACE UNDERWATER",
		collisionvolumeoffsets = "0 -2 0",
		collisionvolumescales = "100 160 100",
		collisionvolumetype = "Box",
		corpse = "talon_mohogeo_heap",
		description = "Produces Energy (Amphibious)",
		energymake = 10000,
		energystorage = 10000,
		explodeas = "CRAWL_BLAST",
		footprintx = 9,
		footprintz = 9,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 61,
		mass = 19350,
		maxdamage = 26520,
		maxslope = 10,
		maxwaterdepth = 9999,
		name = "Safe Geothermal Powerplant",
		noautofire = false,
		objectname = "rumad_egeo",
		radaremitheight = 61,
		selfdestructas = "CRAWL_BLAST",
		sightdistance = 210,
		unitname = "talon_mohogeo",
		yardmap = "ooooooooo ooooooooo ooGGGGGoo ooGGGGGoo ooGGGGGoo ooGGGGGoo ooGGGGGoo ooooooooo ooooooooo",
		customparams = {
			buildpic = "rumad_egeo.dds",
			faction = "TALON",
		},
		featuredefs = {
			talon_mohogeo_heap = {
				blocking = false,
				damage = 5238,
				description = "Geothermal Foundry Debris",
				footprintx = 4,
				footprintz = 4,
				metal = 2724,
				object = "8x8a",
				reclaimable = true,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:PILOT",
			},
			pieceexplosiongenerators = {
				[1] = "piecetrail5",
				[2] = "piecetrail5",
				[3] = "piecetrail4",
				[4] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			count = {
				[1] = "talon_count",
				[2] = "talon_count",
				[3] = "talon_count",
				[4] = "talon_count",
				[5] = "talon_count",
				[6] = "talon_count",
			},
			select = {
				[1] = "geothrm1",
			},
		},
	},
}
