return {
	sat_strike = {
		acceleration = 0.005,
		activatewhenbuilt = false,
		airStrafe  = true,
		airHoverFactor = 1,
		bankingAllowed = false,
		blocking = false,
		brakerate = 0.01,
		buildcostenergy = 414057,
		buildcostmetal = 19520,
		builder = false,
		buildpic = "sat_strike.dds",
		buildtime = 300000,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MOBILE SATELLITE",
		collide = false,
		cruisealt = 1750,
		description = "Precision Strike Satellite",
		energyuse = 0,
		explodeas = "BIG_UNITEX",
		footprintx = 8,
		footprintz = 8,
		hoverAttack = true,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 6,
		maneuverleashlength = 1280,
		mass = 4500,
		maxdamage = 10155,
		maxslope = 10,
		maxvelocity = 2,
		maxwaterdepth = 0,
		mobilestandorders = 1,
		name = "Sauron",
		noautofire = false,
		nochasecategory = "ALL",
		objectname = "sat_strike",
		radaremitheight = 6,
		selfdestructas = "BIG_UNIT",
		sightdistance = 750,
		standingmoveorder = 1,
		stealth = true,
		steeringmode = 1,
		turninplaceanglelimit = 50,
		turninplacespeedlimit = 2,
		turnrate = 120,
		unitname = "sat_strike",
		usepiececollisionvolumes = true,
		usepieceselectionvolumes = true,
		customparams = {
			buildpic = "sat_strike.dds",
			faction = "ALL",
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "satelliteselect",
			},
			select = {
				[1] = "satelliteselect",
			},
		},
		weapondefs = {
			sky_laser = {
				areaofeffect = 4,
				corethickness = 0.2,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.08,
				energypershot = 10000,
				explosiongenerator = "custom:SMALL_YELLOW_BURN",
				firestarter = 50,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				intensity = 0.5,
				laserflaresize = 1.25,
				name = "Precision Laser",
				range = 2000,
				reloadtime = 5,
				rgbcolor = "1 0.6 0.1",
				soundhitdry = "lashit",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "lasrlit1",
				soundtrigger = true,
				targetmoveerror = 0.1,
				thickness = 0.75,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 2000,
				damage = {
					commanders = 1000,
					default = 10000,					
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "MOBILE",
				def = "SKY_LASER",
				onlytargetcategory = "SURFACE",
				maindir = "0 -1 0",
				maxangledif = 8,
			},
		},
	},
}
