return {
	sat_radar = {
		acceleration = 0.005,
		activatewhenbuilt = true,
		bankscale = 1,
		blocking = false,
		brakerate = 0.01,
		buildcostenergy = 100000,
		buildcostmetal = 3500,
		builder = false,
		buildpic = "sat_radar.dds",
		buildtime = 100000,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MOBILE SATELLITE",
		collide = false,
		cruisealt = 2500,
		description = "Radar/Sonar Stealth Satellite",
		energyuse = 0,
		explodeas = "BIG_UNITEX",
		footprintx = 5,
		footprintz = 5,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 6,
		maneuverleashlength = 1280,
		mass = 2500,
		maxdamage = 4850,
		maxslope = 10,
		maxvelocity = 2,
		maxwaterdepth = 0,
		mobilestandorders = 1,
		name = "Spoutnik",
		noautofire = false,
		objectname = "SAT_RADAR",
		onoffable = true,
		radardistance = 5000,
		radaremitheight = 6,
		selfdestructas = "SMALL_UNIT_VTOL",
		sightdistance = 1500,
		standingmoveorder = 1,
		stealth = true,
		steeringmode = 1,
		turninplaceanglelimit = 50,
		turninplacespeedlimit = 2,
		turnrate = 120,
		unitname = "sat_radar",
		usepiececollisionvolumes = true,
		usepieceselectionvolumes = true,
		customparams = {
			buildpic = "sat_radar.dds",
			faction = "ALL",
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
	},
}
