return {
	talon_pyroclastic = {
		acceleration = 0,
		activatewhenbuilt = true,
		brakerate = 0,
		buildangle = 8192,
		buildcostenergy = 77272,
		buildcostmetal = 5425,
		builder = false,
		buildpic = "talon_pyroclastic.dds",
		buildtime = 100000,
		canattack = true,
		canstop = 1,
		category = "ALL SURFACE UNDERWATER",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "115 40 115",
		collisionvolumetype = "box",
		corpse = "dead",
		defaultmissiontype = "GUARD_NOMOVE",
		description = "Armored Geothermal Plasma Tower",
		energymake = 1075,
		energystorage = 2048,
		explodeas = "LARGE_BUILDINGEX",
		firestandorders = 1,
		footprintx = 7,
		footprintz = 7,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 24,
		mass = 5425,
		maxdamage = 13155,
		maxslope = 10,
		maxvelocity = 0,
		maxwaterdepth = 0,
		name = "Pyroclastic",
		noautofire = false,
		objectname = "talon/talon_pyroclastic.s3o",
		radaremitheight = 25,
		seismicsignature = 0,
		selfdestructas = "ESTOR_BUILDING",
		sightdistance = 650,
		standingfireorder = 2,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0,
		turnrate = 0,
		unitname = "talon_pyroclastic",
		yardmap = "ooooooo ooooooo oooGooo ooGGGoo oooGooo ooooooo ooooooo",
		customparams = {
			buildpic = "talon_pyroclastic.dds",
			faction = "TALON",
			normaltex = "unittextures/talon_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "83 37 90",
				collisionvolumetype = "Box",
				damage = 5421,
				description = "Pyroclastic Wreckage",
				energy = 0,
				featuredead = "heap",
				footprintx = 5,
				footprintz = 5,
				metal = 3753,
				object = "talon/talon_pyroclastic_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				damage = 6777,
				description = "Pyroclastic Debris",
				energy = 0,
				footprintx = 5,
				footprintz = 5,
				metal = 2002,
				object = "5x5c.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			explosiongenerators = {
				"custom:armorco_muzzle",
			},
			pieceexplosiongenerators = {
				"piecetrail5",
				"piecetrail5",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			select = {
				"geothrm2",
			},
		},
		weapondefs = {
			carbuncle_rc = {
				accuracy = 500,
				areaofeffect = 64,
				avoidfeature = false,
				burnblow = true,
				cegtag = "carbuncleblaster",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:Explosion_Light_Plasma-2",
				impulseboost = 0.123,
				impulsefactor = 0.123,
				intensity = 3,
				name = "Carbuncle Blaster",
				noselfdamage = true,
				range = 700,
				reloadtime = 0.2,
				rgbcolor = "0.05 0.9 1.0",
				size = 1.2,
				soundhitdry = "xplomed3",
				soundhitwet = "splssml",
				soundhitwetvolume = 0.6,
				soundstart = "Mavgun2",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 500,
				damage = {
					default = 300,
					subs = 5,
				},
				tracks = false,
			},
		},
		weapons = {
			{
				badtargetcategory = "SMALL MINOR",
				def = "CARBUNCLE_RC",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}