return {
	talon_planetkiller = {
		acceleration = 0.005,
		activatewhenbuilt = false,
		airStrafe = true,
		airHoverFactor = 1,
		bankingAllowed = false,
		blocking = false,
		brakerate = 0.01,
		buildcostenergy = 106250000,
		buildcostmetal = 34187000,
		-- cost: 34187000 + (106250000/1000) × 16 = 35.9 million
		builder = false,
		buildpic = "talon_planetkiller.dds",
		buildtime = 45000000,
		canattack = true,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MOBILE SATELLITE",
		collide = false,
		cruisealt = 1750,
		collisionvolumeoffsets = "0 -10 0",
		collisionvolumescales = "360 200 360",
		collisionvolumetype = "ellipsoid",
		description = "Ultimate Energy Weapon Satellite",
		energystorage = 1500000,
		explodeas = "TSAR_DEATH",
		firestandorders = 1,
		footprintx = 25,
		footprintz = 25,
		hoverAttack = true,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 25,
		maneuverleashlength = 500,
		mass = 910000,
		maxdamage = 1450000,
		maxslope = 10,
		maxvelocity = 1,
		maxwaterdepth = 0,
		mobilestandorders = 1,
		name = "Planet Killer",
		noautofire = false,
		objectname = "talon/talon_planetkiller.s3o",
		radardistance = 0,
		radaremitheight = 25,
		seismicsignature = 0,
		selfdestructas = "TSAR_DEATH",
		selfdestructcountdown = 10,
		sightdistance = 2000,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 360,
		turninplacespeedlimit = 0.65,
		turnrate = 90,
		unitname = "talon_planetkiller",
		usepiececollisionvolumes = true,
		customparams = {
			buildpic = "talon_planetkiller.dds",
			faction = "TALON",
			normaltex = "unittextures/talon_normals.dds",
		},
		featuredefs = {},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			arrived = {
				"bigstop",
			},
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"biggo",
			},
			select = {
				"bigsel",
			},
		},
		weapondefs = {
			ultimate_weapon = {
				areaofeffect = 150,
				beamtime = 1,
				burnblow = true,
				collidefriendly = false,
				corethickness = 0.4,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 2,
				energypershot = 750000,
				explosiongenerator = "custom:RAVAGER",
				firestarter = 20,
				impulseboost = 0,
				impulsefactor = 0,
				largebeamlaser = true,
				laserflaresize = 10,
				name = "Antimatter accelerator",
				noexplode = true,
				noselfdamage = true,
				range = 3500,
				reloadtime = 1,
				rgbcolor = "0.1 0.9 1.0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.3,
				soundstart = "talon_accelerator",
				soundtrigger = 1,
				sweepfire = false,
				texture1 = "Type4Beam",
				texture2 = "NULL",
				texture3 = "NULL",
				texture4 = "EMG",
				thickness = 26,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 1500,
				damage = {
					default = 200000,
				},
				tracks = false,
			},
		},
		weapons = {
			{
				def = "ULTIMATE_WEAPON",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
