return {
	talon_opal = {
		acceleration = 0.06,
		amphibious = 1,
		brakerate = 0.714,
		buildcostenergy = 92900,
		buildcostmetal = 3480,
		builder = false,
		buildpic = "talon_opal.dds",
		buildtime = 45000,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL LARGE MOBILE SURFACE UNDERWATER",
		collisionvolumeoffsets = "0 -9 0",
		collisionvolumescales = "80 60 70",
		collisionvolumetype = "Ell",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Amphibious Assault Mech",
		explodeas = "CRAWL_BLASTSML",
		firestandorders = 1,
		footprintx = 4,
		footprintz = 4,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 37,
		maneuverleashlength = 640,
		mass = 3500,
		maxdamage = 9950,
		maxslope = 36,
		maxvelocity = 2.25,
		maxwaterdepth = 32,
		mobilestandorders = 1,
		movementclass = "HAKBOT4",
		name = "Opal",
		noautofire = false,
		objectname = "talon/talon_opal.s3o",
		radaremitheight = 37,
		seismicsignature = 0,
		selfdestructas = "CRAWL_BLAST",
		sightdistance = 550,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 2,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1.32,
		turnrate = 616,
		unitname = "talon_opal",
		upright = true,
		customparams = {
			buildpic = "talon_opal.dds",
			faction = "TALON",
			normaltex = "unittextures/talon_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "48 35 49",
				collisionvolumetype = "Box",
				damage = 8095,
				description = "talon_opal Wreckage",
				featuredead = "heap",
				footprintx = 3,
				footprintz = 3,
				metal = 2600,
				object = "talon/talon_opal_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				damage = 10119,
				description = "talon_opal Debris",
				energy = 0,
				footprintx = 3,
				footprintz = 3,
				metal = 1386,
				object = "3x3f.s3o",
				reclaimable = true,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"mavbok1",
			},
			select = {
				"mavbsel1",
			},
		},
		weapondefs = {
			talon_laser = {
				areaofeffect = 12,
				beamtime = 0.12,
				corethickness = 0.175,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:SMALL_RED_BURN",
				firestarter = 30,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				laserflaresize = 10,
				name = "Twin Rapid Talon Gun",
				noselfdamage = true,
				range = 650,
				reloadtime = 0.3,
				rgbcolor = "1.0 0.8 0.25",
				rgbcolor2 = "1.0 1.0 1.00",
				soundhitdry = "talongunhit",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "talongunfirerapid",
				soundtrigger = 1,
				sweepfire = false,
				targetmoveerror = 0.1,
				thickness = 1,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 850,
				damage = {
					default = 75,
					subs = 5,
				},
				tracks = false,
			},
			talon_torpedo = {
				areaofeffect = 16,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASH2",
				flighttime = 2.3,
				impactonly = 1,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				model = "weapon_torpedo.s3o",
				name = "Torpedo",
				noselfdamage = true,
				range = 450,
				reloadtime = 1.5,
				soundhitdry = "xplodep1",
				soundhitwet = "xplodep1",
				soundstart = "torpedo1",
				startvelocity = 100,
				turnrate = 8000,
				turret = true,
				waterweapon = true,
				weaponacceleration = 15,
				weapontimer = 3,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 160,
				damage = {
					default = 300,
				},
				tracks = false,
			},
		},
		weapons = {
			{
				def = "TALON_LASER",
				onlytargetcategory = "SURFACE",
			},
			{
				def = "TALON_LASER",
				onlytargetcategory = "SURFACE",
				slaveto = 1,
			},
			{
				def = "TALON_TORPEDO",
				onlytargetcategory = "UNDERWATER",
			},
		},
	},
}