return {
	talon_edrag = {
		buildangle = 0,
		buildcostenergy = 15000,
		buildcostmetal = 850,
		builder = false,
		buildpic = "talon_edrag.dds",
		buildtime = 20000,
		category = "ALL SURFACE",
		collisionvolumeoffsets = "0 -3 0",
		collisionvolumescales = "64 100 64",
		collisionvolumetype = "CylY",
		corpse = "fortification",
		description = "Perimeter Defense",
		footprintx = 4,
		footprintz = 4,
		idleautoheal = 5,
		idletime = 1800,
		isfeature = true,
		levelground = false,
		losemitheight = 50,
		mass = 850,
		maxdamage = 5000,
		maxslope = 24,
		maxvelocity = 0,
		maxwaterdepth = 0,
		name = "Experimental Wall",
		noautofire = false,
		objectname = "talon_edrag",
		radaremitheight = 100,
		script = "drag.lua",
		unitname = "talon_edrag",
		yardmap = "ffff ffff ffff ffff",
		customparams = {
			buildpic = "talon_edrag.dds",
			faction = "talon",
		},
		featuredefs = {
			fortification = {
				autoreclaimable = 0,
				blocking = true,
				category = "dragonteeth",
				crushResistance = 5000,
				collisionvolumeoffsets = "0 -3 0",
				collisionvolumescales = "64 100 64",
				collisionvolumetest = 1,
				collisionvolumetype = "CylY",
				damage = 200000,
				description = "Fortification Wall",
				featuredead = "rockteethx",
				featurereclamate = "smudge01",
				footprintx = 4,
				footprintz = 4,
				height = 55,
				hitdensity = 100,
				metal = 650,
				nodrawundergray = true,
				object = "talon_edrag",
				reclaimable = true,
				reclaimtime = 10000,
				seqnamereclamate = "tree1reclamate",
				world = "allworld",
				customparams = {
					fromunit = 1,
				},
			},
			rockteethx = {
				animating = 0,
				animtrans = 0,
				blocking = true,
				category = "rocks",
				damage = 20000,
				description = "Rubble",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 290,
				object = "2X2A",
				reclaimable = true,
				shadtrans = 1,
				world = "greenworld",
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
	},
}
