return {
	talon_builderlvl3 = {
		acceleration = 0.015,
		airhoverfactor = 0,
		brakerate = 0.35,
		buildcostenergy = 845004,
		buildcostmetal = 35351,
		builddistance = 320,
		builder = true,
		buildpic = "talon_builderlvl3.dds",
		buildtime = 1200000,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canreclaim = true,
		canstop = 1,
		category = "ALL MOBILE VTOL",
		collide = false,
		collisionvolumescales = "115 50 115",
		collisionvolumetype = "CylY",
		corpse = "dead",
		cruisealt = 180,
		description = "Tech Level 5",
		dontland = 0,
		energymake = 400,
		energystorage = 800,
		explodeas = "SHIPBLAST",
		footprintx = 5,
		footprintz = 5,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 41,
		mass = 27150,
		maxdamage = 18985,
		maxslope = 10,
		maxvelocity = 1.5,
		maxwaterdepth = 0,
		metalmake = 3.75,
		metalstorage = 100,
		name = "Construction Ship",
		objectname = "talon/talon_builderlvl3.s3o",
		reclaimspeed = 1500,
		repairspeed = 1500,
		selfdestructas = "SHIPBLAST",
		shownanospray = false,
		sightdistance = 400,
		turninplaceanglelimit = 360,
		turninplacespeedlimit = 2.112,
		turnrate = 400,
		unitname = "talon_builderlvl3",
		workertime = 3000,
		buildoptions = {
			[1] = "talon_ufus",
			[2] = "talon_mas",
			[3] = "talon_metalmakerlvl4",
			[4] = "talon_ulab",
			[5] = "talon_covertopscentre",
			[6] = "talon_nanotc4",
			--[7] = "talon_urad",
			[8] = "talon_talpax",
			[9] = "talon_pyramid",
			[10] = "talon_gate3",
			[11] = "talon_damascus2",
			[12] = "talon_elixir",
			[13] = "talon_dmc",
			[14] = "talon_veloute1",
			[15] = "talon_planetkiller",
			--[16] = "talon_cerberus",
		},
		customparams = {
			buildpic = "talon_builderlvl3.dds",
			faction = "TALON",
			normaltex = "unittextures/talon_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = false,
				damage = 5148,
				description = "Builder Level 4 Wreckage",
				footprintx = 4,
				footprintz = 8,
				metal = 19599,
				object = "talon/talon_builderlvl3_dead.s3o",
				reclaimable = true,
			},
		},
		nanocolor = {
			[1] = 0.8,
			[2] = 1,
			[3] = 0.8,
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			arrived = {
				[1] = "armshipstop",
			},
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "armshipgo",
			},
			select = {
				[1] = "armselect",
			},
		},
	},
}
