return {
	talon_eck = {
		acceleration = 0.12,
		brakerate = 0.75,
		buildcostenergy = 113635,
		buildcostmetal = 5878,
		builddistance = 400,
		builder = true,
		buildpic = "talon_eck.dds",
		buildtime = 150000,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canreclaim = true,
		canstop = 1,
		category = "ALL LARGE MOBILE SURFACE UNDERWATER",
		collisionvolumeoffsets = "0 -5 0",
		collisionvolumescales = "60 50 60",
		collisionvolumetype = "Box",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Tech Level 3",
		energymake = 75,
		energystorage = 100,
		explodeas = "BIG_UNITEX",
		footprintx = 4,
		footprintz = 4,
		healtime = 8,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 34,
		maneuverleashlength = 640,
		mass = 5878,
		maxdamage = 5075,
		maxslope = 17,
		maxvelocity = 1.6,
		maxwaterdepth = 22,
		metalmake = 0.4,
		metalstorage = 100,
		mobilestandorders = 1,
		movementclass = "HKBOT4",
		name = "Construction Kbot",
		noautofire = false,
		objectname = "talon/talon_eck.s3o",
		radaremitheight = 34,
		reclaimspeed = 240,
		repairspeed = 240,
		selfdestructas = "CRAWL_BLASTSML",
		shownanospray = false,
		sightdistance = 520,
		standingmoveorder = 1,
		steeringmode = 2,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1.6,
		turnrate = 650,
		unitname = "talon_eck",
		upright = true,
		workertime = 480,
		buildoptions = {
			"talon_sfus",
			"talon_egeo",
			"talon_emex",
			"talon_metalmakerlvl2",
			"talon_emstor",
			"talon_eestor",
			"talon_clone_lab",
			"talon_alab",
			"talon_elab",
			"talon_ulab",
			"talon_nanotc2",
			"talon_edrag",
			"talon_conspiracy2",
			"talon_blt1",
			"talon_popcorn1",
			"talon_gate4",
			"talon_damascus1",
			"talon_silo1",
			"talon_lrpt1",
			"talon_veloute2",
			"portal",
		},
		customparams = {
			buildpic = "talon_eck.dds",
			faction = "TALON",
			normaltex = "unittextures/talon_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 915,
				description = "Holo Wreckage",
				energy = 0,
				footprintx = 2,
				footprintz = 2,
				metal = 217,
				object = "talon/talon_eck_dead.s3o",
				reclaimable = true,
			},
		},
		nanocolor = {
			0.22,
			0.57,
			0.57,
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			capture = "capture2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"kbcormov",
			},
			select = {
				"kbcorsel",
			},
		},
		weapondefs = {
			talon_laser = {
				areaofeffect = 12,
				beamtime = 0.12,
				corethickness = 0.175,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:SMALL_RED_BURN",
				firestarter = 30,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				laserflaresize = 10,
				name = "Light Rapid Talon Gun",
				noselfdamage = true,
				range = 550,
				reloadtime = 0.3,
				rgbcolor = "1.0 0.8 0.25",
				rgbcolor2 = "1.0 1.0 1.00",
				soundhitdry = "talongunhit",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "talongunfirerapid",
				soundtrigger = 1,
				sweepfire = false,
				targetmoveerror = 0.1,
				thickness = 1,
				tolerance = 500,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 850,
				damage = {
					default = 45,
					subs = 5,
				},
				tracks = false,
			},
		},
		weapons = {
			{
				def = "TALON_LASER",
				maindir = "0 0 1",
				maxangledif = 270,
				onlytargetcategory = "SURFACE",
			},
		},
	},
}