-- UNITDEF -- TAWF015 --
--------------------------------------------------------------------------------

local unitName = "tawf015"

--------------------------------------------------------------------------------

local unitDef = {
  acceleration       = 0.2,
  badTargetCategory  = [[NOTAIR]],
  bankscale          = 1,
  bmcode             = 1,
  brakeRate          = 5,
  buildCostEnergy    = 3600,
  buildCostMetal     = 225,
  builder            = false,
  buildPic           = [[TAWF015.png]],
  buildTime          = 1800,
  canAttack          = true,
  canFly             = true,
  canGuard           = true,
  canMove            = true,
  canPatrol          = true,
  canstop            = 1,
  category           = [[MOBILE LEVEL3 VTOL ALL]],
  collide            = false,
  cruiseAlt          = 200,
  defaultmissiontype = [[VTOL_standby]],
  description        = [[Heavy Fighter]],
  energyMake         = 0.6,
  energyStorage      = 0,
  energyUse          = 0.6,
  explodeAs          = [[BIG_UNITEX]],
  firestandorders    = 1,
  footprintX         = 3,
  footprintZ         = 3,
  hoverAttack        = true,
  iconType           = [[air]],
  idleAutoHeal       = 5,
  idleTime           = 1800,
  maneuverleashlength = 1280,
  maxDamage          = 1000,
  maxSlope           = 20,
  maxVelocity        = 9,
  maxWaterDepth      = 0,
  metalStorage       = 0,
  mobilestandorders  = 1,
  name               = [[Liberty]],
  noAutoFire         = false,
  noChaseCategory    = [[NOTAIR]],
  objectName         = [[TAWF015]],
  scale              = 1,
  seismicSignature   = 0,
  selfDestructAs     = [[BIG_UNIT]],
  side               = [[ARM]],
  sightDistance      = 550,
  smoothAnim         = true,
  standingfireorder  = 2,
  standingmoveorder  = 1,
  stealth            = true,
  steeringmode       = 1,
  TEDClass           = [[VTOL]],
  turnRate           = 3000,
  unitname           = [[tawf015]],
  workerTime         = 0,
  wter_badtargetcategory = [[NOTAIR]],
  sounds = {
    canceldestruct     = [[cancel2]],
    underattack        = [[warning1]],
    cant = {
      [[cantdo4]],
    },
    count = {
      [[count6]],
      [[count5]],
      [[count4]],
      [[count3]],
      [[count2]],
      [[count1]],
    },
    ok = {
      [[vtolarmv]],
    },
    select = {
      [[vtolarac]],
    },
  },
  weapons = {
    [1]  = {
      badTargetCategory  = [[NOTAIR]],
      def                = [[Katana_M]],
    },
    [2]  = {
      def                = [[Katana_M2]],
      onlyTargetCategory = [[VTOL]],
    },
    [3]  = {
      def                = [[Katana_M]],
    },
  },
}


--------------------------------------------------------------------------------

local weaponDefs = {
  Katana_M = {
    areaOfEffect       = 16,
    collideFriendly    = false,
    craterBoost        = 0,
    craterMult         = 0,
    edgeEffectiveness  = 0.5,
    explosionGenerator = [[custom:FLASHSMALLBUILDINGEX]],
    fireStarter        = 70,
    guidance           = true,
    impulseBoost       = 0.123,
    impulseFactor      = 0.123,
    lineOfSight        = true,
    metalpershot       = 0,
    model              = [[missile3g]],
    name               = [[Advanced Guided Missiles]],
    noSelfDamage       = true,
    pitchtolerance     = 18000,
    range              = 650,
    reloadtime         = 4,
    renderType         = 1,
    selfprop           = true,
    smokedelay         = 0.1,
    smokeTrail         = true,
    soundHit           = [[xplosml2]],
    soundStart         = [[Rocklit3]],
    startsmoke         = 1,
    startVelocity      = 300,
    tolerance          = 8000,
    tracks             = true,
    turnRate           = 40000,
    weaponAcceleration = 100,
    weaponType         = [[MissileLauncher]],
    weaponVelocity     = 600,
    damage = {
      bombers            = 800,
      commanders         = 25,
      default            = 50,
      fighters           = 500,
      gunships           = 400,
      hgunships          = 500,
      subs               = 3,
      vtols              = 100,
    },
  },
  Katana_M2 = {
    areaOfEffect       = 16,
    collideFriendly    = false,
    craterBoost        = 0,
    craterMult         = 0,
    edgeEffectiveness  = 0.95,
    explosionGenerator = [[custom:FLASH2]],
    fireStarter        = 85,
    guidance           = true,
    impulseBoost       = 0.123,
    impulseFactor      = 0.123,
    lineOfSight        = true,
    model              = [[quadmissile3g]],
    name               = [[4 Missiles pack]],
    noSelfDamage       = true,
    pitchtolerance     = 18000,
    range              = 650,
    reloadtime         = 0.5,
    renderType         = 1,
    selfprop           = true,
    smokedelay         = 0.1,
    smokeTrail         = true,
    soundHit           = [[xplosml2]],
    soundStart         = [[Rocklit3]],
    startsmoke         = 1,
    startVelocity      = 400,
    tolerance          = 8000,
    tracks             = true,
    turnRate           = 40000,
    weaponAcceleration = 200,
    weaponType         = [[MissileLauncher]],
    weaponVelocity     = 700,
    damage = {
      bombers            = 1060,
      commanders         = 3,
      default            = 6,
      fighters           = 464,
      gunships           = 480,
      hgunships          = 680,
      subs               = 3,
      vtols              = 250,
    },
  },
}
unitDef.weaponDefs = weaponDefs


--------------------------------------------------------------------------------

return lowerkeys({ [unitName] = unitDef })

--------------------------------------------------------------------------------
