-- UNITDEF -- TAWF010 --
--------------------------------------------------------------------------------

local unitName = "tawf010"

--------------------------------------------------------------------------------

local unitDef = {
	bmcode = 0,
	buildAngle = 8192,
	buildCostEnergy = 42468,
	buildCostMetal = 2122,
	builder = false,
	buildingGroundDecalDecaySpeed = 30,
	buildingGroundDecalSizeX = 5,
	buildingGroundDecalSizeY = 5,
	buildingGroundDecalType = [[tawf010_aoplane.dds]],
	buildTime = 45675,
	canAttack = true,
	canstop = 1,
	category = [[ALL NOTHOVERNOTVTOL NOTMOBILE NOTSUB NOTSUBNOTSHIP NOTVTOL WEAPON]],
	collisionVolumeOffsets = [[0 -10 0]],
	collisionVolumeScales = [[71 111 71]],
	collisionVolumeTest = 1,
	collisionVolumeType = [[ellipsoid]],
	corpse = [[dead]],
	defaultmissiontype = [[GUARD_NOMOVE]],
	description = [[Heavy Rocket Defense Weapon]],
	designation = [[TAWF-18]],
	energyStorage = 200,
	energyUse = 30,
	explodeAs = [[LARGE_BUILDINGEX]],
	firestandorders = 1,
	footprintX = 3,
	footprintZ = 3,
	maxDamage = 12540,
	maxSlope = 20,
	maxWaterDepth = 0,
	metalStorage = 0,
	name = [[Enforcer]],
	noAutoFire = false,
	noChaseCategory = [[ALL]],
	objectName = [[TAWF010]],
	radarDistance = 0,
	selfDestructAs = [[LARGE_BUILDING]],
	shootme = 1,
	side = [[ARM]],
	sightDistance = 400,
	standingfireorder = 2,
	unitname = [[tawf010]],
	unitnumber = 39,
	useBuildingGroundDecal = true,
	workerTime = 0,
	yardMap = [[ooo ooo ooo]],
	featureDefs = nil,
	sounds = {
		canceldestruct = [[cancel2]],
		underattack = [[warning1]],
		cant = {
			[1] = [[cantdo4]],
		},
		count = {
			[1] = [[count6]],
			[2] = [[count5]],
			[3] = [[count4]],
			[4] = [[count3]],
			[5] = [[count2]],
			[6] = [[count1]],
		},
		ok = {
			[1] = [[anni]],
		},
		select = {
			[1] = [[anni]],
		},
	},
	weaponDefs = nil,
	weapons = {
		[1] = {
			badTargetCategory = [[TINY]],
			def = [[TAWF010_weapon]],
			onlyTargetCategory = [[NOTVTOL]],
		},
		[2] = {
			badTargetCategory = [[TINY]],
			def = [[TAWF010b_weapon]],
			onlyTargetCategory = [[NOTVTOL]],
		},
		[3] = {
			badTargetCategory = [[TINY]],
			def = [[TAWF010b_weapon]],
			onlyTargetCategory = [[NOTVTOL]],
		},
	},
}

--------------------------------------------------------------------------------

local weaponDefs = {
	TAWF010_weapon = {
		areaOfEffect = 48,
		craterBoost = 0,
		craterMult = 0,
		fireStarter = 70,
		guidance = true,
		impulseBoost = 0.123,
		impulseFactor = 0.123,
		lineOfSight = true,
		metalpershot = 0,
		model = [[010weap]],
		name = [[Tachyon Cannon]],
		noSelfDamage = true,
		range = 1200,
		reloadtime = 2,
		renderType = 1,
		rgbColor = [[1 0.95 0.9]],
		selfprop = true,
		size = 1.36,
		smokedelay = 0.1,
		smokeTrail = false,
		soundHitDry = [[HIT010]],
		soundStart = [[FIRE010]],
		startVelocity = 450,
		tolerance = 9000,
		tracks = true,
		turnRate = 30000,
		turret = true,
		weaponAcceleration = 101,
		weaponTimer = 5,
		weaponType = [[Cannon]],
		weaponVelocity = 450,
		damage = {
			default = 330,
			experimental_ships = 660,
			ships = 495,
			subs = 5,
		},
	},
	TAWF010b_weapon = {
		areaOfEffect = 101,
		craterBoost = 0,
		craterMult = 0,
		fireStarter = 70,
		guidance = true,
		id = 238,
		impulseBoost = 0.123,
		impulseFactor = 0.123,
		lineOfSight = true,
		model = [[rpack]],
		name = [[Mammoth Rocket Pack]],
		noSelfDamage = true,
		range = 1050,
		reloadtime = 9,
		renderType = 1,
		rgbColor = [[1 0.95 0.9]],
		selfprop = true,
		size = 1.86,
		smokedelay = 1.01,
		smokeTrail = false,
		soundHitDry = [[kill]],
		soundStart = [[shoot]],
		startVelocity = 650,
		tolerance = 9000,
		tracks = true,
		turnRate = 3000,
		turret = true,
		weaponAcceleration = 112,
		weaponTimer = 5,
		weaponType = [[Cannon]],
		weaponVelocity = 650,
		damage = {
			default = 2100,
			experimental_ships = 4200,
			ships = 3150,
			subs = 5,
		},
	},
}
unitDef.weaponDefs = weaponDefs


--------------------------------------------------------------------------------

local featureDefs = {
	dead = {
		blocking = true,
		category = [[arm_corpses]],
		damage = 0.6000 * unitDef.maxDamage,
		description = unitDef.name .. [[ Wreckage]],
		featureDead = [[heap]],
		featurereclamate = [[smudge01]],
		footprintX = 3,
		footprintZ = 3,
		height = 60,
		hitdensity = 100,
		metal = 0.8000 * unitDef.buildCostMetal,
		object = [[TAWF010_dead]],
		reclaimable = true,
		seqnamereclamate = [[tree1reclamate]],
		world = [[All Worlds]],
	},
	heap = {
		blocking = false,
		category = [[heaps]],
		damage = 0.3600 * unitDef.maxDamage,
		description = unitDef.name .. [[ Heap]],
		featurereclamate = [[smudge01]],
		footprintX = 3,
		footprintZ = 3,
		height = 6,
		hitdensity = 100,
		metal = 0.6400 * unitDef.buildCostMetal,
		object = [[3x3a]],
		reclaimable = true,
		seqnamereclamate = [[tree1reclamate]],
		world = [[All Worlds]],
	},
}
unitDef.featureDefs = featureDefs

--------------------------------------------------------------------------------

return lowerkeys({[unitName] = unitDef})

--------------------------------------------------------------------------------
