return {
	tll_neobahomet = {
		acceleration = 0.005,
		brakerate = 0.18,
		buildcostenergy = 4285000,
		buildcostmetal = 485400,
		builder = false,
		buildpic = "tll_neobahomet.dds",
		buildtime = 12500000,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		cantbetransported = true,
		category = "ALL MAJOR MOBILE SURFACE UNDERWATER",
		collisionvolumeoffsets = "0 -25 0",
		collisionvolumescales = "160 240 230",
		collisionvolumetype = "CylZ",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Titan Amphibious Vehicle",
		energystorage = 10000,
		explodeas = "MKL_BLAST",
		firestandorders = 1,
		footprintx = 14,
		footprintz = 16,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 145,
		maneuverleashlength = 640,
		mass = 485400,
		maxdamage = 684000,
		maxslope = 12,
		maxvelocity = 0.8,
		maxwaterdepth = 255,
		mobilestandorders = 1,
		movementclass = "ATANK14",
		name = "Neo Bahomet",
		noautofire = false,
		objectname = "tll/tll_neobahomet.s3o",
		radaremitheight = 145,
		selfdestructas = "MEGA_BLAST",
		selfdestructcountdown = 10,
		sightdistance = 1400,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplace = 0,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0.66,
		turnrate = 125,
		unitname = "tll_neobahomet",
		customparams = {
			buildpic = "tll_neobahomet.dds",
			faction = "TLL",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 1023165,
				description = "Neo Bahomet Wreckage",
				featuredead = "heap",
				footprintx = 7,
				footprintz = 7,
				metal = 507200,
				object = "tll/tll_neobahomet_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				damage = 28956,
				description = "Samael Debris",
				footprintx = 7,
				footprintz = 7,
				metal = 293840,
				object = "6x6c",
				reclaimable = true,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				"custom:tll_spray_muzzle",
				"custom:mediumflare_front_only",
				"custom:tll_muzzle",
			},
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tarmmove",
			},
			select = {
				[1] = "tarmsel",
			},
		},
		weapondefs = {
			tll_blast = {
				areaofeffect = 452,
				avoidfeature = false,
				burnblow = true,
				cegtag = "tllblaster",
				craterareaofeffect = 225,
				energypershot = 15000,
				explosiongenerator = "custom:explosion_huge_tll",
				impulseboost = 0.123,
				impulsefactor = 0.123,
				intensity = 6,
				name = "Impulsion Blaster",
				noselfdamage = true,
				range = 2500,
				reloadtime = 8,
				rgbcolor = "0.8 0.8 0.15",
				size = 5,
				soundhitdry = "sizzle",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "Lasrhvy2",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 900,
				damage = {
					commanders = 12500,
					default = 50000,
					subs = 5,
				},
			},
			gauss_tll = {
				alphaDecay = 0.5,
				areaofeffect = 32,
				avoidfeature = false,
				cegtag = "GAUSS_HIT_M",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				impulseboost = 0,
				impulsefactor = 0,
				name = "Gauss",
				nogap = 1,
				noselfdamage = true,
				range = 1200,
				reloadtime = 2,
				rgbcolor = "0.9 0.9 0.2",
				size = 0.8,
				sizedecay = -0.1,
				soundhitdry = "soft_crunch",
				soundhitwet = "splsmed",
				soundhitwetvolume = 0.6,
				soundstart = "tllgauss",
				stages = 32,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 850,
				damage = {
					default = 6400,
					subs = 5,
				},
			},
			cannon = {
				accuracy = 375,
				alphadecay = 0.3,
				areaofeffect = 175,
				avoidfeature = false,
				cegtag = "Trail_cannon",
				craterareaofeffect = 196,
				craterboost = 0,
				cratermult = 0,
				energypershot = 500,
				gravityaffected = "TRUE",
				name = "Heavy Plasma Cannon",
				nogap = 1,
				range = 2500,
				reloadtime = 0.3,
				separation = 0.45,
				size = 1,
				sizedecay = -0.15,
				soundhitdry = "S_rocket_hit",
				soundhitwet = "splslrg",
				soundhitwetvolume = 0.6,
				soundstart = "tyrnt_fire",
				stages = 20,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 742,
				damage = {
					default = 450,
					subs = 5,
				},
			},
			tll_lightning = {
				areaofeffect = 10,
				beamTTL = 10,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 1,
				energypershot = 100,
				explosiongenerator = "custom:tll_spray_exp",
				firestarter = 50,
				impactonly = true,
				impulseboost = 0,
				impulsefactor = 0,
				name = "Spray Lightning",
				noselfdamage = true,
				range = 600,
				reloadtime = 1,
				rgbcolor = "0.9 0.9 0.2",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "tllspark",
				soundtrigger = 1,
				texture1 = "spray",
				thickness = 8,
				turret = true,
				weapontype = "LightningCannon",
				customparams = {
					light_mult = 1.4,
					light_radius_mult = 0.9,
				},
				damage = {
					default = 500,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "HUGE LARGE MEDIUM SMALL MINOR",
				def = "TLL_BLAST",
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				badtargetcategory = "LARGE MEDIUM SMALL MINOR",
				def = "CANNON",
				maindir = "0 0 1",
				maxangledif = 220,
				onlytargetcategory = "SURFACE",
			},
			[3] = {
				badtargetcategory = "LARGE MEDIUM SMALL MINOR",
				def = "CANNON",
				maindir = "0 0 -1",
				maxangledif = 220,
				onlytargetcategory = "SURFACE",
			},
			[4] = {
				def = "GAUSS_TLL",
				maindir = "0 0 1",
				maxangledif = 220,
				onlytargetcategory = "SURFACE",
			},
			[5] = {
				def = "GAUSS_TLL",
				maindir = "0 0 -1",
				maxangledif = 220,
				onlytargetcategory = "SURFACE",
			},
			[6] = {
				def = "TLL_LIGHTING",
				maindir = "1 0 0.5",
				maxangledif = 220,
				onlytargetcategory = "SURFACE",
			},
			[7] = {
				def = "TLL_LIGHTING",
				maindir = "0.5 0 0.5",
				maxangledif = 220,
				onlytargetcategory = "SURFACE",
			},
			[8] = {
				def = "TLL_LIGHTING",
				maindir = "0.8 0 -0.2",
				maxangledif = 220,
				onlytargetcategory = "SURFACE",
			},
			[9] = {
				def = "TLL_LIGHTING",
				maindir = "-0.5 0 0.5",
				maxangledif = 220,
				onlytargetcategory = "SURFACE",
			},
			[10] = {
				def = "TLL_LIGHTING",
				maindir = "-0.5 0 1",
				maxangledif = 220,
				onlytargetcategory = "SURFACE",
			},
			[11] = {
				def = "TLL_LIGHTING",
				maindir = "-0.8 0 -0.2",
				maxangledif = 220,
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
