local Def = {
	tllarchnano = {
		acceleration = 0.36,
		bmcode = 1,
		brakeRate = 0.07,
		buildCostEnergy = 2636,
		buildCostMetal = 357,
		buildDistance = 200,
		buildTime = 13917,
		builder = true,
		cainrepair = 1,
		canCapture = true,
		canGuard = true,
		canMove = true,
		canPatrol = true,
		canreclamate = 1,
		canstop = 1,
		category = [[TLL TANK LEVEL3 CONSTR NOWEAPON NOTAIR NOTSUB ]],
		copyright = [[Copyright 1997 Humongous Entertainment. All rights reserved.]],
		corpse = [[dead]],
		defaultmissiontype = [[Standby]],
		description = [[Ampibious Repair K-bot]],
		designation = [[]],
		energyMake = 11,
		energyUse = 3,
		explodeAs = [[BIG_UNITEX]],
		featureDefs = {
			dead = {
				blocking = true,
				category = [[tll_corpses]],
				damage = nil,
				description = [[Wreckage]],
				featureDead = [[heap]],
				featurereclamate = [[smudge01]],
				footprintX = 3,
				footprintZ = 3,
				height = 21,
				hitdensity = 105,
				metal = nil,
				object = [[TLLARCHNANO_dead]],
				reclaimable = true,
				seqnamereclamate = [[tree1reclamate]],
				world = [[All Worlds]],
			},
			heap = {
				blocking = false,
				category = [[heaps]],
				damage = nil,
				description = [[Wreckage]],
				featurereclamate = [[smudge01]],
				footprintX = 3,
				footprintZ = 3,
				height = 2,
				hitdensity = 105,
				metal = nil,
				object = [[3x3a]],
				reclaimable = true,
				seqnamereclamate = [[tree1reclamate]],
				world = [[All Worlds]],
			},
		},
		footprintX = 2,
		footprintZ = 2,
		frenchdescription = [[KBot de reparation amphibie]],
		germandescription = [[Amphibischer Reparatur KBot]],
		maneuverleashlength = 320,
		maxDamage = 1705,
		maxSlope = 255,
		maxVelocity = 3,
		maxWaterDepth = 255,
		metalMake = 0.4,
		mobilestandorders = 1,
		movementClass = [[AKBOT2]],
		name = [[Archnano]],
		noAutoFire = false,
		objectName = [[TLLARCHNANO]],
		ovradjust = 1,
		radarDistance = 100,
		selfDestructAs = [[BIG_UNIT]],
		shootme = 1,
		side = [[TLL]],
		sightDistance = 305,
		smoothAnim = true,
		sonarDistance = 100,
		sounds = {
			arrived = {
				[1] = [[spider]],
			},
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[tllspidcant]],
			},
			count = {
				[1] = [[tllcount]],
				[2] = [[tllcount]],
				[3] = [[tllcount]],
				[4] = [[tllcount]],
				[5] = [[tllcount]],
				[6] = [[tllcount]],
			},
			ok = {
				[1] = [[spider]],
			},
			select = {
				[1] = [[tllspidsel]],
			},
			underattack = [[tllwarning]],
		},
		standingmoveorder = 1,
		steeringmode = 1,
		threed = 1,
		turnRate = 1020,
		unitname = [[tllarchnano]],
		unitnumber = 877,
		version = 3.1,
		workerTime = 280,
		zbuffer = 1,
	},
}
Def.tllarchnano.featureDefs.dead.damage = 0.6000 * Def.tllarchnano.maxDamage
Def.tllarchnano.featureDefs.dead.metal = 0.8000 * Def.tllarchnano.buildCostMetal
Def.tllarchnano.featureDefs.heap.damage = 0.3600 * Def.tllarchnano.maxDamage
Def.tllarchnano.featureDefs.heap.metal = 0.6400 * Def.tllarchnano.buildCostMetal
return lowerkeys(Def)
