return {
	tllanvil = {
		acceleration = 0.4,
		badtargetcategory = "VTOL",
		brakerate = 1.2,
		buildcostenergy = 225014,
		buildcostmetal = 17673,
		builder = false,
		buildpic = "tllanvil.dds",
		buildtime = 803500,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MOBILE LARGE SURFACE UNDERWATER",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "66 66 80",
		collisionvolumetype = "CylZ",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Ultimate Unit Paralyser",
		explodeas = "twilight_big",
		firestandorders = 1,
		footprintx = 4,
		footprintz = 4,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 41,
		maneuverleashlength = 640,
		mass = 17673,
		maxdamage = 12500,
		maxslope = 25,
		maxvelocity = 1.1,
		maxwaterdepth = 12,
		mobilestandorders = 1,
		movementclass = "HTANK4",
		name = "Anvil",
		noautofire = false,
		objectname = "tll/tllanvil.s3o",
		radardistance = 0,
		radaremitheight = 40,
		selfdestructas = "twilight_big",
		sightdistance = 570,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplace = 0,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0.726,
		turnrate = 300,
		unitname = "tllanvil",
		customparams = {
			buildpic = "tllanvil.dds",
			faction = "TLL",
			normaltex = "unittextures/tll_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				catagory = "corpses",
				damage = 9345,
				description = "Anvil Wreckage",
				featuredead = "heap",
				footprintx = 4,
				footprintz = 4,
				metal = 13162,
				object = "tll/tllanvil_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				catagory = "heaps",
				damage = 11681,
				description = "Anvil Debris",
				footprintx = 4,
				footprintz = 4,
				metal = 7020,
				object = "4x4a.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"tcormove",
			},
			select = {
				"tcorsel",
			},
		},
		weapondefs = {
			anchorempbeam = {
				areaofeffect = 8,
				beamtime = 0.1,
				corethickness = 0.2,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.1,
				energypershot = 2500,
				explosiongenerator = "custom:SMALL_YELLOW_BURN",
				firestarter = 50,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				intensity = 0.5,
				laserflaresize = 1.75,
				name = "EMP Laser",
				noselfdamage = true,
				paralyzer = true,
				paralyzetime = 6,
				range = 1200,
				reloadtime = 0.25,
				rgbcolor = "0 0 1",
				soundhitdry = "lashit",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "lasrlit1",
				soundtrigger = true,
				targetmoveerror = 0.1,
				thickness = 0.75,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 1000,
				damage = {
					commanders = 2500,
					default = 25000,
					subs = 5,
				},
				tracks = false,
			},
		},
		weapons = {
			{
				def = "AnchorEmpBeam",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}