return {
	tllgizmo = {
		acceleration = 0.1,
		brakerate = 0.45,
		buildcostenergy = 14207,
		buildcostmetal = 1275,
		builddistance = 250,
		builder = true,
		buildpic = "tllgizmo.dds",
		buildtime = 15000,
		canassist = false,
		canattack = true,
		cancapture = true,
		canguard = false,
		canmove = true,
		canpatrol = false,
		canreclaim = false,
		canrepair = false,
		canrestore = false,
		canstop = 1,
		category = "ALL MEDIUM MOBILE SURFACE UNDERWATER",
		cloakcost = 150,
		cloakcostmoving = 450,
		collisionvolumeoffsets = "0 -6 2",
		collisionvolumescales = "24 45 20",
		collisionvolumetype = "Box",
		decloakspherical = true,
		defaultmissiontype = "Standby",
		description = "Paratrooping Capture Kbot",
		explodeas = "SMALL_UNIT",
		firestandorders = 0,
		firestate = 0,
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 31,
		maneuverleashlength = 640,
		mass = 1275,
		maxdamage = 3450,
		maxslope = 20,
		maxvelocity = 1.75,
		maxwaterdepth = 15,
		mincloakdistance = 75,
		mobilestandorders = 1,
		movementclass = "KBOT2",
		name = "Gizmo",
		noautofire = false,
		objectname = "tll/tllgizmo.s3o",
		radaremitheight = 31,
		seismicsignature = 2,
		selfdestructas = "SMALL_UNIT",
		shownanospray = false,
		sightdistance = 350,
		standingfireorder = 0,
		standingmoveorder = 1,
		stealth = false,
		steeringmode = 2,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1.254,
		turnrate = 1016,
		unitname = "tllgizmo",
		upright = true,
		workertime = 2000,
		buildoptions = {
			"tlltplane",
			"tllspy",
			"tlltower",
			"tllradar",
			"tlljam",
			"tlladt",
			"tllmine2",
			"tllmine4",
			"tllmine5",
		},
		customparams = {
			buildpic = "tllgizmo.dds",
			faction = "TLL",
			initcloaked = true,
			paralyzemultiplier = 0.15,
		},
		nanocolor = {
			0.8,
			1,
			1,
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			capture = "capture2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"kbcormov",
			},
			select = {
				"kbcorsel",
			},
		},
		weapondefs = {
			tllgizmolas = {
				areaofeffect = 8,
				beamtime = 0.1,
				burstrate = 0.2,
				corethickness = 0.2,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.1,
				explosiongenerator = "custom:SMALL_YELLOW_BURN",
				firestarter = 50,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				intensity = 0.5,
				laserflaresize = 1.25,
				name = "EMP Laser",
				noselfdamage = true,
				paralyzer = true,
				paralyzetime = 6,
				range = 450,
				reloadtime = 0.5,
				rgbcolor = "0 0 1",
				soundhitdry = "lashit",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "lasrlit1",
				soundtrigger = true,
				targetmoveerror = 0.1,
				thickness = 0.75,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 600,
				damage = {
					default = 3000,
					subs = 5,
				},
				tracks = false,
			},
		},
		weapons = {
			{
				badtargetcategory = "SMALL MINOR",
				def = "TLLGIZMOLAS",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}