return {
	tllmohogeo = {
		activatewhenbuilt = true,
		bmcode = 0,
		buildangle = 8192,
		buildcostenergy = 29800,
		buildcostmetal = 6200,
		builder = false,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 6,
		buildinggrounddecalsizey = 6,
		buildinggrounddecaltype = "tllmohogeo_aoplane.dds",
		buildtime = 160000,
		category = "ALL NOTDEFENSE NOTHOVERNOTVTOL NOTMOBILE NOTSUB NOTSUBNOTSHIP NOTVTOL NOTWEAPON",
		corpse = "tllmohogeo_dead",
		description = "Hazardous Geothermal Foundry Produces Energy/Metal",
		designation = "",
		energymake = 3000,
		energystorage = 3000,
		energyuse = 2500,
		explodeas = "NUCLEAR_MISSILE",
		footprintx = 4,
		footprintz = 4,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 61.29761,
		makesmetal = 35,
		mass = 5950,
		maxdamage = 5320,
		maxslope = 10,
		maxwaterdepth = 0,
		metalstorage = 600,
		name = "Moho Geothermal Foundry",
		noautofire = false,
		nochasecategory = "ALL",
		objectname = "TLLMOHOGEO",
		onoffable = false,
		radaremitheight = 61.29761,
		selfdestructas = "NUCLEAR_MISSILE",
		side = "TLL",
		sightdistance = 210,
		unitname = "tllmohogeo",
		unitnumber = 803,
		usebuildinggrounddecal = true,
		yardmap = "GGGGGGGGGGGGGGGG",
		featuredefs = {
			tllmohogeo_dead = {
				blocking = true,
				category = "tll_corpses",
				damage = 3192.00024,
				description = "wreckage",
				featuredead = "tllmohogeo_heap",
				featurereclamate = "smudge01",
				footprintx = 4,
				footprintz = 4,
				height = 21,
				hitdensity = 105,
				metal = 4760,
				object = "tllmex_dead",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
			tllmohogeo_heap = {
				blocking = false,
				category = "heaps",
				damage = 1915.20007,
				description = "wreckage",
				featurereclamate = "smudge01",
				footprintx = 4,
				footprintz = 4,
				height = 2,
				hitdensity = 105,
				metal = 3808,
				object = "4x4a",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:PILOT",
			},
		},
		sounds = {
			activate = "tllgeo",
			canceldestruct = "cancel2",
			deactivate = "tllgeooff",
			underattack = "tllwarning",
			count = {
				[1] = "tllcount",
				[2] = "tllcount",
				[3] = "tllcount",
				[4] = "tllcount",
				[5] = "tllcount",
				[6] = "tllcount",
			},
			select = {
				[1] = "tllgeosel",
			},
		},
	},
}
