-- UNITDEF -- TLLMONO --
--------------------------------------------------------------------------------

local unitName = "tllmono"

--------------------------------------------------------------------------------

local unitDef = {
	acceleration = 0.1,
	activateWhenBuilt = true,
	bmcode = 1,
	brakeRate = 0.71,
	buildCostEnergy = 230039,
	buildCostMetal = 16100,
	builder = false,
	buildTime = 444423,
	canAttack = true,
	canGuard = true,
	canMove = true,
	canPatrol = true,
	canstop = 1,
	category = [[ALL HUGE MOBILE NOTDEFENSE NOTHOVERNOTVTOL NOTSUB NOTSUBNOTSHIP NOTVTOL WEAPON]],
	copyright = [[Copyright 1997 Humongous Entertainment. All rights reserved.]],
	corpse = [[tllmono_dead]],
	damageModifier = 0.1,
	defaultmissiontype = [[Standby]],
	description = [[Heavy Assault Mech]],
	designation = [[CYBM-019]],
	energyMake = 24,
	energyStorage = 0,
	energyUse = 24,
	explodeAs = [[COMMANDER_BLAST]],
	firestandorders = 1,
	footprintX = 11,
	footprintZ = 11,
	immunetoparalyzer = 1,
	maneuverleashlength = 640,
	manuverleashlength = 2560,
	maxDamage = 72000,
	maxSlope = 36,
	maxVelocity = 0.9,
	maxWaterDepth = 500,
	metalStorage = 0,
	mobilestandorders = 1,
	movementClass = [[HTKBOT11]],
	name = [[Monolith IV]],
	noAutoFire = false,
	noChaseCategory = [[SUB VTOL]],
	objectName = [[tllmono]],
	onoffable = true,
	ovradjust = 1,
	radarDistance = 1200,
	seismicSignature = 5000,
	selfDestructAs = [[COMMANDER_BLAST]],
	shootme = 1,
	side = [[TLL]],
	sightDistance = 640,
	standingfireorder = 2,
	standingmoveorder = 1,
	steeringmode = 1,
	threed = 1,
	turnRate = 108,
	unitname = [[tllmono]],
	unitnumber = 162,
	version = 1,
	workerTime = 0,
	zbuffer = 1,
	featureDefs = nil,
	sounds = {
		canceldestruct = [[cancel2]],
		underattack = [[warning1]],
		cant = {
			[1] = [[cantdo4]],
		},
		count = {
			[1] = [[count6]],
			[2] = [[count5]],
			[3] = [[count4]],
			[4] = [[count3]],
			[5] = [[count2]],
			[6] = [[count1]],
		},
		ok = {
			[1] = [[krogok1]],
		},
		select = {
			[1] = [[krogsel1]],
		},
	},
	weaponDefs = nil,
	weapons = {
		[1] = {
			def = [[heavy_rockets2]],
			onlyTargetCategory = [[VTOL]],
		},
		[2] = {
			def = [[MonoWeap]],
			onlyTargetCategory = [[NOTVTOL]],
		},
		[3] = {
			def = [[Monolith_Shield]],
		},
	},
}

--------------------------------------------------------------------------------

local weaponDefs = {
	heavy_rockets2 = {
		areaOfEffect = 40,
		burst = 1,
		burstrate = 0,
		explosionart = [[favboom]],
		explosiongaf = [[favboom]],
		fireStarter = 70,
		guidance = true,
		id = 252,
		lavaexplosionart = [[lavasplash]],
		lavaexplosiongaf = [[fx]],
		lineOfSight = true,
		model = [[armsalvo2_missile2]],
		name = [[altmyer-Rockets]],
		range = 2000,
		reloadtime = 0.9,
		renderType = 1,
		selfprop = true,
		smokedelay = 0.01,
		smokeTrail = true,
		soundHit = [[bigexplodetll]],
		soundStart = [[harpyattack2]],
		sprayAngle = 3742,
		startsmoke = 1,
		startVelocity = 378,
		tolerance = 9000,
		tracks = true,
		turnRate = 60000,
		turret = true,
		waterexplosionart = [[h2o]],
		waterexplosiongaf = [[fx]],
		weaponAcceleration = 287,
		weaponTimer = 5,
		weaponType = [[MissileLauncher]],
		weaponVelocity = 845,
		damage = {
			default = 400,
			subs = 5,
		},
	},
	Monolith_Shield = {
		id = 9346,
		isShield = true,
		name = [[Monolith_Shield]],
		range = 290,
		shieldAlpha = 0.5,
		shieldBadColor = [[1 0.2 0.2]],
		shieldEnergyUse = 1500,
		shieldForce = 9,
		shieldGoodColor = [[0.2 1 0.2]],
		shieldInterceptType = 1,
		shieldMaxSpeed = 3500,
		shieldPower = 7000,
		shieldPowerRegen = 50,
		shieldPowerRegenEnergy = 300,
		shieldRadius = 290,
		shieldRepulser = true,
		smartShield = true,
		turret = true,
		visibleShield = true,
		visibleShieldRepulse = true,
		weaponType = [[Shield]],
		damage = {
			default = 100,
		},
	},
	MonoWeap = {
		areaOfEffect = 48,
		beamlaser = 1,
		beamTime = 1,
		beamWeapon = true,
		burst = 1,
		burstrate = 0,
		color = 40,
		color2 = 230,
		craterBoost = 0,
		craterMult = 0,
		duration = 4,
		edgeEffectiveness = 0.99,
		energypershot = 20,
		explosionart = [[Shockboom]],
		explosiongaf = [[Shockboom]],
		id = 225,
		intensity = 2,
		lavaexplosionart = [[lavasplashsm]],
		lavaexplosiongaf = [[fx]],
		lineOfSight = true,
		minbarrelangle = -3640,
		model = [[plasma]],
		name = [[Plasma]],
		noautorange = 1,
		range = 1000,
		reloadtime = 1.6,
		renderType = 1,
		soundStart = [[AMATIR]],
		soundTrigger = false,
		startsmoke = 1,
		thickness = 15,
		tolerance = 1820,
		turret = true,
		waterexplosionart = [[h2oboom1]],
		waterexplosiongaf = [[fx]],
		weaponTimer = 300,
		weaponType = [[BeamLaser]],
		weaponVelocity = 780,
		damage = {
			default = 3000,
			subs = 5,
		},
	},
}
unitDef.weaponDefs = weaponDefs


--------------------------------------------------------------------------------

local featureDefs = {
	tllmono_dead = {
		blocking = false,
		category = [[corpses]],
		damage = 0.6000 * unitDef.maxDamage,
		description = [[Monolith Wreckage]],
		energy = 0,
		featureDead = [[tllmono_heap]],
		featurereclamate = [[SMUDGE01]],
		footprintX = 6,
		footprintZ = 6,
		height = 20,
		hitdensity = 100,
		metal = 0.8000 * unitDef.buildCostMetal,
		object = [[TLLMONO_DEAD]],
		reclaimable = false,
		seqnamereclamate = [[TREE1RECLAMATE]],
		world = [[All Worlds]],
	},
	tllmono_heap = {
		blocking = false,
		category = [[heaps]],
		damage = 0.3600 * unitDef.maxDamage,
		description = [[Monolith Heap]],
		energy = 0,
		featurereclamate = [[SMUDGE01]],
		footprintX = 6,
		footprintZ = 6,
		height = 4,
		hitdensity = 100,
		metal = 0.6400 * unitDef.buildCostMetal,
		object = [[6X6A]],
		reclaimable = false,
		seqnamereclamate = [[TREE1RECLAMATE]],
		world = [[All Worlds]],
	},
}
unitDef.featureDefs = featureDefs

--------------------------------------------------------------------------------

return lowerkeys({[unitName] = unitDef})

--------------------------------------------------------------------------------
