local Def = {
	tllobserver = {
		acceleration = 0.045,
		activateWhenBuilt = true,
		bmcode = 1,
		brakeRate = 0.018,
		buildCostEnergy = 1009,
		buildCostMetal = 190,
		buildTime = 3655,
		builder = false,
		canAttack = false,
		canGuard = true,
		canMove = true,
		canPatrol = true,
		canstop = 1,
		category = [[ALL MOBILE NOTVTOL NOTSUB NOTWEAPON NOTDEFENSE MEDIUM NOTSUBNOTSHIP NOTHOVERNOTVTOL]],
		copyright = [[Copyright 1997 Humongous Entertainment. All rights reserved.]],
		corpse = [[dead]],
		damageModifier = 0.75,
		defaultmissiontype = [[Standby]],
		description = [[Mobile Radar Kbot]],
		designation = [[]],
		energyMake = 15,
		energyUse = 45,
		explodeAs = [[BIG_UNITEX]],
		featureDefs = {
			dead = {
				blocking = true,
				category = [[tll_corpses]],
				damage = nil,
				description = [[Wreckage]],
				featureDead = [[heap]],
				featurereclamate = [[smudge01]],
				footprintX = 2,
				footprintZ = 2,
				height = 20,
				hitdensity = 100,
				metal = nil,
				object = [[tllobserver_dead]],
				reclaimable = true,
				seqnamereclamate = [[tree1reclamate]],
				world = [[All Worlds]],
			},
			heap = {
				blocking = false,
				category = [[heaps]],
				damage = nil,
				description = [[Wreckage]],
				featurereclamate = [[smudge01]],
				footprintX = 2,
				footprintZ = 2,
				height = 4,
				hitdensity = 100,
				metal = nil,
				object = [[2x2a]],
				reclaimable = true,
				seqnamereclamate = [[tree1reclamate]],
				world = [[All Worlds]],
			},
		},
		footprintX = 2,
		footprintZ = 2,
		frenchdescription = [[Radar KBot]],
		germandescription = [[Mobiler Radar-KBot]],
		maneuverleashlength = 320,
		maxDamage = 805,
		maxSlope = 16,
		maxVelocity = 1.15,
		maxWaterDepth = 0,
		mobilestandorders = 1,
		movementClass = [[kbot2]],
		name = [[Observer]],
		noAutoFire = false,
		noChaseCategory = [[VTOL SUB]],
		objectName = [[TLLOBSERVER]],
		onoffable = true,
		radarDistance = 1800,
		selfDestructAs = [[BIG_UNIT]],
		shootme = 1,
		side = [[TLL]],
		sightDistance = 240,
		smoothAnim = true,
		sounds = {
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[cantdo4]],
			},
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			ok = {
				[1] = [[kbarmmov]],
			},
			select = {
				[1] = [[kbarmsel]],
			},
			underattack = [[warning1]],
		},
		standingmoveorder = 0,
		steeringmode = 1,
		threed = 1,
		turnRate = 750,
		unitname = [[tllobserver]],
		unitnumber = 862,
		version = 3.1,
		zbuffer = 1,
	},
}
Def.tllobserver.featureDefs.dead.damage = 0.6000 * Def.tllobserver.maxDamage
Def.tllobserver.featureDefs.dead.metal = 0.8000 * Def.tllobserver.buildCostMetal
Def.tllobserver.featureDefs.heap.damage = 0.3600 * Def.tllobserver.maxDamage
Def.tllobserver.featureDefs.heap.metal = 0.6400 * Def.tllobserver.buildCostMetal
return lowerkeys(Def)
