-- UNITDEF -- TLLSEAF --
--------------------------------------------------------------------------------

local unitName = "tllseaf"

--------------------------------------------------------------------------------

local unitDef = {
	acceleration = 0.6,
	amphibious = 1,
	bmcode = 1,
	brakeRate = 4.2,
	buildCostEnergy = 2000,
	buildCostMetal = 275,
	builder = false,
	buildTime = 14731,
	canAttack = true,
	canFly = true,
	canGuard = true,
	canMove = true,
	canPatrol = true,
	canstop = 1,
	canSubmerge = true,
	category = [[ALL MEDIUMVTOL MOBILE NOTDEFENSE NOTSUB NOTSUBNOTSHIP VTOL WEAPON]],
	collide = false,
	copyright = [[Copyright 1997 Humongous Entertainment. All rights reserved.]],
	cruiseAlt = 75,
	defaultmissiontype = [[VTOL_standby]],
	description = [[Seaplane Fighter]],
	designation = [[TL-SEAF]],
	downloadable = 1,
	energyMake = 1,
	energyUse = 1,
	explodeAs = [[SMALL_UNITEX]],
	firestandorders = 1,
	footprintX = 3,
	footprintZ = 3,
	frenchdescription = [[Hydravion de Chasse]],
	germandescription = [[Jäger-Wasserflugzeug]],
	italiandescription = [[Caccia idrovolante]],
	maneuverleashlength = 1280,
	maxDamage = 500,
	maxSlope = 10,
	maxVelocity = 11.5,
	maxWaterDepth = 255,
	mobilestandorders = 1,
	moverate1 = 8,
	name = [[Gull]],
	noAutoFire = false,
	noChaseCategory = [[NOTVTOL SUB]],
	objectName = [[TLLSEAF]],
	radarDistance = 0,
	selfDestructAs = [[SMALL_UNIT]],
	shootme = 1,
	side = [[TLL]],
	sightDistance = 350,
	spanishdescription = [[Hidroavión de Combate]],
	standingfireorder = 2,
	standingmoveorder = 2,
	steeringmode = 1,
	threed = 1,
	turnRate = 512,
	unitname = [[tllseaf]],
	unitnumber = 919,
	version = 1,
	workerTime = 0,
	zbuffer = 1,
	sounds = {
		build = [[nanlath1]],
		canceldestruct = [[cancel2]],
		repair = [[repair1]],
		underattack = [[warning1]],
		working = [[reclaim1]],
		cant = {
			[1] = [[cantdo4]],
		},
		count = {
			[1] = [[count6]],
			[2] = [[count5]],
			[3] = [[count4]],
			[4] = [[count3]],
			[5] = [[count2]],
			[6] = [[count1]],
		},
		ok = {
			[1] = [[vtolcrmv]],
		},
		select = {
			[1] = [[seapsel1]],
		},
	},
	weaponDefs = nil,
	weapons = {
		[1] = {
			badTargetCategory = [[TINYVTOL]],
			def = [[ARMSFIG_WEAPON]],
			onlyTargetCategory = [[VTOL]],
		},
		[2] = {
			badTargetCategory = [[TINYVTOL]],
			def = [[TLLVTOL_MISSILE]],
			onlyTargetCategory = [[VTOL]],
		},
	},
}

--------------------------------------------------------------------------------

local weaponDefs = {
	ARMSFIG_WEAPON = {
		areaOfEffect = 35,
		craterBoost = 0,
		craterMult = 0,
		explosionGenerator = [[custom:FLASH2]],
		fireStarter = 70,
		guidance = true,
		impulseBoost = 0.123,
		impulseFactor = 0.123,
		lineOfSight = true,
		metalpershot = 0,
		model = [[missile]],
		name = [[GuidedMissiles]],
		noSelfDamage = true,
		range = 550,
		reloadtime = 0.85,
		renderType = 1,
		selfprop = true,
		smokedelay = 0.1,
		smokeTrail = true,
		soundHit = [[xplosml2]],
		soundStart = [[Rocklit3]],
		startsmoke = 1,
		startVelocity = 420,
		texture2 = [[armsmoketrail]],
		tolerance = 8000,
		tracks = true,
		turnRate = 19384,
		weaponAcceleration = 146,
		weaponTimer = 6,
		weaponType = [[MissileLauncher]],
		weaponVelocity = 522,
		damage = {
			bombers = 330,
			default = 5,
			fighters = 110,
			flak_resistant = 165,
			unclassed_air = 165,
		},
	},
	TLLVTOL_MISSILE = {
		areaOfEffect = 48,
		collideFriendly = false,
		craterBoost = 0,
		craterMult = 0,
		explosionart = [[explode3]],
		explosiongaf = [[fx]],
		fireStarter = 70,
		guidance = true,
		id = 134,
		impulseBoost = 0.123,
		impulseFactor = 0.123,
		lavaexplosionart = [[lavasplash]],
		lavaexplosiongaf = [[fx]],
		lineOfSight = true,
		metalpershot = 0,
		model = [[tllvtolmissile]],
		name = [[Guided Missiles]],
		noSelfDamage = true,
		range = 530,
		reloadtime = 1,
		renderType = 1,
		selfprop = true,
		smokedelay = 0.1,
		smokeTrail = true,
		soundHit = [[xplosml2]],
		soundStart = [[Rocklit3]],
		startVelocity = 420,
		texture2 = [[armsmoketrail]],
		tolerance = 8000,
		tracks = true,
		turnRate = 16384,
		waterexplosionart = [[h2o]],
		waterexplosiongaf = [[fx]],
		weaponAcceleration = 146,
		weaponTimer = 5,
		weaponType = [[MissileLauncher]],
		weaponVelocity = 480,
		damage = {
			bombers = 270,
			default = 5,
			fighters = 90,
			flak_resistant = 135,
			unclassed_air = 135,
		},
	},
}
unitDef.weaponDefs = weaponDefs

--------------------------------------------------------------------------------

return lowerkeys({[unitName] = unitDef})

--------------------------------------------------------------------------------
