local Def = {
	tlltraq = {
		acceleration = 0.06,
		badTargetCategory = [[VTOL]],
		bmcode = 1,
		brakeRate = 0.21,
		buildCostEnergy = 11234,
		buildCostMetal = 764,
		buildTime = 23659,
		builder = false,
		canAttack = true,
		canGuard = true,
		canMove = true,
		canPatrol = true,
		canstop = 1,
		category = [[KBOT MOBILE ALL NOTSUB NOWEAPON NOTAIR]],
		cloakCost = 50,
		cloakCostMoving = 250,
		corpse = [[dead]],
		defaultmissiontype = [[Standby]],
		description = [[Inflitration Kbot]],
		designation = [[TLL-TK]],
		downloadable = 1,
		energyMake = 51,
		energyStorage = 500,
		energyUse = 5,
		explodeAs = [[SMALL_UNIT]],
		featureDefs = {
			dead = {
				blocking = true,
				category = [[tll_corpses]],
				damage = nil,
				description = nil,
				featureDead = [[heap]],
				featurereclamate = [[smudge01]],
				footprintX = 3,
				footprintZ = 3,
				height = 20,
				hitdensity = 100,
				metal = nil,
				object = [[tlltraq_dead]],
				reclaimable = true,
				seqnamereclamate = [[tree1reclamate]],
				world = [[All Worlds]],
			},
			heap = {
				blocking = false,
				category = [[heaps]],
				damage = nil,
				description = nil,
				featurereclamate = [[smudge01]],
				footprintX = 2,
				footprintZ = 2,
				height = 4,
				hitdensity = 100,
				metal = nil,
				object = [[2x2c]],
				reclaimable = true,
				seqnamereclamate = [[tree1reclamate]],
				world = [[All Worlds]],
			},
		},
		firestandorders = 1,
		footprintX = 2,
		footprintZ = 2,
		healtime = 10,
		initCloaked = true,
		maneuverleashlength = 640,
		maxDamage = 1798,
		maxSlope = 19,
		maxVelocity = 1.5,
		maxWaterDepth = 14,
		metalStorage = 0,
		minCloakDistance = 65,
		mobilestandorders = 1,
		movementClass = [[KBOT2]],
		name = [[Tracker]],
		noAutoFire = false,
		noChaseCategory = [[VTOL]],
		objectName = [[TLLTRAQ]],
		onoffable = true,
		radarDistance = 450,
		selfDestructAs = [[BIG_UNITEX]],
		shootme = 1,
		side = [[TLL]],
		sightDistance = 250,
		sounds = {
			canceldestruct = [[cancel2]],
			cant = {
				[1] = [[cantdo4]],
			},
			count = {
				[1] = [[count6]],
				[2] = [[count5]],
				[3] = [[count4]],
				[4] = [[count3]],
				[5] = [[count2]],
				[6] = [[count1]],
			},
			ok = {
				[1] = [[kbarmmov]],
			},
			select = {
				[1] = [[kbarmsel]],
			},
			underattack = [[warning1]],
		},
		standingfireorder = 2,
		standingmoveorder = 1,
		stealth = true,
		steeringmode = 2,
		threed = 1,
		turnRate = 1005,
		unitname = [[tlltraq]],
		unitnumber = 345665,
		upright = true,
		version = 3,
		weaponDefs = {
			TLLTRAQ_WEAPON = {
				areaOfEffect = 12,
				beamTime = 0.12,
				beamlaser = 1,
				color = 96,
				color2 = 98,
				coreThickness = 0.175,
				damage = {
					default = 330,
				},
				energypershot = 120,
				explosionart = [[explode5]],
				explosiongaf = [[fx]],
				fireStarter = 90,
				id = 234,
				lavaexplosionart = [[lavasplash]],
				lavaexplosiongaf = [[fx]],
				lineOfSight = true,
				name = [[High Energy Laser]],
				range = 380,
				reloadtime = 0.8,
				renderType = 0,
				soundHit = [[lasrhit1]],
				soundStart = [[lasrhvy3]],
				turret = true,
				waterexplosionart = [[h2o]],
				waterexplosiongaf = [[fx]],
				weaponType = [[BeamLaser]],
				weaponVelocity = 1100,
			},
		},
		weapons = {
			[1] = {
				badTargetCategory = [[VTOL]],
				def = [[TLLTRAQ_WEAPON]],
				onlyTargetCategory = [[NOTAIR]],
			},
		},
		workerTime = 0,
		zbuffer = 1,
	},
}
Def.tlltraq.featureDefs.dead.damage = 0.6000 * Def.tlltraq.maxDamage
Def.tlltraq.featureDefs.dead.description = Def.tlltraq.name .. [[ Wreckage]]
Def.tlltraq.featureDefs.dead.metal = 0.8000 * Def.tlltraq.buildCostMetal
Def.tlltraq.featureDefs.heap.damage = 0.3600 * Def.tlltraq.maxDamage
Def.tlltraq.featureDefs.heap.description = Def.tlltraq.name .. [[ Debris]]
Def.tlltraq.featureDefs.heap.metal = 0.6400 * Def.tlltraq.buildCostMetal
return lowerkeys(Def)
