-- UNITDEF -- TLLVIKING --
--------------------------------------------------------------------------------

local unitName = "tllviking"

--------------------------------------------------------------------------------

local unitDef = {
  acceleration       = 0.01,
  badTargetCategory  = [[NOWEAPON]],
  bmcode             = 1,
  brakeRate          = 0.018,
  buildAngle         = 16384,
  buildCostEnergy    = 25311,
  buildCostMetal     = 4712,
  builder            = false,
  buildTime          = 47303,
  canAttack          = true,
  canGuard           = true,
  canMove            = true,
  canPatrol          = true,
  canstop            = 1,
  category           = [[TLL ALL NOTLAND MOBILE WEAPON NOTSUB SHIP NOTAIR]],
  copyright          = [[Copyright 1997 Humongous Entertainment. All rights reserved.]],
  corpse             = [[dead]],
  defaultmissiontype = [[Standby]],
  description        = [[Battleship]],
  designation        = [[]],
  explodeAs          = [[BIG_UNITEX]],
  firestandorders    = 1,
  floater            = true,
  footprintX         = 6,
  footprintZ         = 6,
  frenchdescription  = [[Cuirassé]],
  germandescription  = [[Schlachtschiff]],
  italiandescription = [[Nave da battaglia]],
  maneuverleashlength = 640,
  maxDamage          = 14880,
  maxVelocity        = 2.07,
  minWaterDepth      = 30,
  mobilestandorders  = 1,
  movementClass      = [[DBOAT6]],
  name               = [[Viking]],
  noAutoFire         = false,
  noChaseCategory    = [[VTOL]],
  objectName         = [[TLLVIKING]],
  scale              = 0.6,
  selfDestructAs     = [[BIG_UNIT]],
  shootme            = 1,
  side               = [[TLL]],
  sightDistance      = 1000,
  spanishdescription = [[Acorazado]],
  standingfireorder  = 2,
  standingmoveorder  = 0,
  steeringmode       = 1,
  threed             = 1,
  turnRate           = 67,
  unitname           = [[tllviking]],
  unitnumber         = 902,
  version            = 3.1,
  waterline          = 8,
  zbuffer            = 1,
  sounds = {
    canceldestruct     = [[cancel2]],
    underattack        = [[warning1]],
    cant = {
      [[cantdo4]],
    },
    count = {
      [[count6]],
      [[count5]],
      [[count4]],
      [[count3]],
      [[count2]],
      [[count1]],
    },
    ok = {
      [[sharmmov]],
    },
    select = {
      [[sharmsel]],
    },
  },
  weapons = {
    [1]  = {
      badTargetCategory  = [[VTOL]],
      def                = [[COR_CRUS]],
    },
    [2]  = {
      def                = [[ARM_CRUS]],
    },
    [3]  = {
      def                = [[ARM_BATS]],
    },
  },
}


--------------------------------------------------------------------------------

local weaponDefs = {
  ARM_BATS = {
    accuracy           = 350,
    areaOfEffect       = 96,
    ballistic          = true,
    craterBoost        = 0,
    craterMult         = 0,
    explosionGenerator = [[custom:FLASH96]],
    gravityaffected    = [[true]],
    impulseBoost       = 0.123,
    impulseFactor      = 0.123,
    minbarrelangle     = -25,
    name               = [[BattleshipCannon]],
    noSelfDamage       = true,
    range              = 1090,
    reloadtime         = 0.4,
    renderType         = 4,
    soundHit           = [[xplomed2]],
    soundStart         = [[cannhvy1]],
    startsmoke         = 1,
    tolerance          = 5000,
    turret             = true,
    weaponType         = [[Cannon]],
    weaponVelocity     = 470,
    damage = {
      default            = 300,
      gunships           = 65,
      hgunships          = 65,
      l1bombers          = 65,
      l1fighters         = 65,
      l1subs             = 5,
      l2bombers          = 65,
      l2fighters         = 65,
      l2subs             = 5,
      l3subs             = 5,
      vradar             = 65,
      vtol               = 65,
      vtrans             = 65,
    },
  },
  ARM_CRUS = {
    areaOfEffect       = 16,
    craterBoost        = 0,
    craterMult         = 0,
    explosionGenerator = [[custom:FLASH1]],
    impactonly         = 1,
    impulseBoost       = 0.123,
    impulseFactor      = 0.123,
    lineOfSight        = true,
    minbarrelangle     = -15,
    name               = [[CruiserCannon]],
    noSelfDamage       = true,
    range              = 740,
    reloadtime         = 1.2,
    renderType         = 4,
    soundHit           = [[xplomed2]],
    soundStart         = [[cannhvy1]],
    startsmoke         = 1,
    targetMoveError    = 0.1,
    turret             = true,
    weaponType         = [[Cannon]],
    weaponVelocity     = 550,
    damage = {
      default            = 220,
      gunships           = 40,
      hgunships          = 40,
      l1bombers          = 40,
      l1fighters         = 40,
      l1subs             = 5,
      l2bombers          = 40,
      l2fighters         = 40,
      l2subs             = 5,
      l3subs             = 5,
      vradar             = 40,
      vtol               = 40,
      vtrans             = 40,
    },
  },
  COR_CRUS = {
    areaOfEffect       = 8,
    beamlaser          = 1,
    beamTime           = 0.15,
    coreThickness      = 0.2,
    craterBoost        = 0,
    craterMult         = 0,
    energypershot      = 50,
    explosionGenerator = [[custom:FLASH1]],
    fireStarter        = 90,
    impactonly         = 1,
    impulseBoost       = 0.123,
    impulseFactor      = 0.123,
    lineOfSight        = true,
    name               = [[HighEnergyLaser]],
    noSelfDamage       = true,
    range              = 785,
    reloadtime         = 0.9,
    renderType         = 0,
    rgbColor           = [[0 1 0]],
    soundHit           = [[lasrhit1]],
    soundStart         = [[Lasrmas2]],
    targetMoveError    = 0.175,
    thickness          = 3,
    turret             = true,
    weaponType         = [[BeamLaser]],
    weaponVelocity     = 700,
    damage = {
      default            = 180,
      gunships           = 44,
      hgunships          = 44,
      l1bombers          = 44,
      l1fighters         = 44,
      l1subs             = 5,
      l2bombers          = 44,
      l2fighters         = 44,
      l2subs             = 5,
      l3subs             = 5,
      vradar             = 44,
      vtol               = 44,
      vtrans             = 44,
    },
  },
}
unitDef.weaponDefs = weaponDefs


--------------------------------------------------------------------------------

local featureDefs = {
  dead = {
    blocking           = true,
    category           = [[tll_corpses]],
    damage             = unitDef.maxDamage*0.6,
    description        = [[Wreckage]],
    featureDead        = [[heap]],
    featurereclamate   = [[smudge01]],
    footprintX         = 6,
    footprintZ         = 6,
    height             = 20,
    hitdensity         = 100,
    metal              = unitDef.buildCostMetal*0.8,
    object             = [[tllviking_dead]],
    reclaimable        = true,
    seqnamereclamate   = [[tree1reclamate]],
    world              = [[All Worlds]],
  },
  heap = {
    blocking           = false,
    category           = [[heaps]],
    damage             = unitDef.maxDamage*0.36,
    description        = [[Wreckage]],
    featureDead        = [[heap2]],
    featurereclamate   = [[smudge01]],
    footprintX         = 6,
    footprintZ         = 6,
    height             = 4,
    hitdensity         = 100,
    metal              = unitDef.buildCostMetal*0.64,
    object             = [[4x4c]],
    reclaimable        = true,
    seqnamereclamate   = [[tree1reclamate]],
    world              = [[All Worlds]],
  },
  heap2 = {
    blocking           = false,
    category           = [[heaps]],
    damage             = unitDef.maxDamage*0.216,
    description        = [[Wreckage]],
    featurereclamate   = [[smudge01]],
    footprintX         = 6,
    footprintZ         = 6,
    height             = 4,
    hitdensity         = 100,
    metal              = unitDef.buildCostMetal*0.512,
    object             = [[3x3a]],
    reclaimable        = true,
    seqnamereclamate   = [[tree1reclamate]],
    world              = [[All Worlds]],
  },
}
unitDef.featureDefs = featureDefs


--------------------------------------------------------------------------------

return lowerkeys({ [unitName] = unitDef })

--------------------------------------------------------------------------------
