return {
	tllviking = {
		acceleration = 0.09,
		bmcode = 1,
		brakerate = 1.62,
		buildangle = 16384,
		buildcostenergy = 25311,
		buildcostmetal = 4712,
		builder = false,
		buildtime = 47303,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL HUGE MOBILE NOTDEFENSE NOTHOVERNOTVTOL NOTSUB NOTVTOL WEAPON",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Battleship",
		designation = "",
		explodeas = "BIG_UNITEX",
		firestandorders = 1,
		floater = true,
		footprintx = 6,
		footprintz = 6,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 38.29916,
		maneuverleashlength = 640,
		mass = 4712,
		maxdamage = 16500,
		maxvelocity = 2.47,
		minwaterdepth = 30,
		mobilestandorders = 1,
		movementclass = "DBOAT6",
		name = "Viking",
		noautofire = false,
		nochasecategory = "VTOL",
		objectname = "TLLVIKING",
		radaremitheight = 38.29916,
		scale = 0.6,
		selfdestructas = "BIG_UNIT",
		shootme = 1,
		side = "TLL",
		sightdistance = 1000,
		standingfireorder = 2,
		standingmoveorder = 0,
		steeringmode = 1,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1.6302,
		turnrate = 307,
		unitname = "tllviking",
		unitnumber = 902,
		waterline = 8,
		featuredefs = {
			dead = {
				blocking = true,
				category = "tll_corpses",
				damage = 9900,
				description = "Wreckage",
				featuredead = "heap",
				featurereclamate = "smudge01",
				footprintx = 6,
				footprintz = 6,
				height = 20,
				hitdensity = 100,
				metal = 3769.6001,
				object = "tllviking_dead",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 5940,
				description = "Wreckage",
				featuredead = "heap2",
				featurereclamate = "smudge01",
				footprintx = 6,
				footprintz = 6,
				height = 4,
				hitdensity = 100,
				metal = 3015.67993,
				object = "4x4c",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
			heap2 = {
				blocking = false,
				category = "heaps",
				damage = 3564,
				description = "Wreckage",
				featurereclamate = "smudge01",
				footprintx = 6,
				footprintz = 6,
				height = 4,
				hitdensity = 100,
				metal = 2412.54419,
				object = "3x3a",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "sharmmov",
			},
			select = {
				[1] = "sharmsel",
			},
		},
		weapondefs = {
			arm_bats = {
				accuracy = 350,
				areaofeffect = 96,
				ballistic = true,
				cegtag = "Trail_cannon",
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASH96",
				gravityaffected = "TRUE",
				impulseboost = 0.123,
				impulsefactor = 0.123,
				minbarrelangle = -25,
				name = "BattleshipCannon",
				nogap = 1,
				noselfdamage = true,
				range = 1090,
				reloadtime = 0.4,
				rendertype = 4,
				rgbcolor = "0.86 0.62 0",
				separation = 0.45,
				size = 1.82,
				sizedecay = -0.15,
				soundhitdry = "xplomed2",
				soundstart = "cannhvy1",
				stages = 20,
				startsmoke = 1,
				tolerance = 5000,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 470,
				damage = {
					default = 300,
					subs = 5,
				},
			},
			arm_crus = {
				areaofeffect = 16,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASH1",
				impactonly = 1,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				lineofsight = true,
				minbarrelangle = -15,
				name = "CruiserCannon",
				noselfdamage = true,
				range = 740,
				reloadtime = 1.2,
				rendertype = 4,
				rgbcolor = "1 0.95 0.9",
				size = 0.94,
				soundhitdry = "xplomed2",
				soundstart = "cannhvy1",
				startsmoke = 1,
				targetmoveerror = 0.1,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 550,
				damage = {
					default = 220,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ARM_BATS",
				onlytargetcategory = "NOTVTOL",
			},
			[2] = {
				def = "ARM_CRUS",
				onlytargetcategory = "NOTVTOL",
			},
			[3] = {
				def = "ARM_CRUS",
				onlytargetcategory = "NOTVTOL",
			},
		},
	},
}
